.npmignore
.storybook/addons.js
.storybook/config.js
.travis.yml
package-lock.json
package.json
scripts/sass.js
src/components/Choice/Input.js
src/styles/blue.hs-app.scss
src/styles/components/Input/InputBackdrop.scss
src/styles/mixins/backdrop-styles.scss
src/styles/themes/hs-app/__index.scss
src/styles/themes/hs-app/components/Choice.scss
src/styles/themes/hs-app/components/HelpText.scss
src/styles/themes/hs-app/components/Input.scss
src/styles/themes/hs-app/components/Text.scss
src/styles/themes/hs-app/components/__index.scss
src/styles/themes/hs-app/configs/_color.scss
src/styles/themes/hs-app/configs/_constants.scss
src/styles/themes/hs-app/mixins/visibility.scss
src/styles/themes/hs-app/resets/_base.scss
stories/Checkbox.js
stories/index.js

This update adds an `hs-app` stylesheet (.scss/.css) for Blue. The idea for this is to allow for Blue components to be seamlessly dropped into `hs-app` with no/minimal issues in UI consistency.
Typically, it should be up to the consumer of this package (`hs-app`) to write the custom CSS necessary to override Blue, as Blue should be application agnostic. However, I think this approach is fine, and is the easiest/fastest way for us to start integrating into multiple projects.
Minimal adjustments were made to the actual React JS components. Most of these changes are SCSS based, and are isolated within the new `hs-app` theme directory under `src/styles/themes/hs-app`.
The idea for this came about during a call I had with @knicklabs.
To use the `hs-app` theme stylesheet, simply import add it …

Add HS-App theme stylesheet for components

---

src/components/Modal/index.js
src/components/Modal/tests/Modal.test.js
src/components/Portal/index.js
src/components/PortalWrapper/README.md
src/components/PortalWrapper/index.js
src/components/PortalWrapper/tests/PortalWrapper.test.js
stories/Animate.js
stories/Modal.js

This update improves the lifecycle callbacks for Portal and PortalWrapper. Portal has been adjusted to allow for re-rendering of child components based on prop changes, which is handy (and necessary) for things like child unmounting animations or `style` prop changes (will come in handy for `Popover`/`Tooltip`).
A new prop from Portal has been exposed in PortalWrapper called `isMounted`. It is similar to `isOpen`, but it's state is changed slightly before `isOpen`, allowing for child components to execute callbacks that need to happen before the Portal child is removed from the DOM (like Animations).
```jsx
import Animate from '../Animate'
import Overlay from '../Overlay'
import PortalWrapper from '../PortalWrapper'
const portalOptions = {
id: 'MyModal',
timeout: 400
}
const MyModal = …
```

Improve Portal mount cycle

---

package-lock.json
src/components/Checkbox/index.js
src/components/Choice/Input.js
src/components/Choice/README.md
src/components/Choice/index.js
src/components/Choice/tests/Choice.test.js
src/components/Choice/tests/ChoiceInput.test.js
src/components/ChoiceGroup/index.js
src/components/Input/index.js
src/components/PortalWrapper/index.js
src/components/Radio/index.js
src/styles/components/Choice/ChoiceInput.scss
src/styles/components/Input/Input.scss
src/styles/mixins/backdrop-styles.scss
src/utilities/id.js
stories/Checkbox.js

This update fixes the `uniqueID()` generation for the `Choice` component, which indirectly fixes it for `Checkbox` and `Radio`. The same fix was also applied to `Input` and `PortalWrapper`.
This issue was the element's ID was being regenerated everytime there was a prop change, which is incorrect. It should only be generated once. The solution was to generate and store the uniqueID in the component state, instead of creating it in the render hook.
The uniqueID creation factory function has also been enhanced to accept a prefix override namespace.

Choice: Fix ID generation

---

src/styles/components/Icon.scss

The path to the color configuration in the CSS for the icon component was incorrect. This PR is to switch it to the correct path.

Fix path on import for color config

---

src/components/ProgressBar/README.md
src/components/ProgressBar/index.js
src/components/ProgressBar/tests/ProgressBar.test.js
src/styles/components/ProgressBar.scss

This update adds the `role="progressbar"` tag, as well as `aria-valuenow`, `aria-valuemin`, `aria-valuemax` and `aria-valuetext`.
The following code:
```
<ProgressBar value={20} />
```
Will render:
```html
<div data-reactroot="" class="c-ProgressBar" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">
<div class="c-ProgressBar__bar" style="width: 50%;"></div>
</div>
```
Follow up for https://github.com/helpscout/blue/pull/30

ProgressBar: Add accessibility aria tags

---

package-lock.json
package.json
scripts/sass.js
src/components/Button/index.js
src/components/Button/tests/Button.test.js
src/components/Card/index.js
src/components/Card/tests/Card.test.js
src/components/CardBlock/index.js
src/components/CardBlock/tests/CardBlock.test.js
src/components/Choice/tests/ChoiceInput.test.js
src/components/Flexy/Block.js
src/components/Flexy/Flexy.js
src/components/Flexy/Item.js
src/components/Link/index.js
src/components/Link/tests/Link.test.js
src/styles/blue.hs-app.slim.scss
src/styles/components/Button.scss
src/styles/components/Card.scss
src/styles/components/Flexy.scss
src/styles/components/Link.scss
src/styles/components/__slim.scss

This update adds a new `blue.hs-app.slim.scss` file that only includes not within `hs-app`. This will reduce the overall build size of `hs-app`'s CSS.
The approach I took was to comment out all of the component imports in the dedicated slim file. It's not ideal, as you'd have to update 2 .scss files everytime a new component style is added. However, it's the simplest solution for now.
To integration into hs-app, simply import the slim file:
```
@import "blue.hs-app.slim";
```
No need to import the base Blue styles + hs-app theme (which was the previous approach)
In addition to this, the components that leverage seed styles have had their classNames restored to the default classNames found in Seed.
Example:
`c-Link` -> `c-link`
CC'ing @knicklabs ❤️ 
Resolves: …

CSS: Create hs-app dedicated stylesheet without duplicate styles

---

package.json
src/components/Button/README.md
src/components/Button/index.js
src/components/Button/tests/Button.test.js
src/components/Link/README.md
src/components/Link/index.js
src/components/Link/tests/Link.test.js
src/components/RouteWrapper/README.md
src/components/RouteWrapper/index.js
src/components/RouteWrapper/tests/RouteWrapper.test.js

In beacon embed, we had a problem where we wanted to fetch some data from the server before navigating to a new <Route>. To make this easier, this Pull Request creates a Higher Order Component, `RouteWrapper`, which wraps around components and adds `fetch` and `to` properties. The `to` property works like the `to` on a React Router `<Link>`, but the `fetch` property lets you specify a thunk-returning function to fetch data before triggering the route specified in `to`. 
The `<Link>` and `<Button>` components have been wrapped with `RouteWrapper`, which means we can now do things like:
```javascript
<Link fetch="fetchArticle" to={`docs/articles/${id}`}>
<Button fetch="fetchArticles" to="docs/articles">
<Button to="synchronous/route/path">
```

Add RouteWrapper higher order component to add `fetch` and `to` attributes

---

src/components/PortalWrapper/index.js
src/components/SidebarCollapsibleCard/index.js
src/components/SidebarCollapsibleCard/tests/SidebarCollapsibleCard.test.js
stories/Modal.js

This update allows for the `SidebarCollapsibleCard` open state to be influenced by the prop change of `isOpen`, allowing for more programmatic control from a parent component/container.

SidebarCollapsibleCard: Toggle open with prop change

---

src/components/Choice/index.js
src/components/ChoiceGroup/index.js
src/components/Input/Resizer.js
src/components/Input/index.js
src/components/Portal/index.js
src/components/PortalWrapper/index.js
src/components/SidebarCollapsibleCard/index.js
stories/Animate.js
stories/Collapsible.js

This update moves the instantiation of `bind(this)` from the `render()` method to `constructor()` for non-Stateless components. This is done for performance + best practice reasons.
Thanks to @brettjonesdev for the tip!

Move `bind(this)` to `constructor()` method for Components

---

src/components/Avatar/index.js
src/components/Avatar/tests/Avatar.test.js
src/components/Link/index.js

Beacon API is going to be specifying an `initials` attribute, which we want to use to override the default `<Avatar>` initials parsing from the `name` attribute. This PR adds an `initials` property to the `Avatar` component.

Add an `initials` attribute to the `<Avatar>` component. 

---

src/components/Avatar/index.js
src/components/Avatar/tests/Avatar.test.js

Bug fix - `initials` was being passed down into the `Avatar`'s `div`.

Fix `initials` attribute being passed down to `<Avatar>` <div>

---

src/components/Sortable/index.js
src/components/Sortable/tests/Sortable.test.js

This update fixes the Sortable component lifecycle to update the remapped `state.items` when there is a change in `props.children`. Previously, this was only firing on mount, but it now fires on `componentWillReceiveProps` as well.
Resolves: https://github.com/helpscout/blue/issues/49

Sortable: Re-render children on children prop change

---

src/components/Modal/tests/Modal.test.js
src/components/Portal/tests/Portal.test.js

Extending times from `100ms` to `300ms`. Ideally, we wouldn't use timeouts for these. Maybe there's an enzyme hook I can tap into to test mount/unmount related things?
It's tricky though, since these tests check for `document` related things, outside of the `Portal` react component.

Extend timeout values for Portal.test.js

---

README.md
package-lock.json
package.json
yarn.lock

This update adds the `deploy` npm script, which initializes [stroybook-deployer](https://github.com/storybooks/storybook-deployer).
This publishes to http://developer.helpscout.net/blue/

Deploy to gh-pages via Storybook deployer 

---

src/components/Input/README.md
src/components/Input/index.js
src/components/Input/tests/Input.test.js
stories/Input.js

It may be desirable to have text appear above and/or below the input but currently it is only possible to configure the input to have text appear below it via the `helpText` prop.
This PR adds a `hintText` prop that can be used to configure the input to have text appear above it, as shown below.

Add hint text to input component

---

package.json

Move project dependencies to dependencies instead of devDependencies.
Some of these items are used by polyfill.js (by create-react-app).
Others are being used by Blue components.
Spotted by @lgariepy

Resolve Blue dependencies

---

.gitignore
src/components/SidebarCollapsibleCard/index.js

Currently, when I click on the toggle on the `SidebarCollapsibleCard` component, the browser navigates to "#". This is a quick fix to prevent that behavior.
I also added a new line to .gitignore, for those of us who are using PHPStorm (me 😄 )

Prevent default on SidebarCollapsibleCard link click

---

src/components/Modal/README.md
src/components/Modal/index.js
src/components/Modal/tests/Modal.test.js
src/components/Scrollable/README.md
src/components/Scrollable/index.js
src/components/Scrollable/tests/Scrollable.test.js
src/utilities/node.js
stories/Modal.js

* Add `scrollableRef` prop to Scrollable and Modal to expose the scrollable DOM node
* Add `onScroll` callback for Modal
* Make `isNodeElement()` util more robust

Add scrollableRef to Scrollable and Modal

---

src/styles/components/Modal.scss

This update adds padding to the correct selector (`.c-Scrollable__content`) instead of `.c-Scrollable`.

Modal: Fix Scrollable padding within a Modal

---

src/components/Card/Block.js
src/components/Card/README.md
src/components/Card/docs/Block.md
src/components/Card/docs/Card.md
src/components/Card/index.js
src/components/Card/tests/Card.Block.test.js
src/components/Card/tests/Card.test.js
src/components/Link/index.js
src/components/Link/tests/Link.test.js
src/styles/components/Card/Card.scss
src/styles/components/Link.scss

This update enhances the Card component to render a Link component if href/to is provided. This allows for Card to use react-router, if needed.
Card.Block has also been enhanced with the new Scrollable props, specificaly scrollableRef and onScroll.
Lastly, the Link component receives a new prop (`block`), that provides it with the ability to render as `display: block`.
* Card CSS className has been resolved
* Link c-link has been renamed to c-Link

Card: Integrate Link component for href/to props

---

src/styles/components/Card/Card.scss

This update ensures that went the Card component becomes a wrapper for Link, that it has a background-color.
Previously, the CSS for Link was reseting the background-color to transparent.

Card: Link variant has a background-color

---

src/components/InfiniteScroller/index.js
src/components/InfiniteScroller/tests/InfiniteScroller.test.js

This update provides InfiniteScroller with an internal `_isMounted` "state", which prevents setState issues when the component is unmounted. This could happen if a callback takes longer than expected, and InfiniteScroller is used within something like a Modal.
The logic for callback methods has been fixed within `componentWillReceiveProps`.

InfiniteScroller: Improve callback stability

---

src/components/Collapsible/README.md
src/components/Collapsible/index.js
src/components/Collapsible/tests/Collapsible.test.js
src/components/SidebarCollapsibleCard/README.md
src/components/SidebarCollapsibleCard/index.js
src/components/SidebarCollapsibleCard/tests/SidebarCollapsibleCard.test.js
src/components/Sortable/DragHandle.js
src/components/Sortable/List.js
src/components/Sortable/index.js
src/components/Sortable/tests/Sortable.test.js
stories/SidebarCollapsibleCard.js

This update fixes Sortable's handling of child item keys. Sortable now respects unique keys, and uses ID props if specified.
SidebarCollapsibleCard gains 2 new hooks: onSortStart and onSortEnd that fire when the component is being sorted. The react-sortable-hoc did NOT provide any callback methods for these hooks for the DraggableHandle, only at the Container level. So I had to come up with a creative solution to get this to work.
The two props allow for SidebarCollapsibleCard to be better integrated into Sortable.
Collapsible gains 2 new props: durationOpen and durationClose, that fallback to duration. This allows you to pass in different timings for the animation, allow for a smoother collapse experience with SidebarCollapsibleCard.
Resolves: https://github.com/helpscout/blue/issues/74 …

SidebarCollapsibleCard: Improve Sortable interactions

---

src/components/Card/index.js
src/components/Card/tests/Card.test.js

After upgrading Blue to the latest version in Beacon, I found out that the `Card` component no longer had an `onClick` handler when they were given an `href` or `to` attribute. I've added it back to fix its behavior.

Added onClick handler back to the Card component

---

package-lock.json
package.json
src/components/Alert/README.md
src/components/Alert/index.js
src/components/Alert/tests/Alert.test.js
src/components/CloseButton/README.md
src/components/CloseButton/index.js
src/components/CloseButton/propTypes.js
src/components/CloseButton/tests/CloseButton.test.js
src/components/index.js
src/styles/components/Alert.scss
src/styles/components/CloseButton.scss
src/styles/components/__index.scss
src/tests/index.test.js
stories/Alert.js
stories/index.js

This update adds a new Alert component, with the styles come from [seed-alert](http://developer.helpscout.net/seed/packs/seed-alert/).
```jsx
<Alert dismissable icon>
Not now Arctic Puffin!
</Alert>
```
Additionally, the `CloseButton` component was enhanced with a new `seamless` style and new `size` props to allow it to be used within Alert for dismissal.
This one is for you @ryan-mulrooney ❤️ 
Resolves: https://github.com/helpscout/blue/issues/87

Add Alert component

---

src/components/KeypressListener/index.js
src/components/KeypressListener/tests/KeypressListener.test.js
src/utilities/node.js
src/utilities/tests/node/getClosestDocument.test.js

This update adds a new node util, that retrieves the closest `document`, given
a DOM node. This allows for KeypressListener to be used within an `iframe`,
and bind events to the iframe `document`, vs the global window `document`.
The scope is automatically set in the KeypressListener component. Various
other Blue components that use these bindings like Portal, Modal, or Dropdown,
do not need to be updated.

KeypressListener: Work with iframes

---

src/styles/components/Input/InputField.scss
src/styles/mixins/input-styles.scss
stories/Input.js

(Chrome)
(Safari)
This update adjusts the CSS for Input (and indirectly, Select), to allow for
the webkit autocomplete state to render correctly.
Previously, the autocomplete styles were overlapping the Input component's
"Backdrop" layer (a technique used to render the appearance/border of the
component). To resolve this, I've added a 1px padding around the container,
which simulates the offset a typical non-backdrop border would provide.
With this change, the autocomplete styles no-longer overflow on top of
the backdrop layer.
This update is purely a CSS change. The only JS changes made were to update
the Input component Stories to add an autocomplete example (and to refactor).
:clap:
These changes were manually visually tested in Chrome + Safari. Also tested in Firefox for regressions. …

Input: Fix webkit autocomplete styles

---

src/styles/components/Input/InputResizer.scss

This update adds `overflow:hidden` to the wrapping component of the input
ghosts. This ensures that the ghost components (that are involved in Input
multiline calculation) don't affect the layout.
Tested in Storybook. This change does not prevent the Input component from
re-calculating the height.
Resolves: https://github.com/helpscout/blue/issues/104

Input: Multiline - Fix ghost overflow

---

src/components/Drop/Positioner.js
src/components/Dropdown/Menu.js
src/utilities/node.js
src/utilities/nodePosition.js
src/utilities/tests/node/getScrollParent.test.js
src/utilities/tests/nodePosition/getDirectionY.test.js
src/utilities/tests/nodePosition/getViewportPosition.test.js
stories/Dropdown.js

This update simplifies the positioning calculations used by the Dropdown
component (more accurately, the Drop.Positioner component).
The adjusted positions are similar to the ones available in other
Dropdown libraries, like Bootstrap.
This is a temporary "downgrade", until I can implement the [12/16-point
positioning system](https://github.com/helpscout/blue/issues/103), that we can leverage for Tooltips and Popovers.
For now, the Drop.Positioner calculations only benefit Dropdown.
Note: Up/down recalcuation is still available. However, left/right
recalculations have been removed.
The DropdownMenu has also been enhanced to only `scrollIntoView` if the
Scrollable component has a scrollbar. This is to resolve that function
forcing the window to scroll.

Dropdown: Simplify positioning

---

src/components/Drop/index.js
src/components/Drop/tests/Drop.test.js
src/components/Dropdown/tests/Menu.test.js

This update fixes the Drop HOC to correctly pass `className` and `style` props
to the ComposedComponent.

Drop: Fix className and style props for ComposedComponent

---

package-lock.json
package.json
src/tests/libraries/helix/createSpec.test.js
src/tests/libraries/helix/faker.test.js
src/tests/libraries/helix/withReactComponents.test.js

This update adds [Helix](https://github.com/helpscout/helix), our fixture generating library.
Simple integration tests with Helix has also been added.
Resolves: https://github.com/helpscout/blue/issues/110

Add Helix + simple integration tests

---

src/components/Portal/index.js
src/components/PortalWrapper/index.js
src/components/PortalWrapper/tests/PortalWrapper.test.js
src/utilities/globalManager.js
src/utilities/tests/globalManager.test.js

This update adds a new "Manager" to the PortalWrapper component,
created with the new `globalManager` utility. This manager ensures
that pressing Escape ONLY closes the most recently Portal'ed component.
This is done by the manager tracking the IDs (which are unique) of
all the PortalWrapper created components.
This has been tested with Modals as well as Dropdowns.
Resolves: https://github.com/helpscout/blue/issues/97

Pressing ESC should not close all Portal components

---

package-lock.json
package.json
src/components/Modal/tests/Modal.test.js
src/components/Portal/tests/Portal.test.js
src/components/PortalWrapper/Content.js
src/components/PortalWrapper/index.js
src/components/PortalWrapper/tests/Content.test.js
src/utilities/globalManager.js
src/utilities/id.js
src/utilities/tests/id.test.js
stories/Modal.js
test/acceptance/components/Dropdown.spec.js
test/acceptance/components/Modal.spec.js
test/acceptance/test-helpers.js

This commit resolves the issue where Route (react-router) mounted
components built with PortalWrapper (specifically Modals) don't
correctly close when the ESCAPE key is pressed.
This is due to `react-router` injecting the Modals in a non-linear
order. To resolve this, I've adjusted how PortalWrapper works with
it's GlobalManager. Instead of using IDs, it will use unique
incrementing index number values. This ensures that the latest
injected component, always has the highest index value. Therefore,
when triggere a close (with the escape key), the GlobalManager will
look for the highest index value and execute the close action it.
Unit tests were enhanced, but more importantly, acceptance tests
were added to test out these interactions, especially with
route changes/ESCAPE interactions. …

PortalWrapper: Fix integration with Route usage

---

src/components/Icon/README.md
src/components/Icon/index.js
src/components/Icon/tests/Icon.test.js
src/styles/components/Icon.scss
stories/Icon.js
test/acceptance/components/Icon.spec.js
test/acceptance/components/StatusDot.spec.js

This update adds a new `withCaret` prop, which renders a small caret
on the right hand side of an Icon component. The caret is automatically
aligned in the center (vertically), regardless of icon size. The caret
does not hinder other prop styles like `center`, and inherits the same
SVG fill color as the regular icon.
To make triple sure of this, I've written some Karma acceptance tests 🎉.
P.S. Acceptance tests are awesome. Boy, I love being able to test
ACTUAL DOM properties.
Partially resolves: https://github.com/helpscout/blue/issues/129

Icon: Add ability to have a (right) side caret

---

src/components/Modal/index.js
src/components/Modal/tests/Modal.test.js
src/components/Scrollable/index.js
src/styles/components/Modal.scss
src/vendors/getScrollbarWidth.js
test/acceptance/components/Modal.spec.js

This update adjusts the width of the Scrollable faders and the position
of the CloseButton for Modal. Previously, these elements had fixed
sizes/offsets, which overlapped with the (native) scrollbar that appears.
To remedy this, a util function was added to calculate the web
scrollbar width, determined by the OS. Calculcations where then added
to inline styles when applicable.
This update also fixes the Modal scroll bug, introduced by the
AnimeJS integration.
Resolves: https://github.com/helpscout/blue/issues/141

Modal: Fix overlapping UI for scrollable content

---

src/components/Modal/README.md
src/components/Modal/index.js
src/components/Modal/tests/Modal.test.js
stories/Modal.js

This update adds the ability to render the children content of
Modals without it's standard Card UI-based container. All that's
required is to pass the `seamless` prop, which is set to `false`
by default.
Resolves: https://github.com/helpscout/blue/issues/140

Modal: Add the ability to render cardless content

---

src/components/Avatar/README.md
src/components/Avatar/index.js
src/components/Avatar/tests/Avatar.test.js
stories/Avatar/index.js

This update provides Avatar with a new `statusIcon` prop, which renders
a specified Icon within the Avatar's StatusDot component.
Resolves: https://github.com/helpscout/blue/issues/136

Avatar: Allow for StatusDot to render an Icon

---

src/components/Animate/tests/Animate.test.js
src/components/Scrollable/index.js

This update fixes the error that happens when Scrollabe is
mounted/unmounted very quickly, and affects the `faderNode`.
The can now only apply inline styles if the `faderNode` exists in
the DOM.
Resolves: https://github.com/helpscout/blue/issues/146

Scrollable: Fix faderNode style bug

---

src/components/Animate/animations/expand.js
src/components/Animate/animations/flip.js
src/components/Animate/animations/index.js
src/components/Animate/animations/right.js
stories/AnimateGroup/index.js

This adds additional Storybook examples for Animate. It also fixes
the `right` animation sequence, and adds an `expand` sequence.

Animate: Add additional examples

---

src/components/Drop/README.md
src/components/Drop/index.js
src/components/Drop/tests/Drop.test.js
src/components/Modal/README.md
src/components/Modal/index.js
src/components/Modal/tests/Modal.test.js
src/components/PortalWrapper/index.js
src/components/PortalWrapper/tests/PortalWrapper.test.js
src/utilities/component.js
src/utilities/tests/component/getComponentDefaultProp.test.js
stories/index.js

This update adds a new `wrapperClassName` prop for the composed
components generated by PortalWrapper. This allows you to add
custom class names to the surrounding Portal'ed `div`, providing
extra CSS flexibility (if needed).
This is an enhancement, and no component API changes are required
on the user's end.
Tests + documentation has been added for this update :rocket:

PortalWrapper: Add wrapperClassName

---

package-lock.json
src/components/Modal/Body.js
src/components/Modal/Footer.js
src/components/Modal/Header.js
src/components/Modal/README.md
src/components/Modal/docs/Body.md
src/components/Modal/docs/Footer.md
src/components/Modal/docs/Header.md
src/components/Modal/docs/Modal.md
src/components/Modal/index.js
src/components/Modal/tests/Body.test.js
src/components/Modal/tests/Footer.test.js
src/components/Modal/tests/Header.test.js
src/components/Modal/tests/Modal.test.js
src/components/Toolbar/Toolbar.js
src/components/Toolbar/docs/Toolbar.md
src/components/Toolbar/tests/Toolbar.test.js
src/styles/components/Modal/Modal.scss
src/styles/components/Modal/ModalBody.scss
src/styles/components/Modal/ModalFooter.scss
src/styles/components/Modal/ModalHeader.scss
src/styles/components/Modal/__index.scss
src/styles/components/Toolbar/Toolbar.scss
src/styles/components/__index.scss
stories/Modal.js

This update adds a new sub-components to Modal: Header, Body, and Footer.
This Header and Footer sub-components are constructed with Toolbar,
and allow you to easily add items (typically action items) to a
Modal dialog.
**Example**
```jsx
<Modal>
<Modal.Header>
...
</Modal.Header>
<Modal.Body>
...
</Modal.Body>
<Modal.Footer>
...
</Modal.Footer>
</Modal>
```
The Modal component has been adjusted to accommodate the new
required markup structure. It is recommended that content is added
into Modal using a `Modal.Body` wrapper. However, if one is not
provided, the Modal component will automatically wrap the content for
you. This is so that the responsive behaviour of the Modal
(powered by CSS flexbox) is preserved.
The docs have been updated to encourage use of Modal.Body.
Resolves: …

Modal: Add Header/Body/Footer sub-components

---

package.json
src/components/InfiniteScroller/tests/InfiniteScroller.test.js
src/components/Message/Media.js
src/components/Modal/Body.js
src/components/Modal/Content.js
src/components/Modal/README.md
src/components/Modal/docs/Body.md
src/components/Modal/docs/Content.md
src/components/Modal/docs/Modal.md
src/components/Modal/index.js
src/components/Modal/tests/Body.test.js
src/components/Modal/tests/Modal.test.js
src/styles/components/Modal/Modal.scss
src/styles/components/Modal/ModalBody.scss
src/styles/components/Modal/ModalContent.scss
src/styles/components/Modal/__index.scss
src/utilities/log.js
stories/Modal.js
test/acceptance/components/Modal.spec.js

This update adds a new Modal.Content sub-component for Modal.
The idea for the sub-component is to support swapping Modal's `children`
from one set of components to another (e.g. loading conditions).
As if this update, Modal will no longer render anything inside that
isn't a sub-component. This is to enforce the new component
pattern required.
This update makes it slightly more verbose to add Modal content.
However, it enables better and more reliable flexibility in rendering
various types of content.
**Note to consumers of Blue: This update changes the Modal component
API. Please refer to the docs (or see examples below) if you notice
that your Modals are not rendering content.**
**Example**
```jsx
<Modal>
<Modal.Content>
...
</Modal.Content>
</Modal>
```
This will still work:
```jsx …
```

Modal: Add Content sub component

---

package-lock.json
package.json
src/components/AvatarList/index.js
src/components/List/List.js
src/components/List/docs/List.md
src/components/List/tests/List.test.js
src/components/Modal/index.js
src/components/Modal/tests/Modal.test.js
src/styles/components/List.scss

This update is a follow-up to the Modal.Content sub-component addition.
When implementing the new Modal structure, I discovered by rejecting
non-sub-component children, it causes unexpected issues for wrapper-like
components.
**This restriction has been removed for Modal.**
It is still highly recommended that you use either Modal.Body or Modal.Content to ensure that the UI looks correct.
There was a CSS bug that was introduced into Lists during the Tag
enhancement, which changed the display from `block` to `flex`.
This update fixes this by defaulting to a display of `block`, but
providing the ability to use `flex` via a prop.
Follow-up to https://github.com/helpscout/blue/releases/tag/v0.0.73

Modal and List: Bug Fixes

---

src/components/Modal/index.js

This update accounts for the rare edge case where a child component
of a Modal may be `null`.

Modal: Handle null child

---

src/components/Modal/Content.js
src/components/Modal/tests/Content.test.js
src/components/Modal/tests/Modal.test.js

This update fixes the `Modal.Content` sub-component to also
handle `null` children content. Tests for `null` were added to
`Modal.Content` and `Modal`.

Modal.Content: To handle null children

---

src/components/Modal/Body.js
src/components/Modal/Content.js
src/components/Modal/index.js
src/components/Modal/tests/Body.test.js
src/components/Modal/tests/Modal.test.js
src/styles/components/Modal/Modal.scss
src/styles/components/Modal/ModalBody.scss
stories/Modal.js

This update adds the `positionCloseNode` method from Modal as context,
which allows the `Modal.Body` sub-component to call it on mount.
Typically, this should happen by default. However, there may be cases
where `Modal.Body` gets injected asynchronously (like transitioning from
loading -> loaded states).
This all fires behind the scenes. No changes are required for users of Modal
:smile:

Modal: Allow reposition CloseButton in sub components

---

src/components/Input/index.js
src/components/Input/tests/Input.test.js

When the input is initialized, the value property of its state is set to the passed value prop. The value prop on the internal state is then only updated via the `handleOnChange`. This is fine when the user is in control of the input. There may be times however, where we want to update the value on the internal state programatically, such as allowing a picker to inject content, as shown below. 
This PR updates the Input component such that the value on the internal state can be updated by passing a new value prop to the component.

Allow input state to be updated by passing new value prop

---

src/components/Drop/tests/Drop.test.js
src/components/Modal/tests/Modal.test.js
src/components/PortalWrapper/index.js
src/components/PortalWrapper/tests/PortalWrapper.test.js
test/acceptance/components/Modal.spec.js
test/acceptance/test-helpers.js

This update fixes PortalWrapper to open/close the composed component
(Modal, Drop) with an isOpen prop change.
Jest tests were added for PortalWrapper, Modal and Drop. Karma tests were
also added for Modal.
Resolves: https://github.com/helpscout/blue/issues/164

Modal: Can open/close with isOpen prop change

---

scripts/test.js
src/components/Collapsible/tests/Collapsible.test.js
src/components/Modal/docs/Footer.md
src/components/Modal/docs/Header.md
src/components/Modal/docs/Modal.md
src/components/Modal/index.js
src/components/Modal/tests/Modal.test.js
test/acceptance/components/Modal.spec.js

This update adds a new prop to `Modal`, which provides a delayed time before
the CloseButton is repositiioned (if the CloseButton is enabled).
This is necessary for certain situations where content that's injected into
the `Modal.Body` changes size, from a no-scrollbar state to a scrollbar state.
An example would be media (like images) unfurling during the mount state,
which is hidden via the Animation transition.
This is very edge-case, but it's something that I saw during Beacon
integration.

Modal: Provide delay for CloseButton reposition

---

src/components/Card/docs/Card.md
src/components/Card/index.js
src/components/Card/tests/Card.test.js
src/components/Heading/README.md
src/components/Heading/index.js
src/components/Heading/tests/Heading.test.js
src/components/Text/README.md
src/components/Text/index.js
src/components/Text/tests/Text.test.js
src/styles/components/Card/Card.scss
src/styles/components/Heading.scss
src/styles/components/Link.scss
src/styles/components/Text.scss
src/styles/mixins/linkStyles.scss

This update adds a new prop to the Card component allowing it to have
full height styles (`height: 100%`). This is useful for when the Card
is contained within a flex-based element, and you require the Card
to expand the entire height of the parent element.
This update updates the Text and Heading components with 2 new props:
`linkStyle` and `center`. This props apply CSS styles that make the
text look like Links and center-align text (respectively).

Card: Add fullHeight styles

---

package.json
src/index.js
src/utilities/index.js
src/utilities/tests/index.test.js

This update exposes all of Blue's utils, making them available to be
imported and used.
All of the utilities come bundled within a `utilities` object.
**Example**
```
import { smoothScroll } from '@helpscout/blue/utilities'
// Now you can do things with smoothScroll.smoothScrollTo()!
```
Alternatively, you can do this (which might not be recommended, as it imports all the utils):
```js
import { utilities } from '@helpscout/blue'
const {
smoothScroll
} = utilities
// Now you can do things with smoothScroll.smoothScrollTo()!
```

Utilities: Expose all of Blue's utils

---

src/components/Card/index.js
src/components/Card/tests/Card.test.js

This update resolves the issue with `Card` when passing in the `autoWordWrap`
prop for non-Link use. Previously, it would pass the prop into a `div`
selector, resulting in a warning.
Tests have been added for this update! :tada:

Card: Fix autoWordWrap prop use for non-Links

---

src/components/Avatar/index.js
src/components/AvatarStack/README.md
src/components/AvatarStack/index.js
src/components/AvatarStack/tests/AvatarStack.test.js
src/styles/components/Avatar.scss

(Screenshot from Sketch)
This update adjusts the `md` sizing for the Avatars to match the
pattern library (created by @digitaldesigner). The Avatar components have also been provided with a default
`size` prop of `md`.
Lastly, `AvatarStack` has been enhanced with a new prop, `avatarClassName`.
This allows you to pass in a custom className to the child Avatars.

Avatar: Adjust sizing

---

src/components/Animate/index.js
src/components/Portal/index.js
src/components/PortalWrapper/index.js

This update provides a slight performance enhancement to the Portal component
by making it extend `PureComponent` instead of `Component` from React.
This prevents some re-renders during the `shouldComponentUpdate` diff'ing
during the render cycle.

Portal: Performance

---

src/components/Icon/README.md
src/components/Icon/index.js
src/components/Icon/tests/Icon.test.js
src/components/Text/README.md
src/components/Text/index.js
src/components/Text/tests/Text.test.js
src/constants/propTypes.js
src/styles/components/Icon.scss
src/styles/components/Text.scss
src/styles/configs/_color.scss
stories/Icon.js

This update adds a new 'extraMuted' shade to both the `Text` and `Icon`
components. This is done via a new `shade` prop, which accepts an
string value of pre-defined shades.
Tests + Storybook (Icon) have been updated :D

Colors: Add ExtraMuted

---

src/components/Avatar/index.js
src/components/Avatar/tests/Avatar.test.js
stories/Avatar/index.js

This PR introduces a new Avatar feature whereby if the image fails to load, the Avatar will fallback to rendering the initials.
This feature makes use of the HTMLImageElement `onError` callback to detect errors and update the `imageLoaded` property on the component's state. This causes the component to re-render with the initials instead of the image.
Because we cannot programmatically detect errors on background images, we use a hidden image element to detect and act on errors.

Avatar Feature: Fallback to initials on image error

---

src/components/Avatar/index.js
src/components/Avatar/tests/Avatar.test.js

Currently, the Avatar component has a background color even when an image is used instead of initials. This results a flash of color before the image loads that is particularly pronounced when the image is not cached in the browser.
This PR introduces a change to use a transparent background when an image is used. The effect of this change is that the space for the avatar is rendered when waiting for an image to load with a transparent background, making for a more seamless loading effect.
Note that in the render function we are building up a style object and that object is reassigned to null if no styles are added. This is to make it easier for testing to simply verify that styles are falsy.

Apply transparent background when Avatar has image

---

src/components/Illo/propTypes.js

This was missing from the previous Illo update.

Illo: Add '72' prop for size

---

src/components/Modal/docs/Modal.md
src/components/Modal/index.js
src/components/Modal/tests/Modal.test.js

This update enhances the `Modal` component with 2 new props:
* `cardClassName`
* `overlayClassName`
This allow you to provide the child `Card` and `Overlay` components
with custom classNames.
Docs and tests have been updated :rocket:

Modal: Add additional classNames

---

src/components/Button/index.js
src/components/Button/tests/Button.test.js
src/components/Select/README.md
src/components/Select/index.js
src/components/Select/tests/Select.test.js
src/styles/components/Button.scss
src/styles/components/Input/Input.scss
src/styles/components/Input/InputField.scss
src/styles/components/Select/Select.scss
src/styles/components/Select/SelectIcon.scss
src/styles/configs/_seed-control.scss
src/styles/mixins/backdrop-styles.scss
src/styles/themes/hs-app/components/Button.scss
src/styles/themes/hs-app/components/__index.scss

This update adjusts the font-size, weight, and size for the Buttons.
This is all done via CSS, mainly Seed's `seed-button` pack's SCSS configs.
Adjustments have also been made for the Input and Select components.
Stateful control borders also receive a 1px bump in size. A new focus style has been added to accommodate the size change.

Controls: Adjust styles for Button, Input and Select

---

src/components/Input/README.md
src/components/Input/index.js
src/components/Input/tests/Input.test.js
src/components/Modal/index.js
src/components/Modal/tests/Modal.test.js
src/components/Select/README.md
src/components/Select/index.js
src/components/Select/tests/Select.test.js
stories/Input.js

This update enhances the Input and Select components with the ability to remove
state-based styles onFocus. The default value for this prop is set
to `false`.
This update also fixes how these prop-based classNames are rendered into the child components.

Input/Select: Add ability to removeStateStylesOnFocus

---

src/components/Input/index.js
src/components/Input/tests/Input.test.js
src/components/Select/index.js
src/components/Select/tests/Select.test.js
src/styles/components/Input/Input.scss
src/styles/components/Input/InputGhost.scss
stories/Input.js

This update ensures that "multiline" mode for `Input` has the same
padding as the default "input" mode. This update also fixes a :bug:
where the style prop was being passed to the child input/select,
instead of the parent wrapper.

Controls: Style and multiline

---

src/components/Skeleton/Control.js
src/components/Skeleton/README.md
src/components/Skeleton/docs/Control.md
src/components/Skeleton/index.js
src/components/Skeleton/tests/Control.test.js
src/styles/components/Input/InputField.scss
src/styles/components/Skeleton/SkeletonControl.scss
src/styles/components/Skeleton/__index.scss
stories/Skeleton.js

This update adds a new Skeleton component - `Skeleton.Control`.
This component acts as a placeholder for things like
Dropdowns, Selects, Inputs, and Buttons. It has been
set up with the `size` prop that all of the components
share for their control elements.
This update also fixes the red border issue for `InputField`
elements on Firefox.

Skeleton: Add Control

---

src/components/Animate/README.md
src/components/AnimateGroup/README.md
src/components/AnimateGroup/index.js
src/components/AnimateGroup/tests/AnimateGroup.test.js
src/components/Modal/docs/Modal.md
src/components/Modal/index.js
src/styles/components/Animate/sequences/_fade.scss
src/styles/components/Avatar.scss
stories/AnimateGroup/index.js

This update enhances the AnimateGroup to better pass down props to
Animate, specifically the `sequence` prop. This allows you to more easily
write markup for your AnimateGroup + Animate components.
(Modals feel a lot more snappier + responsive)
Modal's (user) experience has also been greatly improved be adjusting
the delay/duration/timeout props. All of these properties have now
been exposed to the user for custom adjustments, if they so choose.
Lastly, the Avatar component's small size has been bumped up to 30px.

AnimateGroup/Animate enhancements + Avatar size tweak

---

src/components/Select/index.js
src/components/Select/tests/Select.test.js
src/styles/components/Select/Select.scss

This update fixes the Select component to properly render a placeholder
for Firefox. The fix was to include the placeholder text as textNode
for the `<option>` element.
Previously, it was only used as a `label` prop. Chrome/Safari recognized
this, but Firefox did not.
With this update, all 3 browsers recognize the placeholder just fine.

Select: Fix placeholder for Firefox

---

src/components/Modal/index.js
src/components/Modal/tests/Modal.test.js

This update resolves the `modalAnimationEasing` prop in the `Modal`
component to ensure that it gets passed to the appropriate `Animate` component.
Tests has been added for the various modalAnimation props.
Resolves: https://github.com/helpscout/blue/issues/197

Modal: Allow for modalAnimationEasing to be passed

---

src/components/Drop/tests/Drop.test.js
src/components/Dropdown/Menu.js
src/components/Dropdown/tests/Menu.test.js
src/components/Input/README.md
src/components/Input/index.js
src/components/Input/tests/Input.test.js
src/components/PortalWrapper/index.js
src/components/PortalWrapper/tests/PortalWrapper.test.js
src/components/Select/README.md
src/components/Select/index.js
src/components/Select/tests/Select.test.js
stories/Modal.js
test/acceptance/components/Dropdown.spec.js

This update fixes and imporoves PortalWrapper (and Modal/Drop
components indirectly) by changing how the `isOpen` state/prop determines
the PortalWrapper's open state.
This allows for Portal'ed components to **remain open** even if there are
prop/state changes for their composed/children components determined by
a parent component (e.g. a Redux setup).
PortalWrapper has also been enhanced to refocus the trigger node after
closing, if the Trigger node is available.
Lastly, the `timeout` prop (and HOC option) is resolved, allowing for
ComposedComponents to be unmounted in the expected `setTimeout` value.
This update enhances the isFocused prop on Input and Select to be able
to force focus when the isFocused prop is changed to `true`
Tests have been updated to check for this functionality. …

Modal and control enhancements

---

src/components/Button/README.md
src/components/Button/index.js
src/components/Button/tests/Button.test.js
src/styles/components/Button.scss
stories/Button.js

This update provides a new `theme` prop to the Button component that allows
for additional theme styles, starting with `editing`.

Button: Add themes (and adjust styles)

---

src/components/AvatarGrid/index.js
src/components/AvatarGrid/tests/AvatarGrid.test.js
src/components/AvatarList/index.js
src/components/AvatarList/tests/AvatarList.test.js
src/components/AvatarStack/index.js
src/components/AvatarStack/tests/AvatarStack.test.js
stories/AvatarStack/index.js

This update adjusts the `max` limit logic for the group-based components
that contain Avatars.
The `max` now determines the total number of Avatar (circles) to show,
not the total amount of Avatars before the truncated `+n` additional
Avatar bubble.

Avatar: Update max logic for Stack, List and Grid

---

src/utilities/color.js
src/utilities/tests/color/getColorShade.test.js
src/utilities/tests/color/hexToHsl.test.js
src/utilities/tests/color/rgbToHsl.test.js
stories/Color/index.js

This update adds a new `getColorShade` color utility function that returns
whether a color (`hex`) is considered `lightest`, `light`, `dark`, or
`darkest`.
This is done by converting the Hex to RGB to HSL and using **MATH** to
figure things out.

Color: Add getColorShade function

---

src/components/Modal/docs/Modal.md
src/components/Modal/index.js
src/components/Modal/tests/Modal.test.js
src/styles/components/Modal/Modal.scss
src/utilities/focus.js
stories/Modal.js

This update enhances the Modal component to contain tab/shift+tab based
focusing events to focusable nodes within the Modal.
This was done using the same focus util functions as Dropdown.Menu.
The CloseButton is now no longer tab focusable, encouraging the user to
use ESCAPE to close a Modal instead. This also prevents accidentally focus/
enter triggering.
Lastly, the Modal now autofocuses on mount (or at least it tries to). This
will help with keyboard-based user flow.

Modal: Enhance with keyboard Tab focus handling

---

src/styles/components/Sortable/SortableItem.scss
src/styles/components/Sortable/SortableList.scss

This update removes the `will-change` CSS property from the Sortable
components, as it caused unexpected behaviour when integrating with
3rd party dropdowns.

Sortable: Remove will-change

---

src/utilities/color.js
src/utilities/tests/color/getColorShade.test.js
src/utilities/tests/color/optimalTextColor.test.js
stories/Color/index.js

This update adjusts both the `getColorShade` and `optimalTextColor`
util functions to use a different RGB weight to (subjectively) better
results for determining whether the text color should be black or white
(given a color).
The functions have also been enhanced to accept a secondary argument
(object), that allows the user to override the default suggested RGB
values with their own (to fine tune).

Color: Adjust values + provide ability to override

---

src/components/Input/index.js
src/components/Input/tests/Input.test.js
src/components/Select/index.js
src/components/Select/tests/Select.test.js
stories/Select.js

This update removes the state-based stylings of an Input/Select from it's
hintText (HelpText component).
Just a heads up, content passed as `helpText` will **still** receive state-based styles if defined.

Input/Select: Remove state styles from hintText

---

src/components/HelpText/index.js
src/components/HelpText/tests/HelpText.test.js
src/components/Input/README.md
src/components/Input/index.js
src/components/Input/tests/Input.test.js
src/components/Label/index.js
src/components/Label/tests/Label.test.js
src/components/Select/README.md
src/components/Select/index.js
src/components/Select/tests/Select.test.js
src/styles/components/Scrollable.scss
src/utilities/strings.js
src/utilities/tests/strings.test.js
stories/Input.js

This update enhances the `hintText`, `helpText`, and `label` props of
`<Input />` and `<Select />` to accept either strings or React components.
This provides extra flexibility, for cases where you might want to include
things like Icons, or Popovers or Tooltips with your Text.

Input/Select: Allow text props to accept Components

---

src/components/Choice/index.js
src/components/Choice/tests/Choice.test.js
src/components/Choice/tests/ChoiceInput.test.js

This update enhances components created with Choice to pass the
"checked" value (from Checkboxes and Radios) on the `onChange`
prop as a secondary argument.
Thanks to @tompedals for this!
Resolves: https://github.com/helpscout/blue/issues/217

Choice: Pass "checked" value for onChange callback

---

src/components/PortalWrapper/index.js
src/components/PortalWrapper/tests/PortalWrapper.test.js
stories/Modal.js

This update enhances the PortalWrapper HOC to prevent an ESC keypress
from bubbling if the Portal'ed component is open.
This allows for UI like Modals to prioritize their ESC interactions.

PortalWrapper: Prevent ESC keypress from bubbling

---

src/components/Modal/index.js
src/components/PortalWrapper/index.js
src/components/Scrollable/index.js
src/utilities/node.js

This update replaces the previous getScrollbarWidth method (for offset'ing)
with direct node `offsetWidth` vs `scrollWidth` calculations.
Thanks to @Charca for this idea!!!

Improve scrollbar offset detection

---

src/components/ChatTranscript/Item.js
src/components/ChatTranscript/LineItem.js
src/components/ChatTranscript/docs/Item.md
src/components/ChatTranscript/tests/Item.test.js
src/components/ChatTranscript/tests/LineItem.test.js
src/styles/components/ChatTranscript/ChatTranscriptItem.scss
src/styles/components/ChatTranscript/ChatTranscriptLineItem.scss
src/styles/components/ChatTranscript/__index.scss
stories/ChatTranscript/index.js

This update refactors ChatTranscript.Item to better handle `line_item`
types. It now renders an internal sub-component, specific for the `line_item`
UI, ensuring it has a createdAt, with support for a timestamp, available
on hover.
ChatTranscript.Item now also has access to timestamp on hover.
In the future, I plan to replace it with an actual tooltip, when that
gets built.
Resolves: https://github.com/helpscout/blue/issues/222

ChatTranscript: LineItem with timestamp

---

src/components/Input/README.md
src/components/Input/index.js
src/components/Input/tests/Input.test.js
src/styles/components/Input/Input.scss
stories/Input.js

This update enhances the Input component to allow for setting a maxHeight
for it's multiline mode, which prevents it from growing past a certain
height, and also activates a scrollbar when appropriate.

Input: Add maxHeight to constrict height + add scroll

---

src/components/Input/README.md
src/components/Input/index.js
src/components/Input/tests/Input.test.js
src/components/ScrollLock/README.md
src/components/ScrollLock/index.js
src/utilities/browser.js
src/utilities/index.js
stories/Modal.js

This update fixes multiline scrollable Inputs to allow them to scroll
if they are used within a ScrollLock'ed component.
These Input components (actually textareas) have their own Scroll-locking
mechanism.
Lastly, scroll-locking has been disabled for Firefox, due to some strange
interaction issues with FF.

Input: Allow scrolling + implement scroll-lock

---

src/components/Message/Bubble.js
src/components/Message/Chat.js
src/components/Message/ChatBlock.js
src/components/Message/Media.js
src/components/Message/propTypes.js
src/components/Message/tests/Bubble.test.js
src/components/Message/tests/Chat.test.js
src/components/Modal/Body.js
src/components/Modal/docs/Body.md
src/components/Modal/tests/Body.test.js
src/components/Scrollable/README.md
src/components/Scrollable/index.js
src/components/Scrollable/tests/Scrollable.test.js
src/styles/components/Modal/ModalBody.scss
stories/Message.js

This update enhances the `<Message.Chat />` component to be able to render
HTML by passing HTML string into a new `body` prop. In a scenario where
there is both a `body` and `children` prop defined, `body` will render
instead of `children`.
`<Message.Media>` received some light UI adjustments to account for the
new(ish) Modal structure that was introduced. This change touched a bit of
`Modal.Body` as well as `Scrollable`.
Documentation and tests have been added.

Message: Chat: Allow for HTML rendering

---

src/components/Avatar/README.md
src/components/Avatar/index.js
src/components/Avatar/tests/Avatar.test.js
src/styles/components/Avatar.scss
stories/Avatar/index.js

This update enhances the Avatar component by adjusting the styles for
`outerBorderColor` and `borderColor`. It also coordinates the the Avatar's
`StatusDot` size with the Avatar's size.

Avatar: Adjust UI for outerBorderColor

---

src/components/Button/index.js
src/components/Drop/index.js
src/components/Drop/tests/Drop.test.js
src/components/HoverWrapper/index.js
src/components/HoverWrapper/tests/HoverWrapper.test.js
src/components/PortalWrapper/index.js
src/components/PortalWrapper/tests/PortalWrapper.test.js
src/components/RouteWrapper/index.js
src/components/RouteWrapper/tests/RouteWrapper.test.js
src/styles/components/Button.scss
src/styles/configs/_seed-control.scss
stories/Button.js

This update enhances the Button component styles by adding a new `xs` size,
as well as `outline` styles.
The `outline` style uses `currentColor` for it's coloring, which allows the user to
easily adjust it using inline styles or CSS style rules.
This update also provides HOC/Wrapper components with updated `displayName`,
following the convention of `withWrapperComponentName(ComposedComponent)`.

Button: Add XS and Outline styles

---

src/components/Modal/index.js
src/styles/components/Avatar.scss
src/styles/components/Message/Bubble.scss
src/utilities/smoothScroll.js

This update contains 4 fixes:
1. The `smoothScrollTo` util function works again. It was previously
broken due to the ease function being removed during the Animation rework.
2. `Avatar` names are no longer user-selectable
3. `Message.Bubble` has word-wrap support.
4. `Modal` repositions CloseNode (again) after the animation sequence timing

Smoothscroll and other fixes

---

package.json
src/components/Message/Action.js
src/components/Message/Attachment.js
src/components/Message/Bubble.js
src/components/Message/Caption.js
src/components/Message/Chat.js
src/components/Message/ChatBlock.js
src/components/Message/Media.js
src/components/Message/Message.js
src/components/Message/README.md
src/components/Message/docs/Attachment.md
src/components/Message/docs/Caption.md
src/components/Message/docs/Chat.md
src/components/Message/propTypes.js
src/components/Message/tests/Attachment.test.js
src/components/Message/tests/Bubble.test.js
src/components/Message/tests/Caption.test.js
src/components/Message/tests/Chat.test.js
src/components/Message/tests/Media.test.js
src/styles/components/Image.scss
src/styles/components/Message/Bubble.scss
src/styles/components/Message/Media.scss
src/utilities/browser.js
src/utilities/types.js
stories/EmbedChat/index.js
stories/Message.js

This update enhances the `Message.Media` sub-component, as well as adds
a new `Message.Attachment` sub-component.
`Message.Media` had some UI adjustments as well as added flexibility.
You can now choose whether clicking the media image will automatically
open a Modal preview, as well as tap into an `onClick` callback.
`Message.Attachment` was added to better handle file attachments within
a Chat context.
Related Message sub-components, like `Message.Chat`, were adjusted to
faciliate these changes.

Message: Media and Attachments enhancements

---

src/components/ChatTranscript/LineItem.js
src/components/ChatTranscript/tests/LineItem.test.js

ChatTranscript `LineItem` bodies contain HTML. This PR makes the `LineItem` support dangerously-set HTML in the `body`.

Make LineItems support dangerously-set HTML `body`s

---

src/styles/components/Inline/Inline.scss

This update removes the right negative margins from the `Inline` component,
which appeared to be causing issues for certain use-cases.
Thanks to @brettjonesdev for spotting this one!

Inline: Fix right margins

---

src/components/Message/Attachment.js
src/components/Message/tests/Attachment.test.js
src/styles/components/Message/Attachment.scss
src/styles/components/Message/__index.scss
stories/Message/attachment.js

This update enhances the `Message.Attachment` component to render a muted
style if a `url` prop is not provided.

Message:Attachment - No URL styles

---

src/components/Message/Attachment.js
src/components/Message/tests/Attachment.test.js

This update fixes the filename rendering within the `<Message.Attachment>`
component to truncate the text, via the `truncate` prop made available
by an inner `<Text>` component.

Message.Attachment: Truncate filenames

---

src/components/Message/Media.js
src/components/Message/docs/Media.md
src/components/Message/tests/Media.test.js
stories/Message/media.js

This update enhances `Message.Media` to provide an `onLoad` callback when
the internal `<Image>` is loaded.

Message: Media - Provide an `onLoad` callback

---

src/components/Message/Attachment.js
src/components/Message/docs/Attachment.md
src/components/Message/tests/Attachment.test.js

This update enhances the `Message.Attachment` to open download links
in new tabs when clicked. This better handles non-downloadable file types
like `.html` or `.mp4` or `.mp3`.

Message.Attachment: Open downloadable links in new tab

---

src/components/Attachment/docs/Attachment.md
src/components/Attachment/index.js
src/components/Attachment/tests/Attachment.test.js
stories/Attachment/index.js

This update enhances the `<Attachment>` component to automatically fill
the `download` and `target` HTML link attributes if a `url` is provided.
This allows for the attachment to reliably download/open in a new tab.
Download handling is custom for every browser. For Chrome's case, it
favours simply loading the file in a new tab.
To customize the behaviour, you can provide your own `download`,
`target` attributes, which will override the auto-generated ones.
Example:
**Usage**
```jsx
<Attachment link='https://github.com/helpscout/blue/raw/master/images/Blue.png' />
```
**Result**
```html
<a
class="c-Attachment is-link" 
href="https://github.com/helpscout/blue/raw/master/images/Blue.png"
download=""
target="_blank"
>
...
</a>
```
CC'ing @brettjonesdev  :)

Attachment: Download should open in new window

---

src/components/Avatar/index.js
src/components/Avatar/tests/Avatar.test.js

To make the avatar loading experience smoother, avatars images should only be rendered once they are fully loaded.
This PR implements a change such that the `background-image` property is not set on the Avatar until the image has fully loaded. This prevents partially loaded images from rendering in the Avatar. 
New hooks for onLoad and onError have been added so that consumers of the Avatar component can hook into these events for any custom logic.

Only render avatar images that are fully loaded

---

src/components/Avatar/index.js
src/components/Avatar/propTypes.js
src/components/AvatarList/index.js
src/components/ChatInbox/Header.js
src/components/ChatInbox/tests/Header.test.js
src/components/ChatList/BlankSlate.js
src/components/ChatList/Item.js
src/components/List/List.js
src/components/List/docs/List.md
src/components/List/tests/List.test.js
src/styles/components/Avatar.scss
src/styles/components/Badge.scss
src/styles/components/ChatInbox/ChatInbox.scss
src/styles/components/ChatInbox/ChatInboxHeader.scss
src/styles/components/ChatList/ChatList.scss
src/styles/components/ChatList/ChatListBlankSlate.scss
src/styles/components/ChatList/ChatListItem.scss
src/styles/components/List.scss
src/styles/components/Tag.scss
src/styles/components/Toolbar/Toolbar.scss
src/styles/configs/_constants.scss
stories/ChatList/ChatListItemStateExample.js
stories/ChatList/index.js
stories/ChatSidebar/index.js

This update adjusts the visual UI of various components that appear
within the ChatSidebar UI, which includes:
* Avatar
* AvatarList
* Badge
* ChatInbox
* ChatInbox/Header
* ChatList
* ChatList/BlankSlate
* ChatList/Item
* ChatList/Header
* List
* Tag
* Toolbar
Most of these changes are CSS changes. However, there were some minor
JS changes.
The most significant JS changes include the addition of a `xs` prop
for `Avatar` components, which should be used within the context of a
ChatSidebar.
Also, the example story for `ChatList` has been resolved to properly
render the Assigned UI.

ChatSidebar: Visual tweaks

---

src/utilities/strings.js
src/utilities/tests/strings.test.js

We had some bad data turn up in prod, which was causing Agent Chat to throw a JS error and stop working. I haven't been able to fully track down the data, but the error was within the `nameToInitials` util. I could reproduce the error by passing a string with additional whitespace.
Needed for https://github.com/helpscout/hs-app/pull/4885

Guard against invalid values in the nameToInitials strings util

---

src/components/Message/Media.js
src/components/Message/tests/Media.test.js

The Modal component allows a custom class name to be set on the modal's wrapper. This is very useful for integrating Blue components into other user interfaces. 
A consumer of Blue may scope the Blue styles inside a namespace by importing inside a class. For example, `.myScope { @import 'blue.scss' }`. This is useful to allow the styles from Blue to safely be applied inside a region on a page, avoiding potential style conflicts. This breaks down however, for components that use portals since these components end up being rendered outside the intended region and thereby the styles from Blue are not applied. By being able to set a custom wrapper class name on the Modal component (which uses a portal), this issue is alleviated since the component can now render inside the same class name …

Allow customizing class name on modal wrapper

---

src/components/Avatar/index.js
src/components/Avatar/tests/Avatar.test.js

This update fixes the StatusDot size when used within an Avatar. The
size needs to be `md` if the Avatar is set to have a size of `lg`.

Avatar: Fix StatusDot size for lg

---

package-lock.json
package.json

This update bumps Fancy to v0.6.7, which uses `appendChild` vs `append` for
proper IE/Edge support.

Fix: Update Fancy for Edge/IE support

---

package-lock.json
package.json

This update bumps [Fancy to v0.6.8](https://github.com/helpscout/fancy/releases/tag/v0.6.8), which fixes the async render cycles
of components with hashed style names.

Update Fancy to v0.6.8

---

src/components/ChatTranscript/LineItem.js
src/components/ChatTranscript/tests/LineItem.test.js
src/utilities/strings.js
src/utilities/tests/strings.test.js
stories/ChatTranscript/index.js

https://trello.com/c/HBqD6W7A/307-chat-transcript-linebreaks-are-ignored
Adds a new `newlineToHTML` string utility that converts newlines to HTML line breaks. This is used within the chat transcript to convert the newlines in the chat message body.

Add line breaks to content in the chat transcript

---

src/components/AttachmentList/index.js
src/components/AttachmentList/tests/AttachmentList.test.js
src/styles/components/AttachmentList.scss

This update adjusts the AttachmentList to ensure that items that overflow
are wrapped, instead of being contained within an Overflow component.

AttachmentList: Wrap items instead of Overflow

---

src/components/Input/index.js
src/components/Input/tests/Input.test.js

This update improves the scrolling mechanism that attempts to scroll to the
ideal reading position of a multi-line input.
The scrolling mechanism calculates on every character change, but only kicks
in if the textarea line number is the last line number.

Input: Multiline: Improve scroll mechanism

---

package-lock.json
package.json
src/components/Emoticon/index.js
src/components/Emoticon/styles/Emoticon.css.js
src/components/styled/README.md
src/components/styled/__tests__/styled.test.js
src/components/styled/index.js

This update upgrades [Fancy](https://github.com/helpscout/fancy/releases/tag/v1.0.0) to v1, which has support for Theming with a new
styled-component-like API.
Fancy will be used throughout Blue via a `styled` adapter for added
flexibility.
Integration tests have been added to ensure basic functionality.
At the moment, Fancy is only being used for the Emoticon component. Here's
a screenshot of it rendering on Microsoft Edge.

Update to Fancy v1.0

---

package-lock.json
package.json

This update bumps Fancy to v1.0.5, which includes minor bug fixes, but more
importantly, a consumable build for friendly Webpack (uglify) bundling.

Fancy: Update build

---

src/components/Tooltip/styles/TooltipPopper.css.js
stories/Tooltip.js

This update adds word-wrapping for Tooltip content.

Tooltip: Word-wrap

---

src/components/Overflow/__tests__/Overflow.test.js

This update removes the setTimeout to check if the adjustHeight method
is fired on Mount.

Tests: Overflow - Improve reliability of test

---

src/components/Timestamp/Time.js
src/components/Timestamp/index.js
src/components/Timestamp/tests/Timestamp.test.js
src/utilities/tests/timestamp.test.js
src/utilities/timestamp.js
stories/Timestamp.js

I needed a live updating `time` element that wasn't wrapped in the usual way that `Timestamp` does. It needed to be inline and inherit the styles from the container. To achieve this I split out the logic for the live updating timestamp into a `Time` component that could be used independently of `Timestamp` as `Timestamp.Time`.
The `calculateTimeoutPeriod` function is used to determine the interval to use for updating the live timestamp. When the difference is more than one minute we only updated every minute. This was causing some display issues when we had multiple components that were rendered at different times. One might say "3 min ago" and the other "4 min ago" as the intervals are out of sync. To alleviate some of this I updated the interval to be every 15 seconds rather than every …

Split Time component from Timestamp to allow just rendering time without wrapper

---

src/components/Overflow/__tests__/Overflow.test.js
src/components/Overflow/index.js

This update improves the stability of the `Overflow` component to only check
and adjustHeights if the component is mounted.
There issues that occurred when the `adjustHeight` method was firing
(and failing) if the components get detached.
Thanks @knicklabs for spotting this!

Overflow: Improve stability

---

src/components/Input/README.md
src/components/Input/__tests__/Input.test.js
src/components/Input/index.js
stories/Input.js

This update changes the naming of refApplySubmit to the much more accurate name refApplyCallStopTyping.

Change refApplySubmit to refApplyCallStopTyping

---

src/components/Input/index.js

This update fixes `onStopTyping` on inputs which should only be called if there is a `timeout` set.

Fixes onStopTyping so it doesn't fire if there is no timeout

---

src/components/Modal/tests/Modal.test.js
src/components/Portal/index.js
src/components/Portal/tests/Portal.test.js
src/components/PortalWrapper/tests/PortalWrapper.test.js

This update refactors some of the tests to use `jest.useFakeTimeout` instead
of real time outs.

Test: Refactor tests to use jest.useFakeTimeout

---

package-lock.json
package.json
src/components/Dropdown/__tests__/Menu.test.js

This update bumps Fancy to the latest v2.0.2, which uses a better
babel transpilation for `dist` build.

Fancy: Update babel build

---

src/components/Message/ChatBlock.js
src/components/Message/Content.js
src/components/Message/Media.js
src/components/Message/Message.js
src/components/Message/__tests__/Content.test.js
src/components/Message/__tests__/Message.test.js
src/components/Message/docs/Content.md
src/components/Message/docs/Message.md
src/components/Message/styles/Content.css.js
src/components/Message/styles/Media.css.js
src/components/Message/types.js
src/components/PreviewCard/Context.js
src/components/PreviewCard/__tests__/PreviewCard.test.js
src/components/PreviewCard/index.js
src/components/PreviewCard/styles/PreviewCard.css.js
src/styles/components/Message/Content.scss
src/styles/components/PreviewCard.scss
src/styles/mixins/noteStyles.css.js
stories/Message/index.js

This update enhances the `Message.Content` component to add `isNote` theme
support.
This is done by leveraging the (polyfilled) React 16 `context` API, which sets
up a Provider/Consumer relationship between the `Message` component and the
`Card` component that renders within.
The activation of the note theme happens internally.
CSS has been refactored for the `PreviewCard` and `Message.Content` to use
Fancy instead of SCSS.
Lastly, the main `Message` component was converted from a SFC to a React.Class
component for a performance/stability boost.

Message.Content: Note theme

---

src/components/Message/Action.js

This resolve the React warning for `isNote` rendering for `Message.Action`.

Message.Note: Fix isNote prop for rendering

---

src/components/AvatarGrid/README.md
src/components/AvatarGrid/__tests__/AvatarGrid.test.js
src/components/AvatarGrid/index.js
src/components/AvatarGrid/styles/AvatarGrid.css.js
src/components/AvatarGrid/styles/AvatarGridContainer.css.js
src/components/AvatarGrid/styles/AvatarGridWrapper.css.js
src/styles/components/AvatarGrid.scss
stories/AvatarGrid/index.js

This update fixes the (re)rendering issues for AvatarGrid, caused by
`AnimateGroup`. The `AnimateGroup` component works correctly. However, the
combination of it within the `AvatarGrid` UI may not be ideal.
The CSS styles for `AvatarGrid` now live in Fancy CSS-in-JS, and the original
SCSS removed.
Lastly, tests and the README doc were updated to reflect the changes.
---
Notes on other changes!
I've also started replacing `shallow` with `mount`. [Mount testing is much better](https://blog.kentcdodds.com/why-i-never-use-shallow-rendering-c08851a68bb7) at catching render bugs. It's only a teeny tiny bit slower... maybe by a couple of `ms`. Worth it.

AvatarGrid: Remove animation

---

src/components/Input/README.md
src/components/Input/__tests__/Input.test.js
src/components/Input/index.js

This PR adds a `throttler` for the `onStartTyping` callback and a `typingThrottleInterval` prop (so we can rate limit the frequency at which it is fired).

Add a throttler to throttle startTyping events

---

src/components/Animate/README.md
src/components/Heading/styles/Heading.css.js
src/components/Icon/README.md
src/components/Icon/index.js
src/components/Icon/styles/Icon.css.js
src/components/Input/README.md
src/components/Input/__tests__/Input.test.js
src/components/Input/__tests__/Resizer.test.js
src/components/Input/__tests__/Static.test.js
src/components/Input/index.js
src/components/Pop/Popper.js
src/components/Pop/Reference.js
src/components/Pop/index.js
src/components/Pop/styles/Pop.css.js
src/components/Pop/styles/PopArrow.css.js
src/components/Select/README.md
src/components/Select/index.js
src/components/Select/tests/Select.test.js
src/components/Select/types.js
src/components/Tooltip/index.js
src/components/Truncate/index.js
src/components/Truncate/styles/Truncate.css.js
src/constants/index.js
src/styles/components/Select/SelectIcon.scss
src/styles/mixins/input-styles.scss
stories/Input.js
stories/Select.js

This update enhances the `Input` and `Select` components with error icon
rendering. If these components have a `state` (prop) of `error`, they will
automatically add an error `Icon` at the end.
These error `Icon` have the ability to render a `Tooltip` message, if
the prop `errorMessage` is provided.
The `Select` component was refactored with Flow (yay).
(Select + error)
For this update, I held off refactoring the CSS of `Input` and `Select`
with Fancy (for now).
Other updates include swapping `shallow` for `mount` rendering in tests,
updating tests, and improving `Truncate`/`Tooltip`/`Pop` rendering.

Input/Select: Add error icon support

---

src/components/Pop/styles/Pop.css.js
src/components/Pop/styles/PopArrow.css.js
src/components/Tooltip/styles/Tooltip.css.js
src/components/Tooltip/styles/TooltipPopper.css.js
src/components/Truncate/__tests__/Truncate.test.js
src/components/Truncate/index.js
src/components/Truncate/propTypes.js
src/components/Truncate/styles/Truncate.css.js
stories/Truncate.js

(GIF: Demonstrates truncation triggering a tooltip to display - But only when truncation occurs)
This update improves the truncation calculation for the `Truncate` component.
This is achieved by normalizing the necessary DOM elements to grab the
width variables for MATH'ing. These DOM elements are then reset to their
neutral states, is if nothing happened ;).
`Tooltip`/`Pop` components were also improved to be made less "opinionated"
regarding CSS font-size rendering.

Truncate: Improve calculation reliability

---

README.md
package-lock.json
src/components/Select/index.js
src/styles/configs/constants.js
src/styles/resets/font.css.js
src/styles/resets/fontFamily.css.js
src/styles/utilities/variableFontSize.js

This update adds the font-family fallback for the global Blue CSS
variable. This helps ensure that a font family is, at the very least,
defined, if the variable is somehow not available.
`package-lock.json` was rebuilt using `npm 5.6.0`.

CSS: Add font family fallbacks for variables

---

src/components/Animate/styles/Animate.css.js

This update removes the `visibility` CSS prop from the `Animate` lifecycle
styles. After some investigating/testing, I've noticed that this is somehow
causing render issues in iOS Safari (for certain render cases).
Example:
Elements would stay invisible, unless a repaint/re-render is forced.
By removing this CSS prop, we avoid potential visibility render issues
all together!

Animate: Improve rendering for Safari (iOS)

---

src/components/Message/Embed.js
src/components/Message/Message.js
src/components/Message/README.md
src/components/Message/__tests__/Embed.test.js
src/components/Message/docs/Embed.md
src/components/Message/styles/Embed.css.js
stories/Message/embed.js
stories/Message/index.js

This update adds a new `Message.Embed` component to Blue. It accepts an `html` prop and renders the HTML inside the component with style treatments similar to `Message.Media`. Unlike `Message.Media`, it does not open the content in a modal.

Message: Support Embedded HTML Content

---

src/components/Message/styles/Chat.css.js
stories/Message/index.js

This update fixes the border-radius rendering for Chat Bubbles, when
used within a Scope.
The issue was the `&` was inheriting the full scope style path.

Message: Fix Bubble border-radius

---

src/components/Modal/index.js
src/components/Modal/tests/Modal.test.js

This PR removes the `tabindex` attribute from modal close buttons. This fixes some 'focus tab' issues where the user can't tab to the close button.
more info: https://trello.com/c/CsX0PDSX/552-accessibility-issues-tabbing-escing-highlighting-within-embed

Remove tabindex on close button for modals

---

src/components/Image/__tests__/Image.test.js
src/utilities/images.js
stories/Image.js

**[Trello Card](https://trello.com/c/F42QuDSu)**
When the Image component is provided with a maxWidth and maxHeight, we would calculate an aspect ratio for the image that would fit within those bounds. This would create values that we could multiple the width and height by to get new widths and heights. The problem was in doing this when the width and height were less than the maxWidth and maxHeight. In such a case we would multiple the width and height resulting in larger numbers. In these cases, we should not apply a multiplier, setting the width and height to their original values.

Do not enlarge images

---

src/components/Switch/README.md
src/components/Switch/Switch.js
src/components/Switch/__tests__/Switch.test.js
src/components/Switch/styles/Switch.css.js
stories/Switch.js

Above: Example shows the loading state, which is resolved after 1 second. The parent component is handling the state switching for the `Switch`.
This update adds a new "loading" state for the `Switch`. The loading state
can be triggered by passing `isLoading` = `true` as a prop. The UI adjusts
to a loading animation. During this state, clicks/changes are blocked, until
`isLoading` is set back to false.

Switch: Add loading state

---

src/components/Switch/Switch.js
src/components/Switch/__tests__/Switch.test.js
stories/Switch.js

This update fixes the `onChange` regression that was introduced with the
new ["loading" state](https://github.com/helpscout/blue/pull/341) for the `Switch`.
This does not change the Component API for implementing the `Switch` loading state. It should still be written like:
```jsx
<Switch
value="on"
checked={this.state.checked}
isLoading={this.state.isLoading}
onChange={this.handleOnChange}
onClick={this.handleOnClick}
/>
```
`onClick` will trigger the action to determined if the `Switch` should be checked or not, which should be updated in the parent component `state`.
Once that is done, it'll then get passed into `Switch` as `checked`.
Once that changes, the `onChange` callback action will be called.

Switch: Fix `onChange`/`onClick` callbacks

---

src/components/Switch/Switch.js
src/components/Switch/__tests__/Switch.test.js
src/components/Switch/styles/Switch.css.js
stories/Switch.js

Within Beacon Builder we have a number of switches that are sometimes in a disabled state. This functions as expected, however it's not visually clear that the switch is disabled. We have had a number of false bug reports due to this.
This change adds some styling for the disabled state. I have attempted to make the switches slightly opaque when disabled to differentiate to the enabled switches. It doesn't quite look right to me, but code wise it's working.
@digitaldesigner Do you have any input on this? I couldn't see this state in the designs https://github.com/helpscout/library-hsapp/wiki/Example:-Settings-Refresh

Add styles for disabled state on the Switch component

---

src/components/Switch/README.md
src/components/Switch/Switch.js
src/components/Switch/__tests__/Switch.test.js
stories/Switch.js

This update modifies `Switch` to return a more intuitive callback value
that represents the next switch state (after engagement).
Additionally, the `onChange` event and value are provided as a second
argument, wrapped within an object.
Minor bump for this update!

Switch: Update onChange callback values

---

package-lock.json
package.json
src/components/Avatar/README.md
src/components/AvatarGrid/AvatarGrid.js
src/components/AvatarGrid/README.md
src/components/AvatarGrid/__tests__/AvatarGrid.test.js
src/components/AvatarList/AvatarList.js
src/components/AvatarList/README.md
src/components/AvatarList/__tests__/AvatarList.test.js
src/components/AvatarStack/AvatarStack.js
src/components/AvatarStack/README.md
src/components/AvatarStack/__tests__/AvatarStack.test.js
stories/AvatarGrid/index.js

This update adjusts `AvatarGrid`, `AvatarList`, and `AvatarStack` to
pass down various props to children `Avatar` components (`borderColor`,
`outerBorderColor`, and `showStatusBorderColor`)
This enables these parent wrapper components to leverage the newly adjusted
component API of `Avatar`.
Test and README have been updated
Follow up for https://github.com/helpscout/blue/pull/356

Avatar group component fixes

---

src/components/CopyCode/CopyCode.js
src/components/CopyCode/README.md
src/components/Highlight/Highlight.js

When unmounting the Highlight component the `ref` was being set to null, but this was not guarded against so it was attempting to highlight the `null` element. This change prevents the error by checking element is not `null` before calling `highlightBlock`.

Only call highlightBlock if the ref element is not null

---

src/components/Message/Embed.js
src/components/Message/__tests__/Embed.test.js
src/components/Message/styles/Embed.css.js

This update adds a loading indicator to the Message.Embed component. It works by checking if there is an iframe inside the HTML embed code and if there is, it attaches an onload event that is used to clear the loading indicator. If there is no iframe, the loading indicator is immediately cleared.

Add loading indicator to Message.Embed

---

src/components/Accordion/Title.js
src/components/Accordion/styles/Accordion.css.js
src/components/Collapsible/index.js
stories/Accordion/index.js

This PR makes some updates to the accordion component. It includes adjustments to the padding of the Accordion.Title and Accordion.Body components to tighten it up a little bit.
It also includes a fix for an issue where you would open an Accordion.Section containing a form and then tab into next Accordion.Section and open it resulting in the previous Accordion.Section being closed and then tabbing back to the previous Accordion.Section. On tabbing back, it would tab into the hidden form forcing the user to hit shift+tab several times to return the previous Accordion.Section.
This PR includes a change to the Collapsible component to add a `is-closed` class. This class is used by the Accordion to hide the contents of the Accordion.Body when the Accordion is closed. This prevents the above …

Accordion Updates

---

.vscode/settings.json

This PR makes Blue more <img src="https://github.com/helpscout/blue/raw/master/images/Blue.png" height="14px" />.
This PR updates the VSCode Workspace settings to include a customization for the titleBar colour.
Before:
After:

Make Blue More Blue

---

src/components/Input/Input.js
src/components/Input/__tests__/Input.test.js
stories/Input.js

GIF demo's the bottom 30px padding is preserved on Enter press.
This update improves the Input scrollToBottom handling in `multiline` mode.
The scrolling mechanism now factors `padding-bottom` when pressing `enter`
for new line.
By default, the browser does **not** do this. Padding values are not
taken into consideration with `textarea` or `contentEditable` elements
autoscroll when paging (up/down/enter).
Note: This update doesn't add support for arrow/mid-content overflow paging.
I tried. It was wayy too difficult.
I had something kinda working, but it wasn't reliable.

Input: ScrollToBottom to account for padding

---

src/components/Button/ButtonV2.js
src/components/Button/__tests__/ButtonV2.test.js
src/components/Button/docs/ButtonV2.md
src/components/Button/index.js
src/components/Button/styles/Button.css.js
stories/Button/ButtonV2.js

This update updates Button V2 to allow for events (like clicks) to child
components to pass through to the primary `Button` component.
This is enabled by a new prop, `allowContentEventPropogation`, which is
`true` by default.
Buttons should allow for their `onClick` (or whatever events) to happen, regardless of where you click within the button itself.

Button V2: Allow content events to pass through

---

package-lock.json
package.json
src/components/Input/Input.js
src/components/Input/__tests__/Input.test.js

This update adjusts the scrollToBottom requirements for Input. The
ENTER keypress requirement was recently added for extra safety. However,
it appears that this broke an implementation where `scrollToBottom` was
manually called.

Input: Remove key press event for scrollToBottom

---

package-lock.json
package.json
stories/Fancy/FrameProvider.js

(GIF: Shows the correct CSS rendering within an unmounting/mounting iFrame within IE11)
This update bumps Fancy to the latest version which fixes an iFrame
rendering issue for Edge/IE. This occurs when the iFrame is unmounted/destroyed.
Note: It still throws an error in IE11, however, the styles work 👍 	. No errors in Edge.
Update in [Fancy 2.1.2](https://github.com/helpscout/fancy/releases/tag/v2.1.2)

Fancy: Fix iFrame rendering for Edge/iFrame

---

src/components/Modal/styles/Body.css.js

On IE11, a modal is not adjusting his height based on the content. I think it's becaused of the shorthand version of `flex: 1`. IE10-11 are interpolating that value the wrong way
Setting it to `flex: 1 1 auto` fixed the issue I was having
There are other places in Blue that used the same shorthand flex property. I didn't want to go in there and change everything without causing unknown side effects

Fix modal body to adapt height based on content, on IE11

---

package-lock.json
src/components/FormLabel/FormLabel.tsx
src/components/FormLabel/README.md
src/components/FormLabel/__tests__/FormLabel.test.js
src/components/FormLabel/styles/FormLabel.css.ts
stories/FormLabel.stories.js
stories/Page/Page.Card.stories.js

This PR proposes the addition of an "inline" mode on `FormLabel`, where the label (including help text) sits on the right and the content on the left. This is specially designed for when the content is a checkbox or a `<Switch>` as most recent designs lays them out.
The alignment of items is done using flexbox
This PR:
- Adds the prop `inline` to enable this mode
- Adds tests
- Adds stories
```jsx
<FormLabel
label="This is the label for the Input down there"
helpText="Ignore this message, says nothing interesting."
>
<Input />
</FormLabel>
```
```jsx
<FormLabel
label="Label for the Switch"
inline
>
<Switch />
</FormLabel>
```
```jsx
<FormLabel
label="Label for the Switch"
helpText="Enable this feature or you might regret it later."
inline
>
<Switch />
</FormLabel>
```
```jsx
<FormLabel …
```

FormLabel: Adds a new mode (inline)

---

src/components/Choice/Choice.js
src/components/Choice/__tests__/Choice.test.js

In a PR for Beacon Builder @ItsJonQ suggested making the help text part of the label so it's clickable when using the stacked style: https://github.com/helpscout/hs-app/pull/5934#issuecomment-442864744
This PR moves the help text inside the label only when it is stacked.

Move help text inside the label when Choice is stacked

---

src/components/HelpText/HelpText.js
src/components/HelpText/__tests__/HelpText.test.js
src/components/HelpText/styles/HelpText.css.js
stories/HelpText.stories.tsx

The `state` prop of `HelpText` was not being respected and it was always using the `faint` text style. This PR moves the state styling to the child `Text` component rather than adding styles to the `HelpText` component as they were are not specific enough.
I added a story to test these changes.

Fix HelpText state and add stories

---

package-lock.json
package.json
src/components/ChatSidebar/ChatSidebar.js
src/utilities/__tests__/pluralize.test.ts
src/utilities/pluralize.ts

This update removes the `pluralize` dependency. Instead, we're gonna use
our own super tiny (but kinda naive) way of pluralizing. This should be okay
since we're currently only using it for one label in the library.

Remove pluralize dependency

---

src/components/Modal/Modal.js
stories/Modal.stories.js

This update fixes a lil' bug with `Modal` where `style` and `className` props were being unexpectedly passed to inner components.

Modal: Prevent className/style prop pass

---

package-lock.json
package.json
src/components/Input/Input.js
src/utilities/__tests__/is.test.js
src/utilities/component.ts
src/utilities/is.ts

This update adds a guard for `Input` during the height check phase. It also refactors `utilities/is` to work better with Typescript.

Input + Is

---

.remake/component/remake-name/remake-name.tsx
src/components/ChatScroller/ChatScroller.tsx
src/components/ChatScroller/ChatScroller.utils.ts
src/components/ChatScroller/README.md
src/components/ChatScroller/__tests__/ChatScroller.test.js
src/components/ChatScroller/index.ts
src/utilities/smoothScroll.js
stories/ChatScroller.stories.js
tsconfig.json

(GIF: Demo of `ChatScroller` controlling a parent scrollable node)
This update enhances `ChatScroller` to be able to control scrollable
nodes that may exist as parent nodes (instead of child only).
`ChatScroller` has also been refactored with the latest HSDS conventions,
including `propConnect` and Typescript.

ChatScroller: Enable external selector

---

src/styles/components/Button.scss

This updates the styles for the `Button` component `pill` theme.

Refactor styles for Button pill theme

---

src/components/PropProvider/__tests__/propConnect.test.js
src/components/PropProvider/docs/propConnect.md
src/components/PropProvider/propConnect.tsx

This update adds a new `wrappedRef` prop to `propConnect`, which allows for consumers
to retrieve the original component instance of a connected component.
🍐 'ed on this with @knicklabs !

propConnect: Add wrappedRef

---

src/components/ChatScroller/ChatScroller.tsx
src/components/ChatScroller/README.md
src/components/ChatScroller/__tests__/ChatScroller.test.js

This update fixes ChatScroller to ensure that it references the correct scrollable
node.

ChatScroller: Fix reference for scrollableNode

---

src/components/ChatScroller/ChatScroller.tsx
stories/ChatScroller.stories.js

This update re-adds the ability for ChatScroller to reference a DOM element
that may exist outside of it's contents.
The order of operations flows like:
1. Specified DOM Node (via `scrollableNode`)
2. Child `scrollableSelector` query
3. Document `scrollableSelector` query
Note: Document is iFrame friendly as it references the `document` containing
`ChatScroller` rather than assuming `window.document`.

ChatScroller: Re-add ability to target an outer selector

---

package-lock.json
package.json
src/components/ChatScroller/ChatScroller.tsx
src/components/ChatScroller/README.md
src/components/ChatScroller/__tests__/ChatScroller.test.js

This update resolves the issue where ChatScroller failed to determine the
`document` from the internal `childRef`.
An enhancement was also made that adds a new `forceScrollToBottomProp` prop
which, when changed, forces `ChatScroller` to scroll to the very bottom.

ChatScroller: Fix scrollableSelector for iFrames + add force prop

---

package-lock.json
package.json

This update version bumps Fancy + React Utils to their latest versions.
These updates improve support for React 16.3+ in retrieving the closest
`document` for DOM node referencing and targeting.

Update Fancy + React Utils

---

src/components/Input/styles/Input.css.js

This update fixes the (right) margin for error icons that appear within
`Input` and `Select` components.
The issue came from a typo where the style selector was `is-prefix`, but
needed to be `is-suffix`.

Input: Reduce suffix error icon margin

---

package-lock.json
package.json
src/components/Select/Select.css.ts

This update adjusts the alignment of the "error" icon that appears
on the right of a `Select` component. The adjustment was to reduce the
right margin, to ensure that it lines up correctly next to `Input` components
in error states.

Select: Adjust error icon alignment

---

package-lock.json
package.json
src/components/ChatScroller/ChatScroller.tsx
src/components/ChatScroller/__tests__/ChatScroller.test.js

This update allows for `ChatScroller` to reset it's target DOM node when
either the `scrollableNode` or `scrollableSelector` props are updated.
Previously, the method to set the DOM node only ran during initialization.
With this update, `ChatScroller` is now able to observe different nodes
during it's lifecycle, depending on the implementation.

ChatScroller: Reset Nodes

---

package-lock.json
package.json
src/components/Dropdown/V2/Dropdown.Trigger.tsx
src/components/Dropdown/V2/Dropdown.store.js
src/components/Dropdown/V2/Dropdown.types.ts
src/components/Dropdown/V2/docs/Dropdown.md
src/components/SelectDropdown/README.md
src/components/SelectDropdown/SelectDropdown.css.ts
src/components/SelectDropdown/SelectDropdown.tsx
src/components/SelectDropdown/__tests__/SelectDropdown.test.tsx
src/utilities/__tests__/arrays.test.js
src/utilities/arrays.ts
stories/SelectDropdown.stories.js

This update improves the `SelectDropdown` to be able to accept a
`value` prop. This adds API parity with `Select` as well as the
native HTML select.
`value` will be used to find the actual item from the original `items` prop.
Both `selectedItem` and `value` is supported for `SelectDropdown`.
An enhancement was made to `Dropdown` to add a new `triggerStyle` prop,
allowing you to specify inline styles for the Trigger wrapper
component.
This update has been E2E tested in the main application.

SelectDropdown: Add support for value

---

src/components/Input/Resizer.tsx
src/components/Input/__tests__/Resizer.test.js

This update enhanced `Input.Resizer` to recalculate it's height on mount behind
a `requestAnimationFrame` call. This is to help ensure correct height values when
loaded into a heavier page/component (computation wise).
`Input.Resizer` has also been converted to Typescript, with minor performance/render
refactors for how it handles defining instance variables.

Input: Resizer - Recalculate height on mount

---

package-lock.json
package.json
src/components/Input/styles/Input.css.js
src/components/Select/Select.css.ts

(GIF shows Firefox rendering for Select and Input)
This update resolves the cursor rendering issue for Firefox. The select
border styles were accidentally added for `Input`. It has now been moved
to target just `Select` fields.

Input/Select: Firefox text/selection fixes

---

src/components/Accordion/Accordion.js
src/components/Accordion/Section.js
src/components/Accordion/__tests__/Accordion.test.js
src/components/Accordion/__tests__/Section.test.js
src/components/Accordion/docs/Accordion.md
src/components/Accordion/docs/Section.md
src/components/Accordion/types.js
stories/Accordion.stories.js

This update adds support for programatically controlling the sections of an Accordion. The sections can be open and closed by setting/updating the `openSectionIds` property on the `Accordion` component. For each id in the array, the corresponding section will be open. All others, will be closed. 
To achieve this, the `Section` component needed to be updated to allow the library user to set an `id` which supersedes the `uuid` generated by the `Section`. Should an id be provided, that id will be used to track the open/closed state of `Section` in the `Accordion`.
This feature supports programmatically opening open or more Sections at a time. 
Below is an example of one Section being controlled at a time.
Below is an example of multiple Sections being controlled at a time.

Enable Programmatic Control of Accordion Sections

---

src/components/Toolbar/Block.js
src/components/Toolbar/Item.js
src/components/Toolbar/tests/Block.test.js
src/components/Toolbar/tests/Item.test.js

Some toolbar items in HS App were rendering with no children when we didn't want to show that element. In https://github.com/helpscout/hs-app/pull/6264 I moved the `Toolbar.Item` inside the component so it also wouldn't be rendered but this seemed to be mixing concerns. @TerrenceLJones had the idea of instead changing HSDS to not render if there are no children like we did for other components.

Don't render Toolbar Item/Block without any children

---

src/components/Input/Input.js
src/components/Input/__tests__/Input.test.js

This update fixes empty carriage return insertions when there is no pre-existing value in the field.

Fixes inserting empty return if there is no value in field

---

package-lock.json
package.json
src/components/Button/Button.css.js
src/components/Button/ButtonV2.js
src/components/Button/__tests__/ButtonV2.test.js
src/components/Button/docs/ButtonV2.md
stories/ButtonV2.stories.js

This update enhances the Button (v2) component to allow for the render of
`<a>` selectors if `href` is defined.
For performance, `memoize-one` was added to help cache the (re)generation
of the `ButtonUI` styled component.

Button: Add support to render link (for href)

---

src/components/Button/Button.css.js
src/components/Button/ButtonV2.js
src/components/Button/docs/ButtonV2.md
src/components/Button/types.js
stories/ButtonV2.stories.js

This update adds a new primary alt (purple) variant to `Button` (version 2).
This can be rendered by:
```jsx
<Button version={2} kind="primaryAlt" />
```

Button: Add PrimaryAlt (purple) variant

---

.groovyrc.json
src/components/Button/Button.css.js

This update adjusts `Button` (v2) to not have an underline for `:hover`
and `:focus` by default. Note, these styles do appear if the `kind` of the
button happens to be a `link`.

Button: Remove underline for link selector

---

src/components/Tag/README.md
src/components/Tag/Tag.css.ts
src/components/Tag/Tag.tsx
stories/Tag/Tag.stories.js

https://trello.com/c/sanmmp8E/937-yellow-tag-not-supported-in-chat-ui-hsds
This fix adds the color yellow as a possible tag color.

Add color yellow to tag colors

---

src/components/Attachment/Attachment.css.js
src/components/Attachment/Attachment.tsx
src/components/Attachment/__tests__/Attachment.test.js
src/components/Attachment/docs/Attachment.md
stories/Attachment.stories.js
stories/AttachmentList.stories.js

This update adds an state support for `Attachment`, allowing for a state
of `error` to render a red border.
---
Testing:
https://deploy-preview-473--hsds-react.netlify.com/?selectedKind=Attachment&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

Attachment: Adding Error state

---

src/components/AnimateGroup/__tests__/AnimateGroup.test.js
src/components/Dropdown/V2/Dropdown.Container.tsx
stories/DropdownV2.stories.js

This update resolves the issue for `DropdownV2` where new items being passed
may (or may not) re-render correctly.
The issue was `Dropdown.Container`, which handles the diff'ing + state
updating process from external props.
The `nextState` that was building was being clobbered over as it trickles
down the conditional logic tree.
---
Unrelated, I fixed the `AnimatedGroup` test so that it stops spitting out
errors during the test run.
Resolves: https://github.com/helpscout/hsds-react/issues/474

DropdownV2: Resolve item render updates

---

src/components/Attachment/Attachment.css.js

This update fixes the text color for `Attachment` when it is `:hover`,
specifically for the error state.
https://github.com/helpscout/hsds-react/issues/476

Attachment: Fix error link (hover) colour

---

src/components/RateAction/RateAction.css.ts

This update fixes the green active circle rendering for RateAction buttons.
The issue came from a lack of CSS `box-sizing`, resulting in inconsitent size
rendering depending on the environment.

RateAction: Fix active circle sizing

---

src/components/Message/styles/Bubble.css.js
src/components/Message/styles/Embed.css.js
src/components/Message/styles/Media.css.js

https://trello.com/c/OXlQfWF7/960-update-note-styling-to-be-more-accessible
Changes the note message bubble to text `yellow-900`, background `yellow-200` and border `yellow-400` so that there is more contrast between text and background. This will become more noticeable when we change the color yellow to the new palette.
Storybook: https://deploy-preview-487--hsds-react.netlify.com/?selectedKind=Message&selectedStory=content&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Update the color of note chat message bubbles

---

src/components/Message/Media.js

This update removes the caption from the preview modal.

Message.Media: Remove caption from modal

---

src/components/Pop/Pop.js

This update replaces the async/await usage in Pop with standard JS
Promises. This ensures the consuming application has an easier time
compiling with minimal/no adjustments to existing Babel configs.

Replace async/await usage in Pop with Promise

---

src/components/Input/Input.js
src/components/Input/__tests__/Input.test.js
stories/AutoDropdown.stories.js

This update addresses an issue where opening an autodropdown would cause the page to scroll to the bottom.
This issue impacted the autodropdown when the number of items exceeded the threshold that has us render a filterable dropdown menu. That is 15 items by default. It also was only a noticeable issue on pages with a scrollbar. However, when those conditions were met, the dropdown was unusable.
Here is a demo of the problem:
Here is a demo of how things are looking after the fix:

Fix: Opening Autodropdown causes scroll to bottom

---

src/components/SplitButton/SplitButton.css.ts
src/components/SplitButton/SplitButton.tsx
stories/SplitButton.stories.js

Nice job on the SplitButton component @TerrenceLJones! Soon as it went out I scooped it up to use in app :)
This update improves the styles for the primary button with success + error state as well as the disabled states.
Here are some screenshots of before:
Here are some screenshots of after:

Fix appearance of disabled SplitButtons and SplitButtons with state

---

src/components/Button/ButtonV2.js
src/components/RouteWrapper/__tests__/RouteWrapper.test.js
src/components/RouteWrapper/index.js

This temporarily resolves unexpected Marionette routing issues in the App

Temporarily disable data-bypass in links

---

jest.config.js
package-lock.json
package.json
src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
src/components/Dropdown/V2/Dropdown.Trigger.tsx
src/components/Dropdown/V2/Dropdown.actionTypes.ts
src/components/Dropdown/V2/Dropdown.actions.ts
src/components/Dropdown/V2/Dropdown.css.js
src/components/Dropdown/V2/Dropdown.store.js
src/components/Dropdown/V2/Dropdown.tsx
src/components/Dropdown/V2/Dropdown.types.ts
src/components/Dropdown/V2/__tests__/Dropdown.MenuContainer.test.tsx
src/components/Dropdown/V2/__tests__/Dropdown.Trigger.test.tsx
src/components/Dropdown/V2/docs/Dropdown.md
src/components/Portal/Portal.js
src/components/SplitButton/SplitButton.tsx
src/utilities/__tests__/memoize.test.ts
src/utilities/env.ts
src/utilities/memoize.ts
stories/DropdownV2.stories.js
stories/SplitButton.stories.js

This update dramatically improves the menu positioning mechanisms for `DropdownV2`. The primary changes involved:
1. More frequent get/set for the `trigger` node
2. A `requestAnimationFrame` loop that performantly repositions the menu
3. A new `positionFixed` prop, which defaults to `false`.
https://www.useloom.com/share/60d1873ad62e4498b00bd2024ee7c8b9
cc'ing @jmauerhan for x-team review

DropdownV2: Better menu repositioning

---

.vscode/settings.json
src/components/ComboBox/ComboBox.tsx
src/components/ComboBox/__tests__/ComboBox.test.tsx
src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
src/components/Dropdown/V2/Dropdown.store.js
src/components/Dropdown/V2/Dropdown.types.ts
src/components/Dropdown/V2/__tests__/Dropdown.MenuContainer.test.tsx
src/components/Dropdown/V2/docs/Dropdown.md
stories/ComboBox.stories.js

(ComboBox, by default, should always drop down, if defined)
This update fixes the up/down menu position of `ComboBox` based dropdowns
that happens when the list size changes (during filtering).
The solution was to introduce a new prop called `shouldDropDirectionUpdate`.
By default, in `Dropdown`, it resolves to `true`. However, in `ComboBox`,
we'll resolve it to `false`.
The user can adjust this, if required.
`Dropdown` auto positioning works as before:
I recorded a screencast for additional details:
https://www.useloom.com/share/be89d280e6984512a707571e35e15cbc
---
Future enhancement idea:
Ideally, the menu position **should** auto calculate for `ComboBox`, but only on the initial render. Subsequent updates shouldn't change it's positioning. There are more edge cases with this, but I …

Dropdown: Fix ComboBox positioning with shouldDropDirectionUpdate

---

src/components/ChatTranscript/Item.js
src/components/Message/Bubble.js
src/utilities/__tests__/strings.test.js
src/utilities/strings.ts

https://trello.com/c/zowspdvk/889-use-rawbody-rather-than-body-when-outputting-chat-messages
During testing we discovered some test strings with URLs that were not handled correctly. There were some side effects when escaping the string before converting URLs to links. To resolve this issue we now escape the string for output at the same time as converting URLs to links. I have also added support for converting emails to links.
Lots of extra test cases have been added.

Improve the utility to convert URLs (and emails) to links

---

src/components/PropProvider/PropProvider.tsx
src/components/PropProvider/__tests__/PropProvider.test.js
src/utilities/__tests__/component.test.js
src/utilities/component.ts

This update improves the rendering stability for PropProvider, allowing it
to handle `props.children` of varying types, including booleans,
empty objects, and empty arrays.
The solution involved creating a new `renderAsSingleChild` utility which
encapsulates all that logic.
Resolves: https://github.com/helpscout/hsds-react/issues/523

PropProvider: Fix rendering for empty array

---

src/components/Button/Button.css.js
stories/GreeterCard.stories.js

This update fixes the Button (V2) styles to ensure that it gets the correct
theme properties from the `<ThemeProvider />`.
The shape of the `theme` prop should be:
```
theme = {
brandColor: {
...themeBrandColors
}
}
```
vs
```
theme = {
...themeBrandColors
}
```
Resolves: https://github.com/helpscout/hsds-react/issues/522

Button: Fix mapping of props.theme.brandColor

---

package-lock.json
package.json
src/utilities/__tests__/component.test.js
src/utilities/component.ts

This update fixes the `renderAsSingleChild` util function to handle the
rendering of Arrays, of zero, singular, or multiple items.

Fix renderAsSingleChild handling of Array

---

src/components/Pop/Popper.js
src/components/Pop/__tests__/Popper.test.js
stories/Popover.stories.js

This update improves the positioning of the Popover/Tooltip element in
relation to the trigger. The spacing on the left/right sides have been
reduced, to bring the elements closer together.
Resolve: https://github.com/helpscout/hsds-react/issues/535

Popover/Tooltip: Improve left/right placement

---

src/components/Icon/styles/Icon.css.js

This is a hotfix to remove icon scaling. We will address the proper sizing
of icons after a discussion with Design + Eng.

Icon: Remove scaling

---

src/components/Input/Input.js
src/components/Input/styles/BackdropV2.css.js
src/components/Input/styles/Input.css.js
src/styles/utilities/__tests__/font.test.ts
src/styles/utilities/font.ts
stories/Input.stories.js

This update improves the rendering of Input + Actions within an error state.
The solution was to re-arrange the UI to always have the actions on the
right-est side of the Input
This update also fixes the Input focus ring to use `blue.500`, and sets the `input`/`textarea` font-family to system.
Resolves:
https://github.com/helpscout/hsds-react/issues/520
#546 
#545

Input: Fixed Action + Error rendering

---

package.json
scripts/make-version.js
src/components/PropProvider/propConnect.tsx
src/utilities/__tests__/info.test.ts
src/utilities/info.ts
src/utilities/pkg.ts

This update adds some info about HSDS React to `window`, which would be helpful
for debugging.
A version generator script was added which runs right after a version bump
occurs during a release. This generates a file, which is used during the
build/compile step.
The mechanism that adds the info to `window` was snuck into `propConnect`, since
the chances of it instantiating is extremely high. We aren't able to add it to any entry file
(like the main `index.js`) since we don't use HSDS: React that way.
Resolves: https://github.com/helpscout/hsds-react/issues/529

Add HSDS version to window

---

src/components/Link/Link.css.ts
src/components/Link/Link.tsx
src/components/Link/README.md
src/components/Link/__tests__/Link.test.js
src/components/Link/index.ts
src/styles/components/Link.scss
stories/Link.stories.js

This update refactors the `Link` component to TypeScript and use `css.ts`.
The previous SCSS styles have been removed.
`Link` has also been enhanced with a new prop, `voidOnClick`. This disabled
the click interaction if set to `true`.
Resolves: https://github.com/helpscout/hsds-react/issues/532

Link: Refactor + add voidOnClick

---

src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
src/components/Dropdown/V2/Dropdown.MenuContainer.utils.ts
src/components/Dropdown/V2/__tests__/Dropdown.MenuContainer.utils.test.ts

This update fixes the issue with Dropdown (V2) where it did not factor in
`window.scrollY` and `window.scrollX` with it's `top` and `left`
calculations.
The fix involved creating a special util function to generated the computed
`top` and `left` values, which are used within the `Dropdown.MenuContainer`
position methods.

Dropdown: Fix top/left position calculation with window.scroll values

---

src/components/Icon/icons.all.js
src/components/Icon/icons.embed.js
stories/Toolbar.stories.js

This update fixes the close icon within the Tag component. The solution
was to provide the alias for `cross`, which was removed during the icon
refactor.
The Toolbar component story was updated for improved rendering.

Tag: Close icon fix

---

src/components/Message/styles/Content.css.js
src/components/PreviewCard/styles/PreviewCard.css.js
src/styles/mixins/cardStyles.css.js
src/styles/mixins/noteStyles.css.js
stories/Message/Message.stories.js

https://trello.com/c/sX3XeCBX/1075-docs-embed-cards-could-be-visually-improved
The style of the chat preview card for unfurled links did not match the padding of other chat bubbles. This PR addresses this by tweaking the default card styling when in the scope of a chat content component.
Before:
After:

Fix the padding of chat preview cards

---

src/components/Button/Button.css.js
src/components/Button/types.js
stories/ButtonV2.stories.js

This update adds a new size and primary state to the V2 Button.
For contrast reasons, the button color for the new `warning` state uses a base of `600` instead of `500`. 
A new size was added to Button. Size `lgxl`. This enables the button to render with a height of `50px`, which matches the requirements for the Beacon Embed design.

Button: Add new size and state to V2

---

src/components/Input/Input.js
src/components/OptionIcon/OptionIcon.js

This update fixes the 20->24 Icon rescale for usage within `Input` and
`OptionIcon`.

Icon: Fix rendering sizes within Input and OptionIcon

---

src/components/Button/Button.css.js

This update adds CSS to nullify the outline styles which may occur during
integration.
These outline styles are typically defined within reset/normalize
styles. Adding `outline: none` directly to the Button helps ensure that outline
removal is prioritized.
https://github.com/helpscout/hsds-react/issues/559

Button V2: Remove outline for hover, active, focus

---

src/components/ArticleCard/styles/ArticleCard.css.js

This cleans up the ArticleCard UI.
Changes 
- adjust space between Meta data and Title to 10px
- adjust space between the content and the Title to 7px
- adjust the space between the Content and Avatars to 10px

Clean up ArticleCard UI

---

src/components/Icon/styles/Icon.css.js
stories/Icon.stories.js

(GIF: Rendered Icon + caret overlaying latest mock from HSDS: Product UI)
This update adjusts the caret SVG sizing + alignment when used within
an `<Icon />` component via the `withCaret` prop.
https://github.com/helpscout/hsds-react/issues/555

Icon: Adjust caret sizing + alignment

---

src/components/KeypressListener/__tests__/KeypressListener.test.js
src/components/Pagination/Pagination.tsx
src/components/Pagination/__tests__/Pagination.test.js
src/utilities/__tests__/number.test.js
src/utilities/number.js
stories/Pagination.stories.js

This update add 3 small improvements to the Pagination component
Pressing `j` or `k` will update the current page
Current range and total of items are now formatted with the us format: 111,111.00
If the prop isLoading is active, all navigations button will be disabled

Improve pagination component

---

package-lock.json
package.json

This update locks React Treebeard at 3.1.0. This dependency comes from
`@storybook/ui`. There is a chance npm will install `react-treebeard@3.2.0`,
which uses `@emotion/core@10`. This breaks Storybook! Haha.

Storybook: Lock React Treebeard at v3.1.0

---

src/components/GreeterCard/GreeterCard.css.ts
src/components/GreeterCard/GreeterCard.tsx

- [Tighten line-height on the headings](https://trello.com/c/JlAwISd2/137-tighten-line-height-on-the-headings)
- [Tighten the typography of the body text](https://trello.com/c/q0kbZXt4/135-tighten-the-typography-of-the-body-text)
- [Line breaks are ignored in Embed](https://trello.com/c/ITC1nFSo/132-line-breaks-are-ignored-in-embed)
- [Greeter title text tooltip displayed on hover](https://trello.com/c/KWsmHYw2/138-greeter-title-text-tooltip-displayed-on-hover)
This PR updates the styles of the `GreeterCard` component based on feedback from Buzz and Ryan. Updates include:
- Updated line-height of title and subtitle components.
- Updated line-height, font-size and letter-spacing of body text component.
- Added `white-space: pre-wrap;` to body component to respect new line characters.
- …

Updated GreeterCard Styles

---

src/components/Input/Input.js
src/components/Input/Resizer.tsx
src/components/Input/__tests__/Input.test.js

This update resolves the `multiline` based size calculation for the
`Input` component. The solution was to provide one of the "ghost" inputs
with the correct `GhostUI` styled component to help account for
padding/line-height.
For context, the Input uses a ghost `textarea` to help recalculate the
height for auto-resizing.
Additionally, a default `maxHeight` of `320` was added for `Input`.

Input: Fix multiline size calculations + add default maxHeight

---

src/utilities/smoothScroll.js

**[Trello Card](https://trello.com/c/mHLEw62a/180-beacon-chat-doesnt-auto-scroll-on-microsoft-edge)**
This PR fixes the `smoothScrollTo` function, used by `ChatScroller` and other components so that it works in IE/Edge where the `scrollTo` method is not available.
Here's a demo of the auto-scrolling working correctly in Beacon chat:

Fix smoothScrollTo function to work in IE/Edge

---

package-lock.json
package.json
src/components/HsApp/HsApp.tsx
src/components/HsApp/Nav.tsx
src/utilities/pkg.ts
stories/HsApp.stories.js

This update removes the Helix dependency for the HsApp component,
making it easier to integrate into other environments/applications.

HsApp: Remove helix dependency

---

cypress/integration/Pagination.js
cypress/support/commands.js
src/components/Pagination/Pagination.css.js
src/components/Pagination/Pagination.tsx
stories/Pagination.stories.js

This update adds a list of cypress tests for the Pagination component
This is the first time I am working with Cypress. Feel free to give advice or request some changes to this PR
Next step would be to add cypress to travis-ci, and then add Percy to the integration suite

Add Cypress tests for Pagination component

---

.storybook/preview-head.html
src/components/Avatar/Avatar.Crop.tsx
src/components/Avatar/Avatar.Image.tsx
src/components/Avatar/Avatar.css.ts
src/components/Avatar/Avatar.tsx
src/components/Avatar/__tests__/Avatar.test.js
stories/AvatarStackV2.stories.js

This update fixes the Avatar image crop rendering for Safari on iOS and Mac OS.
The solution involved migrating the transition styles to a parent DOM node,
in this case, another wrapping `div`, instead of applying it directly on
the `div.image`.
To simplify the (pretty complex) Avatar component, `Avatar.Image` and `Avatar.Crop`
sub-components were created to contain the rendering logic for those pieces
of UI.
This has been tested on both Mac OS and iOS (iPhone 8).
Resolves: https://github.com/helpscout/hsds-react/issues/581

Avatar: Render fix for Safari (Mac/iOS)

---

src/utilities/__tests__/strings.test.js
src/utilities/strings.ts

https://trello.com/c/ybWLWC8N/1162-beacon-20-chat-design-domain-not-recognized-as-email-add
We were only matching domains with TLDs that were up to 4 characters long. With all of the new TLDs the maximum length is now 24 characters. This PR fixes this.
While fixing the TLD length issue I also found that we had some other problems with the regular expression and we were matching things like `www.test./path`. I have reworked the regular expression and added more test cases.

Improve auto linking to allow longer TLDs

---

package-lock.json
package.json
src/components/AvatarGrid/AvatarGrid.js
src/components/Message/Message.js
src/components/Message/__tests__/Message.test.js
src/components/StatusAvatar/StatusAvatar.js
src/utilities/pkg.ts

@jaredmcdaniel has a [PR](https://github.com/helpscout/hs-app/pull/6653) in play to make all Avatars in `hs-app` circles. In order to make this happen, we need to change the `<Message>` component in HSDS to stop enforcing `rounded`. 
This PR changes the logic to enforce `shape="circle"` on all `Message` component `Avatar`s regardless of theme. (Embed was already circles)

Avatars: Make shape default to circles

---

src/components/Input/BackdropV2.js
src/components/Input/__tests__/BackdropV2.test.js
src/components/Input/styles/BackdropV2.css.js
src/components/Input/utils.js

[Trello Card](https://trello.com/c/YhkkvCSD/1152-focus-state-for-inputs-with-errors-should-be-red)
This refactors the outline color of an input with an error.

Refactor input error-state outline color to Red

---

src/components/Page/styles/Card.css.ts

[Trello Card](https://trello.com/c/aAVMc6Sz/1151-additional-20px-padding-required-on-the-bottom-of-greeter-settings-blocks)
Add extra margin to the bottom of Page.Card component.

Page.Card: Add additional bottom margin

---

src/components/Dropdown/V2/Dropdown.ItemSelectedCheck.tsx

This update fix an issue where the label was not render inside a multi select dropdown. The component `ItemSelectedCheck` will now render the label if available.

Dropdown: Fix label rendering in multi select 

---

src/components/Dropdown/V2/Dropdown.Renderer.tsx
stories/AutoDropdown.stories.js

This update fixes the Dropdown: Multi-select active rendering, specifically
for items without an `id` prop.
This update provides the matcher util with the `indexMap` id for both `id`
and `value` (as fallback) to determine the `is-active` UI state.

Dropdown: Multi-select: Match active item (without id)

---

src/components/Avatar/Avatar.Crop.tsx
src/components/Avatar/Avatar.tsx
stories/Avatar/AvatarV2.stories.js

This update adjusts the `Avatar` component to remove the background color
once the Image is loaded in. This prevents unexpected cropping issues
around the edge of rounded/circular avatars.

Avatar: Remove background when image is loaded

---

src/utilities/strings.ts

We had issues with the regex in IE11 that resulted in syntax errors.
After removing the modifier the story loads and the URL is converted to a link.

Remove unicode modifier from auto linking regex

---

src/components/EventListener/EventListener.tsx
src/components/Pop/Arrow.tsx
src/components/Pop/Pop.tsx
src/components/Pop/Pop.types.ts
src/components/Pop/Pop.utils.ts
src/components/Pop/Popper.tsx
src/components/Pop/README.md
src/components/Pop/docs/Pop.md
src/components/Popover/Popover.tsx
src/components/Popover/__tests__/Popover.integration.test.tsx
src/components/Tooltip/Tooltip.tsx

This update fixes the closeOnBodyClick mechanic of `Pop`, which powers
`Tooltip` and `Popover`.
The issue was the click handler was never actually called. The solution
was to add `EventListener` to scope on `document.body` to handle the
interaction.
A nice enhancement was added to `Pop` to allow for the user to determine
if the `Pop` component should open/close before it happens with a
`Function` that returns a `boolean`. This enables finer grain control
for situations.
Cyan tests have been added to `Popover` to test these interactions and
integrations.
Also! For this PR, `closeOnBodyClick` will be set to **true** by default!
Resolves: https://github.com/helpscout/hsds-react/issues/623

Pop (Tooltip/Popover): Fix closeOnBodyClick

---

src/components/FormGroup/styles/Choice.css.ts
src/components/FormGroup/styles/FormGroup.css.ts
src/components/Page/styles/Page.Card.css.ts
stories/Page/Page.Example.stories.js

(Screenshots from Zeplin)
This update adjusts the bottom of `Page.Card` to have a margin of `65px`,
matching the latest designs. `FormGroup` margin has also been bumped to `20px`.
cc'ing @digitaldesigner for heads up!

Page: Adjust margins

---

package-lock.json
package.json
src/components/ActionSelect/ActionSelect.ContentResizer.tsx
src/components/ActionSelect/ActionSelect.tsx
src/components/ActionSelect/ActionSelect.types.ts
src/components/ActionSelect/__tests__/ActionSelect.test.tsx
src/components/Choice/Choice.tsx
src/components/Choice/Choice.types.ts
src/components/Choice/__tests__/Choice.test.js
src/components/Choice/styles/Choice.css.js
src/components/Dropdown/V2/Dropdown.Trigger.tsx
src/components/Dropdown/V2/Dropdown.actions.ts
src/components/Message/__tests__/Message.integration.test.js
src/components/Pop/Pop.tsx
src/components/Pop/__tests__/Pop.test.js
src/utilities/focus.ts
src/utilities/node.ts
src/utilities/pkg.ts
stories/ActionSelect.stories.js

This update fixes the resizing and refocus interactions when an item
is selected from the Dropdown.
A special focus util has been added to ensure the scroll position doesn't
jump on focus.
The resizing mechanism in ActionSelect has been optimized to only fire during
a new selection, rather than on children change.
Ensure Checkbox/Radio aren't display block, by default
Fix click interactions with Trigger, `document.body`, and content.

ActionSelect: Fix resize and refocus interactions

---

src/components/Page/Page.Actions.tsx
src/components/Page/Page.StickyActions.tsx

This update adds a guard for `IntersectionObserver`, which is used for the
sticky feature in `Page.Action`.
The issue would only occur JSDOM. Target browsers (Edge+) supports this
feature

Page.Action: Add guard for IntersectionObserver

---

src/components/Accordion/Accordion.Title.tsx
src/components/Accordion/Accordion.types.ts
src/components/Accordion/__tests__/Accordion.Title.test.js

This update fixes the GreeterRow to ensure that clicks (and keyboard Enter
press) works as expected (which is that it performs like a regular link).

GreeterRow: Fix link clicks

---

package-lock.json
package.json
src/components/ActionSelect/ActionSelect.tsx
src/utilities/pkg.ts

This update adjusts the scrollIntoView mechanism of ActionSelect to
check against the current position of `window.y` to determine if scrolling
is required.

ActionSelect: Scroll into view if needed

---

src/components/Pagination/Pagination.tsx
src/components/Pagination/__tests__/Pagination.test.js

This update hides the next and last button when the pagination is on the last page. This change of behavior was requested for hs-app

Pagination - Hide next & last button on last page

---

src/components/ConditionField/ConditionField.tsx
src/components/ConditionField/ConditionField.types.ts
src/components/ConditionField/README.md
src/components/ConditionField/__tests__/ConditionField.test.tsx
stories/ConditionField.stories.js

This PR updates ConditionField with a 'isWithRemove' prop, which allows enabling / disabling of the remove button.
Here's an example of why this functionality is needed:
http://c.hlp.sc/47c2d62e537f

Add isWithRemove to condition field to hide close icon

---

src/components/Avatar/Avatar.tsx
src/components/Avatar/Avatar.utils.ts
src/components/Avatar/__tests__/Avatar.test.js
stories/Avatar/Avatar.stories.js

This update add the possibility of having a fallback image in case the original image failed to load
If the fallback image failed to load as well, we default to the avatar background color.
```javascript
<Avatar
name={fixture.name}
image="https://notfound"
fallbackImage={imageUrl}
/>
```
The component was also reorganized to move some utility function out of the component, to make it cleaner and "simpler"
```javascript
isImageLoaded(props, state): boolean
hasImage(props, state): boolean
isFallbackImageLoaded(props, state): boolean
getImageUrl(props, state): string
```

Avatar fallback image

---

src/components/GreeterCard/GreeterCard.tsx

This updates the GreeterCard so that:
- the prop animationSequence defaults to an empty string
- we have some default truncation on text strings so that the card does not expand too much

Update default animationSequence and add trunctate

---

src/components/ConditionField/ConditionField.tsx

This update adjusts the `ConditionField` component to allow for props to be
passed through to `Flexy`, allowing for finer grain adjustments for configs
like `align`.

ConditionField: Pass props through to Flexy

---

src/components/EmojiPicker/styles/EmojiPicker.css.ts

This is a proposal for an alternative way of handling styles for Emoji Picker active/hover states. Previously, it was difficult to get the correct spacing for the background color for each emoji. This was inspired by how Github handles it's emoji picker for reactions.

Refactor EmojiPicker active/hover state styling

---

src/components/EmojiPicker/styles/EmojiPicker.css.ts

This removes the transition animation from the EmojiPicker when items are hovered or active.

Remove EmojiPicker hover state transition

---

.npmrc
package-lock.json
package.json
src/components/ActionSelect/ActionSelect.ContentResizer.tsx
src/components/ActionSelect/ActionSelect.tsx
src/components/ActionSelect/__tests__/ActionSelect.test.tsx
src/components/Animate/__tests__/Animate.test.js
src/components/AnimateGroup/AnimateGroup.tsx
src/components/BlankSlate/BlankSlate.tsx
src/components/BlankSlate/README.md
src/components/BlankSlate/__tests__/BlankSlate.test.tsx
src/components/BlankSlate/styles/BlankSlate.css.js
src/components/Page/Page.StickyActions.tsx
stories/BlankSlate.stories.js

Help Scout has a new illustration library: [hsds-illos](https://github.com/helpscout/hsds-illos). These illustrations are from our design system and meant to be imported into any project. We should be able to mix and match them with hsds-react components as needed.
This update adds support for using illustrations from our illustration library with the BlankSlate component. Currently, the BlankSlate component leverages the Illo component in this library, which includes a small set of illustrations. I recommend that we deprecate the `illoName` and `illoSize` properties on the BlankSlate component in favour of this more flexible and maintainable approach of using the illustration library as the source.
Below is an example Blank Slate with an illustration from our separate illustration …

Support Custom Illos in BlankSlate Component

---

src/components/Pop/Pop.tsx
src/components/Popover/__tests__/Popover.test.tsx

When attempting to upgrade hsds-react in Beacon embed, I ran into an issue that was preventing the app from rendering.
I found out that the issue originated in version 2.43.1, which added an `EventListener` to the `Pop` component: https://github.com/helpscout/hsds-react/releases/tag/v2.43.1
I'm not sure if this issue doesn't happen in hs-app, and if that's the case it might be because embed is still in React 15, but the issue seemed to be that "Providers" can only have a single child component, and with this update we were now returning two: `EventListener` and `PopUI`.
To fix this, I've wrapped both components in a `div`, which is the only React 15-compatible solution I know of, but if you know of a better one, please let me know!

Fixed error with Tooltips in Embed

---

src/components/Condition/Condition.Operator.tsx
src/components/Condition/styles/Condition.css.ts

This change makes it easier to extend the `Condition.Operator` component.

Remove wrapper component to support extension

---

src/components/Message/Message.Chat.tsx
src/components/Message/Message.ChatBlock.tsx
src/components/Message/__tests__/Message.Chat.test.js
stories/Message/Message.Chat.stories.js

This update add a new prop to the `Chat` component called `metaPosition` to move the rendering of the meta block before or after the message bubble.
Prop value can be either `bottom` or `top`

Add a new prop to Chat to change the position of the meta block

---

src/components/EditableField/EditableField.Input.tsx
src/components/EditableField/EditableField.Truncate.tsx
src/components/EditableField/EditableField.tsx
src/components/EditableField/EditableField.types.ts
src/components/EditableField/EditableField.utils.ts
src/components/EditableField/__tests__/EditableField.Input.test.tsx
src/components/EditableField/__tests__/EditableField.test.tsx
src/components/EditableField/__tests__/EditableField.truncate.test.tsx
src/components/EditableField/styles/EditableField.Input.css.ts
src/components/EditableField/styles/EditableField.css.ts
stories/EditableField.stories.js

This PR is a quick follow to the just merged Editable Fields.

Editable Field Follow Up Fixes

---

src/components/EditableField/EditableField.Input.tsx
src/components/EditableField/EditableField.tsx
src/components/EditableField/styles/EditableField.Input.css.ts
src/components/EditableField/styles/EditableField.css.ts
src/components/Page/styles/Page.Card.css.ts
stories/EditableField.stories.js

This update add some small improvements to the `<EditableField />` component.
**Increase the size of the + icon**
**Add padding to the delete/clear icon**
**Show caret on hover**
**System font on all static content to match inputs**
**Update the Page.Card shadow**
_Not part of the EditableField component, but I squeeze that in_

Editable Field Follow Up Fixes Part II

---

src/components/Condition/Condition.Operator.tsx

This updates the font wait of the text.

Update Condtional Operation font weight

---

src/components/Input/Input.tsx
src/components/Input/Input.types.ts
src/components/Input/README.md
src/components/Input/__tests__/Input.test.js
src/components/Input/styles/Input.css.js
stories/Input.stories.js

https://trello.com/c/xfyBplpT/261-content-screen-tweak-error-verbiage-when-over-character-count
This adds a `charValidator` to the Input component.
We added 3 props to the input:
- withCharValidator (a clause so that we can block from default input)
- charValidatorShowAt (determines when the charValidator becomes visible)
- charValidatorLimit (how many chars are allowed in the input)
cc: @digitaldesigner

Add char validator to text inputs

---

src/components/Page/Page.StickyActions.tsx
src/components/Page/Page.utils.ts

The current "guard" to check if `IntersectionObserver` is present is brittle and does not work in all browsers (Safari 10).
This PR adds a proper check and has been tested on Safari 10

Fixes the IntersectionObserver guard for Safari 10, others

---

src/components/Input/Input.tsx
src/components/Input/Input.types.ts
src/components/Input/styles/Input.css.js
stories/Input.stories.js

After @tjbo expertly created and implemented the pill for character counting on Form Inputs, we noticed a few issues to address in this follow up.
1. When the pill appears, all the content below is pushed down: http://c.hlp.sc/281f55b675ca
2. When the pill first appears, there's a staggered effect: http://c.hlp.sc/04b2ad07a850
3. When reducing the character count to less than 250, the new count is briefly shown before the pill disappears. The pill should just disappear without displaying the new count: http://c.hlp.sc/281f55b675ca
To address 1) @ryan-mulrooney moved the pill `div` inside the InputUI component, and then `position: absolute`
2) and 3) is @tjbo's bag :)

Fix remaining pill issues

---

src/components/MessageCard/styles/MessageCard.css.ts

Pretty simple... 
The title, subtitle, and message body all overlapped the containing div if a long word was typed (German word, for example): https://trello.com/c/ivQZjg0M/275-demo-message-in-builder-long-strings-overlap
I just made word wrapping a thing throughout the MessageCard to apply to all elements.

Wrap words in MessageCard

---

src/components/Input/Input.tsx
src/components/Input/Input.types.ts
src/components/Input/__tests__/Input.test.js
src/components/Input/styles/Input.css.js

Took me a while to realize I can piggy back off max-length a bit here.
`-webkit-transform: translateY(0);` this line apparently forces hardware acceleration which takes care of some small UI bugs.

Fix char validator

---

src/components/Message/styles/Action.css.js

https://helpscout.atlassian.net/browse/COMMS-174
Added the link styles to links within the `Message.Action` component used for chat line items. Previously the links were the same color as the rest of the line item and it wasn't obvious that there was a link.

Add link styles to the Message.Action component

---

src/components/MessageCard/styles/MessageCard.css.ts

https://helpscout.atlassian.net/browse/COMMS-206
Descenders are being cropped when Truncate is nested within a Button. The default `line-height: normal` is being overwritten with `line-height: 1`.
I just changed the style back to `line-height: normal` for the MessageCard button in case `line-height:1` is required elsewhere for other buttons.

Truncated Button text

---

src/components/FilteredList/FilteredList.tsx
src/components/FilteredList/__tests__/FilteredList.test.js
stories/FilteredList.stories.js

This update fixes a bug in the inline version of the FilteredList component. If the length of the number of items to be rendered was less than n-1 then the separator would be rendered after every item in the list, including the last item.
The reason why was the original logic determined if we were on the last item by checking if the next item was after the limit. However, in the case where we have, for example 1 item and a limit of 3, when on the first item the next item would not exceed the limit according to this logic. That meant the separator would be rendered even though nothing was to follow.
This update changes the logic to determine if we are on the last item by checking if the next item exceeds the length of the list of items to be rendered.

Fix: Inline FilteredList

---

src/components/Avatar/Avatar.tsx
src/components/Avatar/README.md
src/components/Avatar/__tests__/Avatar.test.js
src/components/Avatar/styles/Avatar.css.ts
stories/Avatar/Avatar.stories.js

This update adds a new overlay when hovering an avatar.
This overlay is fully customizable and will follow the shape of the avatar (circle, rounded or square).
The Avatar dom element will be a button when it is `actionable`. This will add a focus state to the avatar
It adds 4 new props to the `<Avatar />` component:
* **actionable** Activate the action overlay
* **actionIcon** Change the actual icon of the overlay (default to the `trash`icon)
* **actionIconSize** Set the size of the overlay icon
* **onActionClick** Callback for then the overlay was clicked

Add Avatar action overlay

---

src/components/Avatar/Avatar.tsx
src/components/Avatar/README.md
src/components/Avatar/__tests__/Avatar.test.js
src/components/Avatar/styles/Avatar.css.ts
stories/Avatar/Avatar.stories.js

This update fixes an issue with the avatar button background color. In #685 we add replace the `<div>` with a `<button>` when the `Avatar` component is actionable. By doing that the default button background was still present. Now it will be a transparent background. 
**Before**
**After**
This update add an animation sequence to remove an avatar. It will add a border animation, force load the fallback image and fade out the actual avatar. When the animation is completed, the avatar will not be clickable anymore
Right now this animation is only valid for the circle shape.

Fix Avatar background color & Add remove avatar animation

---

src/components/Avatar/styles/Avatar.css.ts

This fixes an `z-index` introduced in: https://github.com/helpscout/hsds-react/pull/691

Fix z-index issue in Avatar/Status UI

---

src/components/Dropdown/V2/Dropdown.Container.tsx
src/components/Dropdown/V2/Dropdown.Item.tsx
src/components/Dropdown/V2/Dropdown.actionTypes.ts
src/components/Dropdown/V2/Dropdown.actions.ts
src/components/Dropdown/V2/Dropdown.reducer.ts
src/components/Dropdown/V2/__tests__/Dropdown.Item.test.tsx
src/components/Dropdown/V2/__tests__/Dropdown.actions.test.ts
src/components/Dropdown/V2/__tests__/Dropdown.reducer.test.ts

- ### Allow for a dropdown item to be clickable, but not update the dropdown’s internal selectedItem state
The ideal usages for this would be when you have a set of items that should display as selected or not, along with items that might be present to trigger an external action, but not be set to the selectedItem. 
An example is the following usage, where the statuses selected but items like `Your Profile` should not be set to the selected item, but just trigger a click event. 
- ### Allow for the internal `selectedItem` state to be updated and controlled from outside the component.

Dropdown V2 adjustments

---

src/components/Dropdown/V2/Dropdown.Item.tsx

This adds support for `Dropdown.Items` to have a type of `header`. This allows for a user to pass an item with the type of `header` in the array of items passed to the `Dropdown` component.
For example you can now:
```
const items = [ { type: 'header', label: 'Chat Status' }, ...items ]
```

Allow Dropdown Items to have a type of `header`

---

src/components/Avatar/Avatar.Crop.tsx
src/components/Avatar/Avatar.tsx
src/components/Avatar/__tests__/Avatar.test.js
stories/Avatar/Avatar.stories.js

The avatar component was flashing when updating the state from loading to loaded. It was cause by the Avatar.Crop component changing his background image to currentColor to transparent.
By removing that line we make sure the avatar will fade in on top of the placeholder color

Fix Avatar that was flashing when loading was completed

---

stories/Input.stories.js

**Problem**
The storybook's input disabled state is in focus and does not match the HSDS spec. A disabled input by definition should not be "focusable".
Storybook: https://hsds-react.netlify.com/?path=/story/input--disabled
HSDS: https://helpscout.slab.com/posts/hsds-product-ui-7l7onzj2#forms
**Solution**
Remove the **autofocus** attribute from the input.
**Background**
For context, please see Jared's comment in this PR: https://github.com/helpscout/hs-app/pull/7236#issuecomment-522842380

Fix input disabled state in storybook to reflect HSDS

---

.eslintrc.js
src/components/EditableField/EditableField.Input.tsx
src/components/EditableField/EditableField.Truncated.tsx
src/components/EditableField/EditableField.tsx
src/components/EditableField/EditableField.utils.ts
src/components/EditableField/__tests__/EditableField.Mask.test.tsx
src/components/EditableField/__tests__/EditableField.test.tsx
src/components/EditableField/__tests__/EditableField.truncated.test.tsx
src/components/EditableField/styles/EditableField.Mask.css.ts
src/components/EditableField/styles/EditableField.Truncated.css.ts
stories/EditableField.stories.js

There were a couple of visual bugs on email type fields reported by Jared:
1. Extra spacing: http://c.hlp.sc/ac63799be531
2. Weird deletion behaviour when space present in value: http://c.hlp.sc/7a4b054a1277
Before, I had a minimum width on the "first chunk" (the part before the _@_), which in cases like a single letter name, would be too much and show extra space.
I removed the minimum width and instead applied a couple of rules to the second chunk (the domain), I also simplified the markup and included the _@_ in the second chunk to avoid some cases in which I noticed there was some extra space added to the first chunk because of how flexbox behaves.
This was a Chrome only bug, present when adding an "email" type to the input, I'm not sure why exactly, but the solution was to give the …

EditableField: Fixes email type UI glitches

---

src/components/Truncate/README.md
stories/Truncate.stories.js

Documentation updates that got left out of #703 accidentally:
This PR updates the `<Truncate />` documentation to include the new `splitter` prop, and removes some unnecessary props from the new splitter example in the Truncate story.

Update Truncate documentation

---

src/components/Truncate/README.md
src/components/Truncate/Truncate.tsx
src/components/Truncate/Truncate.utils.ts
src/components/Truncate/__tests__/Truncate.test.js
src/components/Truncate/styles/Truncate.WithSplitter.css.ts
stories/Truncate.stories.js

Reverts helpscout/hsds-react#717
In prod, but not in Storybook, tooltips are showing up even when an email is not truncated.

Revert "HSDS-77 Fix Truncate component to show tooltip when truncated on splitter'"

---

src/components/SelectDropdown/styles/SelectDropdown.css.ts
stories/SelectDropdown.stories.js

https://helpscout.atlassian.net/browse/COMMS-299
Before:
After:

COMMS-299: Truncate the select dropdown labels when they're really long

---

src/components/RadioCard/README.md
src/components/RadioCard/RadioCard.tsx
src/components/RadioCard/RadioCard.types.ts
src/components/RadioCard/__tests__/RadioCard.test.js
src/components/RadioCard/styles/RadioCard.css.ts
stories/RadioCard.stories.js

This update adds the ability to render an heading and a content inside a RadioCard. It also add the possibility to limit the size of each card.

Add content, heading and maxWidth to the RadioCard component

---

src/components/Input/styles/Input.css.js
stories/Input.stories.js

This PR fixes a bug with Error states in the Input Component.
In condition builder in Messages we were having a problem in FireFox with slimmer inputs. This fixes that problem, so that the width of the input is calculated if there is an error.
http://c.hlp.sc/997ff0c21c71

Fix Input Width if is Error

---

src/components/Avatar/Avatar.Crop.tsx
src/components/Avatar/Avatar.Image.tsx
src/components/Avatar/__tests__/Avatar.test.js
src/components/Avatar/styles/Avatar.css.ts

https://helpscout.atlassian.net/secure/RapidBoard.jspa?rapidView=153&projectKey=COMMS&modal=detail&selectedIssue=COMMS-330
The user avatars shown on the Chat blank screen are A) blurry and B) have very subtle but noticeable blue pixelation around the image — both of which make them look bad.
This ticket fixes that by adding some styles.

Fix avatar styles

---

package-lock.json
package.json
src/components/ChatList/ChatList.BlankSlate.tsx
src/components/ChatList/__tests__/BlankSlate.test.js
src/components/ChatList/docs/BlankSlate.md
src/components/ChatList/styles/BlankSlate.css.js

https://helpscout.atlassian.net/secure/RapidBoard.jspa?rapidView=153&projectKey=COMMS&modal=detail&selectedIssue=COMMS-237
This update changes the ChatList Illo when there are no chats in the sidebar to a SpeechBubble.
Story:
https://deploy-preview-728--hsds-react.netlify.com/?path=/story/chatlist--list-empty

Change Chat List Illo

---

package-lock.json
package.json
src/components/EditableTextarea/EditableTextarea.tsx
src/components/EditableTextarea/styles/EditableTextarea.css.ts
src/utilities/pkg.ts

Currently, when empty, Editable Textareas are not focusable with normal usage (tab or shift+tab) or programmatically due to having a `display: none` rule applied.
This PR fixes the issue by using a different way to hide the `textarea` from view.

Fixes accessibility issues on empty Editable Textareas

---

src/components/Truncate/README.md
src/components/Truncate/Truncate.tsx
src/components/Truncate/Truncate.utils.ts
src/components/Truncate/__tests__/Truncate.test.js
src/components/Truncate/styles/Truncate.WithSplitter.css.ts
stories/Truncate.stories.js

JIRA: https://helpscout.atlassian.net/browse/HSDS-77
Note: This is largely the same PR as the one previously reviewed for HSDS-77 that I had to revert: #717 . Updates include:
1. Addition of `_isMounted` variable ([see commit](https://github.com/helpscout/hsds-react/pull/727/commits/6b7378437d70e76f45bd40b65a621b32cafeefbd))
2. Addition of setTimeout in componentDidMount to prevent issue where calculation for `isTruncate` is performed using `0` for `offsetWidth` and `scrollWidth`.
3. Removing some manipulation of the contentNode styles - I don't see the removal causing a problem in Storybook or hs-app. 
4. Updated tests that broke as a result of the `setTimeout` in `componentDidMount`.
1. When using `<Truncate />` with a splitter prop so you can truncate email addresses, the tooltip …

HSDS-77 Fixes for Truncate

---

package-lock.json
package.json
src/components/MessageCard/MessageCard.tsx
src/components/MessageCard/__tests__/MessageCard.test.tsx
src/components/MessageCard/styles/MessageCard.css.ts
src/utilities/pkg.ts
stories/MessageCard.stories.js

On #730 I've added styles for the MessageCard component on mobile. It was using media queries to determine if it should use the mobile styles or not, which worked well but didn't quite work on Beacon Embed because, since the component was rendered inside an iframe that was approx 350px wide, it was ALWAYS using the mobile styles, independently of the window's viewport size.
I tried to look for a way to tell the media query to use the window's size instead of the iframe's, but there doesn't seem to be a good way to go about it, so the styles are now applied using an `isMobile` flag.
Go to the [MessageCard story](https://deploy-preview-735--hsds-react.netlify.com/?path=/story/messagecard--default) in Storybook and check/uncheck the isMobile checkbox: https://share.getcloudapp.com/4gu7PmJk

Messages mobile 2

---

src/components/Avatar/styles/Avatar.css.ts

[Jira Ticket ](https://helpscout.atlassian.net/browse/COMMS-353)
This changes the default color for the Avatar component, when an image is not available.

Modify default color for Avatars

---

src/components/Dropdown/V2/Dropdown.Item.tsx
src/components/Dropdown/V2/Dropdown.css.js

In https://github.com/helpscout/hsds-react/pull/738 we made a change so that a Dropdown.Item could be rendered as an `a` tag instead of a `div` if the item had an `href` prop.
This worked fine, except in Chat UI. The items were being rendered as `div` components still, but most of the time, required two clicks for the `onClick` handler to fire.
To be honest, I'm not sure why this happened. The only thing we did here was change `ItemUI` to a factory that returns the ItemUI as a `div` or `a` tag. 
Nonetheless, reverting that fixed the problem. We can use the `withComponent` API method on a Fancy StyledComponent to dynamically change the div to an `a` when there is an `href` prop and this works.
In essence, we're doing the same thing, but one solution causes problems and the other does not.

Change way Dropdown ItemUI is created

---

.storybook/config.js
package-lock.json
package.json

The Console addon for Storybook was causing the loss of filename/line numbers. After polling the JS Guild, it was decided to just remove this package.

Remove Storybook Console addon

---

stories/ChatList/ChatList.stories.js

I’m not sure what changed here, but `fixtures` is an `object` and not an `array`.

Fix bug in ChatList story

---

src/components/Dropdown/V2/Dropdown.css.js

 When a custom trigger is passed to the Dropdown V2 component, click events from the custom element could trigger extra events in the MS Edge browser.
Since the Dropdown Trigger is explicitly handling events on itself and not using the click events from children, we can fix this problem by suppressing all events from the children. 
This of course needs to be tested in the MS Edge browser, but please test in all other browsers as well. 
Affected Components that pass `renderTrigger` props
- EditableField 
- “On Commit” story
- Emoji Picker
- Select Dropdown
- SideNavigation
- with dropdown header
- with long list dropdown
- Split Button
- AutoDropdown
- “Multiple instances” story
- AvatarSelector
- TabBar 
- “with secondary content dropdown” story

Prevent pointer events from DropdownTrigger children

---

src/components/Dropdown/V2/Dropdown.css.js

Bumps the active item color up so it's seen better when visual looking at it.
@digitaldesigner

Fix dropdown active item color

---

src/components/Form/Form.test.js

Before I merged #753, I forgot to add this missing test that was causing the complaints about test coverage. This puts coverage back at 100% (and removes a stray `.only` that had gotten by).

Fix missing test coverage.

---

src/components/Table/README.md
src/components/Table/Table.Body.tsx
src/components/Table/Table.tsx
src/components/Table/Table.types.ts
src/components/Table/__tests__/Table.test.js
stories/Table/Table.stories.js

This PR adds the ability for the Table to be collapsed after it has been expanded and use custom text for the "expander" button.
📚 [Story](https://deploy-preview-760--hsds-react.netlify.com/?path=/story/table--expandable)

Table collapse and custom expander text

---

src/components/Dropdown/V2/Dropdown.Container.tsx
src/components/Dropdown/V2/Dropdown.Item.tsx
src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
src/components/Dropdown/V2/Dropdown.MenuContainer.utils.ts
src/components/Dropdown/V2/Dropdown.renderUtils.ts
src/components/Dropdown/V2/Dropdown.tsx
src/components/Dropdown/V2/Dropdown.types.ts
src/components/Dropdown/V2/__tests__/Dropdown.MenuContainer.utils.test.ts
src/components/Dropdown/V2/docs/Dropdown.md

This adds support for a `customWindow` prop in the Dropdown Component. 
This is needed to allow for use of the component in Beacon. Because Beacon is shown in an `iframe` element, we need to be able to override the `window` reference in the component to use the `iframe`'s `window` object and not the `host`'s.
Testing:
- That no regressions were introduced into the Dropdown V2 functionality
- That the scrolling issue displayed in the gifs above are fixed. You can check out this [PR](https://github.com/helpscout/beacon2/pull/771) which has a  beta release of the this work installed.

Update Dropdown Component `window` reference

---

package-lock.json
package.json
src/components/Input/Input.tsx
src/components/Input/Input.types.ts
src/components/Input/__tests__/Input.test.js
src/components/Pop/Pop.tsx
src/components/Pop/__tests__/Pop.test.js
src/components/Select/Select.tsx
src/components/Select/Select.types.ts
src/components/Select/__tests__/Select.test.js
src/utilities/pkg.ts
stories/Input.stories.js
stories/Popover.stories.js
stories/Tooltip.stories.js

*[HSDS-114](https://helpscout.atlassian.net/browse/HSDS-114)*
This update improves the accessibility of errors on the Input component as well as generally improves the accessibility of the Tooltip component.
The Tooltip component was updated to:
1. When the Tooltip is set to open on hover and close on mouse leave, the Tooltip will also open on focus and close on blur.
2. When the Tooltip is set to open on click and close on click, the Tooltip will also open on enter press and close on enter press. Clicking or blurring will also close an open Tooltip.
Try the Tooltip story [https://deploy-preview-763--hsds-react.netlify.com/?path=/story/tooltip--default](https://deploy-preview-763--hsds-react.netlify.com/?path=/story/tooltip--default) and change the knob configurations to see the impact …

Input Error and Tooltip Accessibility

---

src/components/Accordion/Accordion.Title.tsx
src/components/Accordion/__tests__/Accordion.Title.test.js
src/components/Accordion/styles/Accordion.css.ts

In this PR we update the Accordion styles to:
1 - have smaller carets
2 - have no background or border on the section title row
I back channeled with @digitaldesigner  and he is aware of the places (SavedReplies, CustomProperties, TranslateBeaconSettings) where this will be updated in HSAPP, and he wants it to be a global change.
Before:
After:
CC: @digitaldesigner

Tweak accordion styles

---

package-lock.json
package.json
src/components/ActionSelect/ActionSelect.ContentResizer.tsx
src/components/ActionSelect/ActionSelect.tsx
src/components/ActionSelect/ActionSelect.types.ts
src/components/ActionSelect/README.md
src/components/ActionSelect/__tests__/ActionSelect.ContentResizer.test.js
src/components/ActionSelect/__tests__/ActionSelect.test.tsx
src/utilities/pkg.ts
stories/ActionSelect.stories.js

https://helpscout.atlassian.net/secure/RapidBoard.jspa?rapidView=153&projectKey=COMMS&modal=detail&selectedIssue=HSAPP-994
On the New Onboarding Screen we have a way to update the box height programatically. When placing this ActionSelect on that Screen, (it has has a programatic CSS animation update); it was getting very janky behaviour.
In this case CSS doesn't have a `animationUpdated` listener, so we've set an interval timer to call on `onAnimationUpdate`.

Add animation callback to action select

---

src/components/Tooltip/Tooltip.tsx
stories/Modal.stories.js

The default zIndex for our Tooltip component should allow it to work within a Modal. Currently, you would need to manually override the z-index for a Tooltip appearing from within a Modal for it to appear.
**Before (default zIndex = 999)**
**After (default zIndex = 9999)**

Increase Tooltip default zIndex for use in Modals

---

src/components/AvatarList/AvatarList.tsx

[Jira Ticket](https://helpscout.atlassian.net/browse/HSAPP-1271) 
This refactors the `AvatarList` to support Tooltip child types. This is needed in the Chat App in HS App to support the new agent typing tooltip.

Refactor AvatarList to support Tooltips as children

---

src/components/Message/Message.Bubble.tsx
src/components/Message/__tests__/Message.Bubble.test.js
src/components/index.ts

This PR replaces the `LoadingDots` component usage in `Message.Bubble`, used for typing indication, with the `TypingDots` component.

Replace LoadingDots with TypingDots

---

src/components/Pop/Pop.tsx

A change was made to the Pop component several months ago to fix an  issue in Embed. However this change prevented the ability to override the styles on the base element in the Pop component. This change implements the functionality to allow for the overriding of styles of base element.

Refactor Pop component to allow styling base wrapper

---

src/components/RateAction/README.md
src/components/RateAction/RateAction.css.js
src/components/RateAction/RateAction.js
src/components/RateAction/RateAction.stories.js

Adds an `is-active` state to RateAction so that it can maintain an active state.

Fix active border in rate action component

---

src/components/Form/Form.js
src/components/Form/Form.stories.js
src/components/Form/Form.test.js
src/components/Form/README.md

[JIRA](https://helpscout.atlassian.net/browse/HSAPP-1325)
This PR lets the Form component accept custom props for the Save, Cancel and Delete buttons, which will allow you to pass through along any prop that the current `<Button />` component accepts, like `disabled`, `isLoading`, etc.
Testing:
[Story](https://deploy-preview-785--hsds-react.netlify.com/?path=/story/form--with-custom-button-props)
Storybook has been updated with a custom story under `Form => with custom button props`. There are knobs you can use to change the current value or pass in a new value, but I've noticed that I can only make one change before having to refresh the page - just FYI. 
Example GIF: https://c.hlp.sc/2Nurn8Yq
If you change `{"disabled": true}` to `{"disabled": false}`, you should see the save button …

HSAPP-1325 Tweak Form component to accept custom button props

---

src/components/Accordion/Accordion.css.js

This update fixes the positioning of the drag handle in the sortable Accordion component. The drag handle should be positioned relative to the Section Title, not relative to the entire Section.
[Before](https://p-zkf42x.t2.n0.cdn.getcloudapp.com/items/DOu8X9Od/Screen+Recording+2020-02-11+at+12.39+PM.gif?v=2292d5b7b7a56e81e2a76b161bdbd1e8)
[After](https://p-zkf42x.t2.n0.cdn.getcloudapp.com/items/JruWkgRR/Screen+Recording+2020-02-11+at+12.38+PM.gif?v=5641728837fa990b5edb1ed4a4175d27)

Fix Sortable Accordion Drag Handle Position

---

src/components/Button/Button.css.js
src/components/Button/Button.jsx

[Jira](https://helpscout.atlassian.net/browse/JS-88)
**What's the issue**
react-testing-library is not able to retrieve the Button label because our component wrap the label with a `span`.
**What's the new behavior?**
When the button is not loading, we don't wrap the button children with a span. We still need to wrap the children when it's loading to keep the button size the same for when the `isLoading` flag will be turned off.

Remove wrapping span around the button childrens only when it's not loading

---

src/components/Input/Input.tsx
src/components/Input/__tests__/Input.test.js

*Problem:*
When typing in a multiline text input with a scroll bar, if you moved the caret to the top of the input the multi input would auto scroll to the bottom.
*Solution:*
Remove scrollToBottom. Looking at the blame I could not figure out why this was added. It seems this is a bit over engineered; I've removed, but am confused as to why it was even there in the first place, since the native behaviour of the input seems to be what we want.
ie, it doesn't scroll to the bottom when the caret is at the top.

Remove scroll to bottom

---

src/components/Message/styles/Bubble.css.js

This PR removes the `helix` library import that was added on https://github.com/helpscout/hsds-react/releases/tag/v2.87.0 to avoid increasing bundle size.
The imported module was not being used so I assume we won't have any issues :)

Remove Helix import

---

src/components/Message/Message.Bubble.tsx
src/components/Message/__tests__/Message.Bubble.test.js
stories/Message/Message.default.stories.js

In release https://github.com/helpscout/hsds-react/releases/tag/v2.88.0 the Chat UI was updated for when the message body included only Emoji characters. However this work did not include the scenario when message data was passed in the `body` prop. This PR addresses that missing support.

Fix emoji-only UI in Message.Bubble component

---

src/components/CopyCode/styles/CopyCode.css.js

We [changed the color of the border when the CopyCode component is focused to blue.500](https://github.com/helpscout/hsds-react/commit/b2846ef674e26a56bdcc2ccd305f68f677b8b914#diff-3b6a2f7b6a7795a08dfc329597b498c3R7), but the box shadow also needed to be changed. This PR changes it to match.
This is needed as part of https://helpscout.atlassian.net/browse/HSAPP-1535

Fix the border color of the CopyCode upon focus

---

src/components/Message/Message.Bubble.tsx
src/components/Message/styles/Bubble.css.js
src/components/Message/styles/Message.css.js
stories/Message/Message.default.stories.js

This address a spacing issues when Emoji only messages are sandwiched between other messages.

Fix chat message body with emoji spacing issue

---

src/components/Message/styles/Message.css.js
stories/Message/Message.default.stories.js

There was unfortunately a missing CSS rule, in the previous release: https://github.com/helpscout/hsds-react/releases/tag/v2.89.7

Adjust Mesage Bubble spacing that include Emoji

---

package-lock.json
package.json
scripts/codemod/cli.js
scripts/codemod/hsds-codemod.js
scripts/codemod/transforms/AutoDropdownTransform.js
scripts/codemod/transforms/AvatarGridTransform.js
scripts/codemod/transforms/ButtonTransform.js
scripts/codemod/transforms/ComboBoxTransform.js
scripts/codemod/transforms/CssVariablesTransform.js
scripts/codemod/transforms/DeprecatedComponentsTransform.js
scripts/codemod/transforms/DropdownV2Transform.js
scripts/codemod/transforms/PropProviderTransform.js
scripts/codemod/transforms/ReplaceImportsTransform.js
scripts/copy-files.js

First let's just say that I am very excited by this PR. After creating the migration plan for HSDS 3.0.0, I started to think on how we could make it easier for dev to execute that migration.
I am very please to introduce HSDS 3.0.0 codemods.
This tooling will help any developper kickstart the process of migrating an SPA to HSDS 3.0. It will refactor some code for you or give you hints of place that would need to be refactor.
When releasing HSDS, we will add a `bin` that we could run on any app that installed HSDS:
```
npx hsds-codemod [transform] [path]
```
**All:** Run all codemod
**AutoDropdown:** Rename AutoDropdown to SearchableDropdown and add the autoInput prop
**AvatarGrid:** Rename AvatarGrid to AvatarList, and add props center & grid
**Button:** Remove the version={2} prop to …

HSDS 3.0.0 migration codemods

---

package-lock.json
package.json

**[Customer Convo](https://secure.helpscout.net/conversation/1089679675/501512/)**
This upgrade is a [one-liner](https://github.com/helpscout/fancy/compare/v2.2.7...v2.2.8#diff-17db3debd221f187e2859daf66158d85R18) on Fancy that passes the `fcy` key to the `createEmotion` instance. In a [previous PR](https://github.com/helpscout/fancy/pull/48) we added the key to the Emotion instance used in iframes, and now we're doing basically the same for instances outside of iframes. This solves a conflict between Beacon and other websites using Emotion.
With this upgrade, all auto-generated class names in hsds-react will now be named `fcy-{hash}` instead of `css-{hash}`. Other than that, there should be no impact.

Upgrade Fancy to v2.2.8

---

src/components/VerificationCode/VerificationCode.js

The **`Verification Code`** component was not calling the `onChange` event when a new code is pasted in, only when typing in. We want the onChange to fire if the change is caused by pasting a new value in as well.

Verification Code: trigger the onChange event when a code is pasted

---

src/components/Modal/Modal.ActionFooter.jsx
src/components/Modal/Modal.stories.js
src/utilities/__tests__/focus/findCurrentFocusedNodeIndex.test.js
src/utilities/__tests__/focus/findFirstFocusableNode.test.js
src/utilities/__tests__/focus/findFocusableNodes.test.js
src/utilities/__tests__/focus/findLastFocusableNode.test.js
src/utilities/__tests__/focus/findNextFocusableNode.test.js
src/utilities/__tests__/focus/findPreviousFocusableNode.test.js
src/utilities/__tests__/focus/focusNextFocusableNode.test.js
src/utilities/__tests__/focus/focusPreviousFocusableNode.test.js
src/utilities/focus.js

This update adds two new props to `Modal.ActionFooter` that will disabled the action button when needed. `primaryButtonDisabled` & `secondaryButtonDisabled`
The node selector to find focusableNode did included disabled `<button>` and `<a>` with an `href`. We update the selector to better reflect what can be focused inside a modal

Add disabled props + Fix modal focus trapping

---

src/components/Modal/Modal.HeaderV2.jsx
src/components/Modal/Modal.jsx
src/components/Modal/Modal.stories.js
src/components/Pop/Arrow.jsx
src/components/VerificationCode/VerificationCode.jsx
src/components/VerificationCode/VerificationCode.stories.js
src/components/VerificationCode/VerificationCode.test.js

This updates move the focus to the first or last in the list based on if the user reach an edge node inside a Modal
_**edit**_
We also update the `Modal` component to add a new prop  `iconSize` to modify the size of the header icon
We split the autoSubmit prop into two different prop (`autoSubmitPaste` `autoSubmitKeyUp`), to allow for more customization. We can now trigger the auto submit on paste or keyup only, or for both.

Tab focus cycling in Modal

---

package.json
scripts/codemod/cli.js
scripts/codemod/transforms/ReplaceImportsTransform.js

This update adds 2 steps after selecting which codemod to run.
This will allows us to change when needed the package name that needs to be find&replace.
The extra prompt questions will be shown only when selected "All" or "Replace import path"

Configurable codemod import package name

---

src/components/Message/styles/Bubble.css.js

[Jira Ticket](https://helpscout.atlassian.net/browse/COMMS-589)
Refactor the UI for Chat message typing indicator. To achieve this, we:
- removed the background color of the Message Bubble
- move the y-pos of the typing indicator up 6px

Message Bubble w/Typing Indicator UI adjustments

---

src/components/CopyButton/CopyButton.tsx
src/components/CopyInput/CopyInput.tsx
stories/CopyButton.stories.js

CopyButton checkmark which displays on clicking copy, is too small when rendered inside a large version of the component and looks strange.
Also, makes a CopyButton within a CopyInput default to not being part of the focus loop
This is needed for two HSApp issues:
- https://helpscout.atlassian.net/browse/HSAPP-1926
- https://helpscout.atlassian.net/browse/HSAPP-1921
**Before:**
CopyButton size = anything => checkmark icon size = "tick-small"
**After:**
CopyButton size = "lg" => checkmark icon size = "tick-large"
CopyButton size = "md" => checkmark icon size = "tick-large"
CopyButton size = "sm" => checkmark icon size = "tick-small"
This adds new stories to the CopyButton for medium and small to demonstrate the difference on click.
)

CopyButton minor tweak: updates the checkmark size to match the button size

---

src/components/Alert/Alert.tsx
src/components/Alert/styles/Alert.css.ts

This update brings all UI changes to the `Alert` component that was done in v3, to the actual HSDS version.
There is not a tons of UI updates. The line-height was updates, and the component rely on the padding to keep thing well aligned. The icon size was also increase to 24.

Add Alert UI updates from v3

---

src/components/ComboBox/ComboBox.tsx

Previously the ComboBox component wasn't updating the internal `isOpen` state when the `isOpen` prop was updated.

COMMS-613 Add re-rendering on prop changes to ComboBox

---

src/components/Dropdown/V2/Dropdown.Trigger.tsx
src/components/Dropdown/V2/Dropdown.css.js

Included in this change is:
- adding spacing between dropdown menu and the trigger
- fix issue where triggers via renderTrigger were not being informed on hover events

COMMS-613 Dropdown Improvements

---

src/components/AvatarSelector/AvatarSelector.tsx
src/components/AvatarSelector/styles/AvatarSelector.css.js

When the AvatarSelector was used as a trigger for the Dropdown component, the hover prop was not be used to systematically add hover states to the Avatar button.

Add systematic hover state control to AvatarSelector

---

src/components/Form/Form.Actions.css.js

The margin-bottom on the HSDS Form, applied via the Form Actions, was 100px, which was much too large. It should have been 20px, which is consistent with other forms in Help Scout.
In the following screenshot, we see the Form Actions used inside an Accordion Section. In total, there is 120px of space at the bottom, where there should be 40px (20px for the Form Action margin bottom and 20px for the Accordion Section padding.
In the next screenshot we see how after applying this change, we have the correct amount of space.

PROD-726 Fix Margin Bottom on HSDS Form

---

.storybook/manager.js

This PR updates the default setting for displaying the Storybook Addon menu. Now the menu will be hidden by default.

Hide Storybook Addon Panel by default

---

src/components/Form/Actions/Form.Actions.css.js

The margin-bottom on the HSDS Form, applied via the Form Actions, was 100px, which was much too large. It should have been 20px, which is consistent with other forms in Help Scout.
In the following screenshot, we see the Form Actions used inside an Accordion Section. In total, there is 120px of space at the bottom, where there should be 40px (20px for the Form Action margin bottom and 20px for the Accordion Section padding.
In the next screenshot we see how after applying this change, we have the correct amount of space.

PROD-726 Fix Margin Bottom on HSDS Form (v2)

---

src/components/Dropdown/Dropdown.MenuContainer.jsx

This PR addresses several bugs in the Dropdown.MenuContainer component. The issues include:
- a memory leak created by not properly cleaning up an animation frame reference
- (uncovered by fixing the first bug) `memoSetPositionStylesOnNode`'s memorized function  props not being updated (reset) on close of the portal. 
To address these issues:
1. I added the missing animation reference update, so that that reference will be cleaned up by the `cancelAnimationFrame` call. 
2. Called `updateMenuNodePosition` in the `onPortalClose` call so that the result of the call to `getPositionProps` would produce its defaultValue and that would replace the memorized arguments in `memoSetPositionStylesOnNode`. This allowed for the next call to run `setPositionStylesOnNode` properly.
For a detailed …

Fix Dropdown.MenuContainer memory leak

---

src/components/Popover/Popover.jsx
src/components/Popover/Popover.stories.js

The Popover was hardcoded to trigger on click, but it needs to default to 'click' but be configurable so that will open on hover as well.
Solution: Update some props. The [triggerOn](https://github.com/helpscout/hsds-react/pull/830) prop exists in the documentation, but it wasn't being passed in, and we needed to remove the hard-coding to accept `triggerOn` instead.
Testing: Please check this out in Storybook using the action where you can switch between click and hover - you can try click as well as hover.
I created a beta release and tested this on the Properties feature branch - it's working there.

PROD-816 Update Popover to be able to display on hover

---

package-lock.json
package.json
src/components/FilteredList/FilteredList.jsx
src/components/FilteredList/FilteredList.stories.js
src/components/Tooltip/Tooltip.css.js
src/components/Truncate/Truncate.jsx
src/utilities/pkg.js

We found some issues on Truncate and FilteredList when inside the customer list table. Those fix will make sure the tooltip is append to the body instead of the parent.
That will stop the tooltip from being selectable, but it's something we can live with it right now, especially since the original tooltip in v2 was not selectable.
This update also contain a fix for the wrapping content of the tooltip on IE Edge.

Force FilteredList & Truncate to append tooltip on the body

---

package-lock.json
package.json
src/utilities/babel-plugin-hsds-imports/__snapshots__/plugin.test.js.snap
src/utilities/babel-plugin-hsds-imports/index.js
src/utilities/babel-plugin-hsds-imports/plugin.test.js

What do we _don't_ want?
```js
import Page from 'hsds-react-next/components/Page'
import Button from 'hsds-react-next/components/Button'
import Select from 'hsds-react-next/components/Select'
```
What do we want?
```js
import { Page, Button, Select } from 'hsds-react-next'
```
Currently applications need to import components using the first mode above to allow tree-shaking, otherwise we can use `import { Page, Button, Select } from 'hsds-react-next/components/'` (notice the "/components" requirement) but it won't be tree-shakeable.
This PR adds a babel plugin that takes care of it for you!
So feel free to write the nice and concise form of importing, and get all the benefits. Who said you can't have your cake and eat it too?
Have a look at the test cases, in a nutshell:
- Allows you to …

Adds Babel plugin to make HSDS imports nicer to write while tree-shakeable

---

.eslintrc.js
cypress/integration/Button.js
cypress/integration/Dropdown.js
cypress/integration/Modal.js
cypress/integration/Pagination.js
cypress/integration/Tooltip.js
cypress/support/commands.js
cypress/tsconfig.json
package-lock.json
package.json
src/components/Button/Button.stories.js
src/components/Modal/Modal.jsx
src/components/Modal/Modal.stories.js
src/components/Portal/Portal.jsx

Since we release HSDS v3, all our (two) cypress tests were broken. This update fix all of them and adds some small tests for Modal, Tooltip and Dropdown.
This update also fix a cypress issue that occured on hs-app related to iframe. We make sure that all components that use Portal (through our custom implementation) will be injected inside the iframe if it's within cypress (just like we did before with storybook).

Fix cypress

---

src/components/Message/Message.Bubble.css.js

Fix a styling issue with the HSDS Chat Message typing indicator.

Fix typing indicator styling issue

---

src/components/Input/Input.jsx

The styles of the trigger are interfering with the styles of the tooltip, constraining it to the width of the trigger. This causes the text to wrap and due to the tall height of the tooltip, its placement will be forced to the bottom more easily than it should. The image below illustrates the problem.
As [suggested in the documentation](https://atomiks.github.io/tippyjs/v5/faq/#my-tooltip-appears-cut-off-or-is-not-showing-at-all), the tooltip is being appended to the body to deal with the issue of the conflict between its display and the bounds of the trigger.

Fix: Tooltips on Input Errors Do Not Display Correctly

---

src/components/Button/Button.config.js

This update changes the background and active color for the secondary and tertiary buttons
Unless it is requested, we will only update v3 with that update
direct link to the buttons story : https://deploy-preview-842--hsds-react.netlify.app/?path=/story/components-buttons-button--everything

Update secondary & tertiary buttons

---

src/components/Button/Button.jsx
src/components/CopyButton/CopyButton.css.js
src/components/CopyButton/CopyButton.jsx
src/components/CopyButton/CopyButton.stories.js
src/components/CopyInput/CopyInput.jsx
src/icons/copy-small.svg

This update add an icon prop to the `CopyButton` component. We also add a label prop that can be turn off. The end result is a icon button that still has the confirm animation (triggered on click)
This update also change the CopyInput component to leverage this new button style

Change CopyInput to use copy-small icon

---

src/components/Modal/Modal.Body.jsx
src/components/Modal/Modal.HeaderV2.css.js
src/components/Modal/Modal.css.js
src/components/Modal/Modal.jsx
src/components/Modal/Modal.stories.js
src/components/Modal/__tests__/Modal.Body.test.js

We update the modal alert component to match the current specs
* sit vertically centered on the page be 440px wide
* have Horizontal padding: 50px
* have Top padding: 50px
* have Bottom padding: 60px
* have min-height 180px (vs 179)
* Button group sits 24px below the copy
Those changes will only affected `v3`

Update modal v2 alert styles to match design specs

---

package-lock.json
package.json
src/components/Accordion/Accordion.Section.jsx
src/components/Accordion/Accordion.Title.jsx
src/components/Accordion/Accordion.jsx
src/components/Accordion/Accordion.stories.mdx
src/components/Accordion/Accordion.storiesHelpers.js
src/components/Accordion/__tests__/Accordion.Body.test.js
src/components/Accordion/__tests__/Accordion.Section.test.js
src/components/Accordion/__tests__/Accordion.Title.test.js
src/components/Accordion/__tests__/Accordion.test.js
src/components/Accordion/docs/Accordion.md
src/utilities/pkg.js

This update rewrite the internal state of the Accordion component to use an array containing the current open section ids. Before it was converted to an object but now it's simpler and less prone to an out of sync state
We create our own hook to handle the state. See `useSectionState ` in the Accordion component
When using the external state, it is still an array, but the method to set the new state is pass as a prop. Also, the allowMultiple has no effect when the state is set outside of the component. It needs to be handle by the external state
```javascript
const [openSectionIds, setOpenSectionIds] = useState()
return (
<Accordion
openSectionIds={openSectionIds}
setSectionState={uuid => {
setOpenSectionIds([uuid])
}}
>
{dataWithIds.map((datum, index) => (
<Accordion.Section key={index} …
```

Refactor Accordion to use either an internal or external state

---

src/components/Accordion/Accordion.Title.jsx
src/components/Accordion/Accordion.css.js
src/components/Sortable/Sortable.DragHandle.jsx

@knicklabs spotted a few differences between the Accordion component implementation in v2 and v3. This PR solves these issues.
1. Sortable drag-handle updated to the right icon and size.
2. Fixed position of drag-handle while dragging an expanded item.
3. Fixed issue where chevron icons changed orientation when dragging them.

Fixed differences between v2 and v3 in Accordion component

---

src/components/ActionSelect/ActionSelect.ContentResizer.jsx

We were passing `...rest` as props to a styled component, which in this case was a `div`. Some of the props were not relevant so React was emitting a warning.
In this PR I have passed `rest` through the `getValidProps` utility so we only pass props that are valid.

Only pass valid props within ActionSelect ContentResizer

---

src/components/Animate/Animate.jsx

I've removed the call to `getValidProps` on the Animate component because it was filtering out props like `onEnter`, `onExit`, etc, which are needed for this component to work correctly.

Removed getValidProps call from Animate component

---

src/components/Radio/Radio.jsx
src/components/Radio/Radio.stories.js
src/components/Radio/Radio.test.js

`Radio` component was not internally passing down the `stacked` prop into the `Choice` component, therefore if you render a Radio with `stacked={true}` it did not get the` 'is-stacked'` classes and associated styling, and did not appear as stacked.
This PR ensures the stacked prop is passed through correctly and also adds a new story to Radio and test to support the change.

Bug Fix: Radio stacked prop was not passing through to Choice element, so stacked styles never applied

---

src/components/Tooltip/Tooltip.css.js

[Jira Issue](https://helpscout.atlassian.net/browse/HSDS-158)
When tooltips have long lines of text, the text breaks at arbitrary points, including mid-word. See the screenshot below.
I changed the value of the `word-break` style property applied to the tooltip to be `break-word` so that words are preserved if possible. 
You can try it out with various text content using the knobs in the add-ons pane on the [Tooltip Story](https://deploy-preview-859--hsds-react.netlify.app/?path=/story/components-overlay-tooltipv2--default).

HSDS-158 Tooltip Fix: Text breaks mid-word

---

src/components/Modal/Modal.ActionFooter.jsx

The Saved Replies app is being upgraded to HSDS V3 in [this PR](https://github.com/helpscout/hs-app/pull/8682), however cypress tests need to be updated. The tests were looking for data-cy attributes on buttons like Save and Cancel, but we're no longer hard-coding those buttons ourselves in the Saved Replies app, we're using the buttons that come with the Modal.ActionFooter, and they don't currently have unique data-cy attributes (the default one for the Button component comes through). 
Current data-cy attribute for the Primary button:
[
](url)
Updated data-cy attribute for the Primary Button:
This PR adds data-cy attributes to the Primary, Secondary, and Cancel button with Modal.ActionFooter.

Add data-cy attributes to Modal.ActionFooter

---

src/components/MessageCard/MessageCard.css.js
src/components/MessageCard/MessageCard.jsx
src/components/MessageCard/MessageCard.stories.js
src/components/MessageCard/MessageCard.test.js

This update fix an issue with the MessageCard rendering when there is no html, but with some `\n`.
When rendering the body, we will detect it contains any html element, if it's not the case, we will replace all `\n` with a `<br>`
We add a `overflow:auto` to the body if the content is bigger than the available space. We make sure that the title, subtitle, and action will always be visible in full within the `MessageCard` component

Fix MessageCard render issue

---

src/components/Select/Select.css.js
src/components/SelectDropdown/SelectDropdown.css.js
src/components/SelectDropdown/SelectDropdown.jsx
src/components/SelectDropdown/SelectDropdown.stories.js

This add disabled styling support to the `SelectDropdown` component.

Add disabled support to SelectDropdown component

---

src/components/Nav/Nav.Item.jsx

This update change the append location for error Tooltip inside a Nav.Item component (from `parent` to the `document.body`)

Change appendTo location for Tooltip inside Nav.Item

---

src/components/CopyButton/CopyButton.jsx
src/components/CopyCode/CopyCode.jsx
src/components/CopyCode/README.md

The copy button in the `CopyCode` button was too large. This was a regression caused by changes to Button size styles.

Fix CopyCode button sizing issue

---

src/components/Popover/Popover.jsx
src/components/VerificationCode/VerificationCode.jsx

Problem: The Popover's placement prop is dropped before rendering the tooltip, so no matter what value you send in for placement into a Popover component, it is always rendered as "top" placement (you can see this in the [prod story for Popover](https://hsds-react.netlify.app/?path=/story/components-overlay-popover--default) if you just adjust the placement prop in the knobs, the position never actually changes)
Solution: Popover's inner tooltip honors what you pass in for the placement value and positions it accordingly.
https://c.hlp.sc/d5uWZ6JQ
Problem: Tooltip on VerificationCode is displaying oddly
Solution: appendTo document.body

Bug Fixes: Popover placement prop is getting ignored, Verification Tooltip error rendering incorrectly

---

src/components/EditableTextarea/EditableTextarea.jsx
src/components/EditableTextarea/EditableTextarea.test.js

When running jest, you might have seen this warning scattered here and there:
Who cares right, it's only a warning _and_ test pass! 🍾 
BUT, because of course there is a but.
What that actually means is that the test causing the warnings are not actually running 😱... so of course they all pass...
I found such events in the `EditableTextarea` tests, when I fixed the warning a bunch of the cases failed 😩
Moral of the story, when testing asynchronous code in Jest, be extra careful!
Make sure to catch rejections, use `done()`, etc.

Textarea test fixes

---

src/components/CopyButton/CopyButton.css.js
src/components/Input/Input.jsx

This address two issues: 
- Fixes an issue with the Input tooltip not closing as expected when another Tooltip is hovered 
- Fixes a styling issue caused specificity issues in Safari

Bug fixes for CopyButton in Safari & Input Tooltip

---

src/components/CopyInput/CopyInput.jsx
src/components/CopyInput/CopyInput.stories.mdx
src/components/CopyInput/CopyInput.test.js

In HSDS v3 we lost the ability to display CopyInput with a text button. See Jira Issue: https://helpscout.atlassian.net/browse/HSDS-159
Adds an optional `buttonLabel` prop which defaults to null, but if provided, will be used as the copy button's text in place of a copy icon (which is still the default!)
New Story:
- CopyInput "text button"
http://localhost:8900/?path=/story/%F0%9F%A7%AC-components-forms-copyinput--text-button
New Test also added so please check that it passes!

CopyInput can render as a Text Copy Button instead of Copy Icon

---

src/components/Button/Button.jsx
src/components/Checkbox/Checkbox.stories.mdx
src/components/Choice/Choice.Input.jsx
src/components/Choice/Choice.jsx
src/components/Choice/Choice.test.js
src/components/Choice/ChoiceInput.test.js
src/components/ChoiceGroup/ChoiceGroup.jsx
src/components/ChoiceGroup/ChoiceGroup.test.js
src/components/CopyCode/CopyCode.jsx
src/components/Input/Input.BackdropV2.css.js
src/components/Input/Input.jsx
src/components/Radio/Radio.stories.mdx
src/components/RadioCard/RadioCard.css.js
src/components/RadioCard/RadioCard.jsx
src/components/RadioCard/RadioCard.stories.mdx
src/components/RadioCard/RadioCard.test.js
src/components/Select/Select.jsx

**Feature** 👉 We need a new component, `Checkmark`!
The solution is very similar to `RadioCard`, so much this component could be named `CheckCard`...
`RadioCard` normally gets used with `ChoiceGroup` like so:
```jsx
<ChoiceGroup>
<RadioCard icon="fab-chat" value="chat" />
<RadioCard icon="fab-antenna" value="antenna" />
<RadioCard icon="fab-buoy" value="buoy" />
<RadioCard icon="fab-search" value="search" />
<RadioCard icon="fab-question" value="question" />
</ChoiceGroup>
```
We'd like to continue using this pattern
`ChoiceGroup` has a `multiSelect` option, that like the name indicates allows you to select more than one choice in the group, usually with radio inputs you turn this off and with checkbox you turn it on.
A while back, @cocoabythefire mentioned she was having some issues with …

Fixing ChoiceGroup, RadioCard, Choice in preparation for Checkmark

---

src/components/Popover/Popover.css.js
src/components/Popover/Popover.jsx
src/components/Popover/Popover.test.js
src/components/Tooltip/Tooltip.css.js
src/components/Tooltip/Tooltip.jsx

Arrows ("tips") on the `<Popover />` are not rendering correctly, a regression from the refactoring of tooltips and popovers done recently.
No size was being passed to the arrow.
- Pass a default size of 14px, the arrows in Figma have a size of "10" (the arrow is just a little square rotated 45 degrees), to get an actual arrow of that size using a little math you arrive to the number of ~14 (the size of the diagonal):
- When the little square gets rotated, the browser does some _antialiasing_ which causes the little border of the arrow to appear lighter, I have made the border slightly darker to compensate for this effect
- I removed `getValidProps` from the component, as it was causing the `isOpen` prop to not be passed down.
- Also, renamed the prop `size` on the `ArrowUI` of the …

Fixes Popover arrow/tip rendering

---

src/components/ChoiceGroup/ChoiceGroup.jsx
src/components/ChoiceGroup/ChoiceGroup.test.js

**[Jira Issue](https://helpscout.atlassian.net/browse/HSDS-164)**
##Problem/Feature
A regression was introduced in https://github.com/helpscout/hsds-react/pull/872 which was released in [v3.5.2]( https://github.com/helpscout/hsds-react/releases/tag/v3.5.2) leaving us unable to upgrade to 3.5.2 or later. The regression was that ChoiceGroup components, when used as a single-select, would receive the single value wrapped in an array via the `onEnter` and `onChange` callbacks. Existing projects consuming this code expected the values to NOT be wrapped in an array.
##Solution
Update the `handleOnChange` and `handleOnEnter` component methods to invoke `onChange` and `onEnter` respectively with the value NOT wrapped in an array when the `multiSelect` prop is set to false. The corresponding test …

ChoiceGroup: onChange and onEnter callbacks always receive value wrapped in array but it only should be for multiSelect

---

src/components/Dropdown/Dropdown.jsx
src/components/Dropdown/Dropdown.stories.mdx

**[Jira Issue](https://helpscout.atlassian.net/browse/HSDS-165)**
The Dropdown component should support passing multiple selected items in order to support multi-selection when used as a controlled component. The propType definition for the `selectedItem` prop incorrectly excluded arrays from the allowed types. This regression has resulted in warnings being logged in other projects consuming this library.
The solution was to update the propType to accurately reflect what is supported by the component. An additional story was added as a basic demonstration of its use.

HSDS-165 Dropdown: update selectedItem propType

---

src/components/Checkbox/Checkbox.stories.mdx
src/components/Choice/Choice.Input.jsx
src/components/Choice/Choice.css.js
src/components/ChoiceGroup/ChoiceGroup.jsx

Previously the Checkbox component was not rendering its `disabled` state correctly. Also when the Checkbox component was displayed within a `ChoiceGroup` its explicitly set `disabled` state was being overwritten from within the `ChoiceGroup`.

Fix Checkbox disabled state

---

package-lock.json
package.json
src/components/Frame/Frame.jsx
src/components/Frame/Frame.stories.mdx
src/components/Frame/index.js
src/utilities/pkg.js

While testing the new Frame component, we realized that it was clearing the cache on the sheet on every function call (which can be a lot with functional component).
By wrapping the cache clearing code in `useMemo`, we make sure to reuse the same sheet if the one from the context didn't changed.
We also did some change on the html structure, and removed the default styles on the Frame component to ease the integration in beacon.

Fix Frame performance

---

package-lock.json
package.json
src/components/CheckMarkCard/CheckMarkCard.css.js
src/components/CheckMarkCard/CheckMarkCard.jsx
src/components/CheckMarkCard/CheckMarkCard.stories.mdx
src/components/CheckMarkCard/CheckMarkCard.test.js
src/components/ChoiceGroup/ChoiceGroup.jsx
src/components/ChoiceGroup/ChoiceGroup.test.js
src/components/Tooltip/Tooltip.css.js
src/components/Tooltip/Tooltip.jsx
src/utilities/pkg.js

This PR adds a new way to style the CheckMarkCard.
Changes:
- Use the prop `withStatus`:
```js
const withStatus = {
status: 'locked',
iconName: 'lock-closed',
iconSize: '20',
color: getColor('lavender.600'),
tooltipText: 'This is locked, leave it alone',
}
```
- `withStatus` takes precedence over `checked` (in case both are provided for some reason)
- If `tooltipText` is provided, a Tooltip with the provided string will be rendered.
- CheckmarkCard now keeps track of it's own checked status
- ChoiceGroup's `onChange` is now triggered with keyboard events
- Removed the `shouldComponentUpdate` lifecycle on ChoiceGroup because we need to rerender its contents even when the values have not changed (think when pagination is used)
- Updated stories

CheckMarkCard additions

---

src/components/MessageCard/MessageCard.css.js

The inline code element in MessageCard was not render correctly if the text was on multiple line
We improve the original implementation in the Editor, and bring those change inside hsds-react. We make sure that the height is not fixed, and now rely on `display: inline-block` to make sure the content stays inside the parent element

Fix inline code render issue within MessageCard

---

src/components/Popover/Popover.jsx

The `Popover` component was not passing the correct prop to the underlying `Tooltip` component. 
This PR fixes that issue.

Fix props typo in Popover component

---

src/components/MessageCard/MessageCard.css.js

The line-height of the MessageCard component's body was too large. This PR updates it from 26px to 22px.
You can check it out here: https://deploy-preview-885--hsds-react.netlify.app/?path=/story/%F0%9F%A7%AC-components-conversation-messagecard--default-story

Updated MessageCard line-height

---

src/components/Datepicker/Datepicker.Context.js
src/components/Datepicker/Datepicker.Day.js
src/components/Datepicker/Datepicker.Month.js
src/components/Datepicker/Datepicker.Navigator.js
src/components/Datepicker/Datepicker.PeriodCalendar.js
src/components/Datepicker/Datepicker.css.js
src/components/Datepicker/Datepicker.js
src/components/Datepicker/Datepicker.stories.mdx
src/components/Datepicker/Datepicker.test.js
src/components/Datepicker/Datepicker.utils.js

In this PR we add the ability to select a range of dates in the Datepicker.
✅ Use the new `enableRangeSelection` prop (default false)
✅ Restrict the selection to a minimum number of days with `minBookingDays`
✅ After completing a selection range, starting a new one clears the existing one
✅ `onDateChange` returns both `startDate` and `endDate`
✅ Adds `type=button` to days to avoid triggering a form submit event in case you use the datepicker inside one.
✅ Adds a performance improvement with `useMemo`
✅ Adds an outer container div (to allow the use of styled components)
✅ Adds `innerRef` to obtain the DOM node
📹 https://www.loom.com/share/871fd4a5bd6747fc86fd8f8b66cc09d1

Datepicker range

---

package-lock.json
package.json
src/styles/configs/colorway.js

This is the last color change to be up-to-date with our color palette.
Overall, the green color update is straightforward. The only color change that would have been tricky is the `green.800` & `green.900` (they are a bit more darker). Fortunately, we don't use that color anywhere within HSDS.
One component that would need a design review is `Button`. Just to make sure the color change match our design vision. It looks almost the same as before, except the active color:
Purple color is migrating to `indigo`.
Three HSDS components are affected by this change:
The custom status, which we believe is used within beacon:

Upgrade green & purple color

---

src/components/MessageCard/MessageCard.jsx
src/components/MessageCard/MessageCard.test.js

This PR adds an `onBodyClick` prop to the `MessageCard` component. We need this in order to implement a fix for [a bug](https://helpscout.atlassian.net/browse/BEMBED-228) in Beacon, where links in a Message's body open inside the Beacon iframe.
Pass a function as the `onBodyClick` prop to a `MessageCard`. The function should be called when you click on any element of the Message's body, but not when clicking on other parts of the Message (Title, Subtitle, Action CTA, etc).

Added onBodyClick prop to MessageCard component

---

src/components/MessageCard/MessageCard.css.js
src/styles/mixins/depth.css.js

We've recently found an issue on Beacon/Messages where the `MessageCard` component wasn't resizing correctly in some cases. After tracking down the bug, we found that it was coming from the HSDS [v3.9.3 release](https://github.com/helpscout/hsds-react/releases/tag/v3.9.3), where we added the depth component and refactored `MessageCard` to use the depth mixins.
In particular, the issue comes from the `will-change: box-shadow;` property that seems to be affecting the order in which property changes are calculated. Since we have a dynamic-height iframe that cares about when the `height` property changes, we were running into a conflict there.
My fix was to add a `d600Effect` depth constant that only applies the `box-shadow` styles.
I can't say I fully understand the `will-change` property, …

Use effect only shadow for MessageCard component

---

src/components/Datepicker/Datepicker.utils.js
src/components/Datepicker/Datepicker.utils.test.js

[Jira Issue](https://helpscout.atlassian.net/browse/HSDS-180)
There is a bug in the isMonthInThePast function the Datepicker utils that has surfaced and was caught be the 'isMonthInThePast' test in the Datepicker utils tests. The bug surfaced when we rolled over into the new year and since the test is failing we can not make new releases.
This blocked me in trying to release the next patch version 3.10.4.
The issue is with this logic:
```
return (
someDate.getFullYear() <= today.getFullYear() &&
someDate.getMonth() < today.getMonth()
)
```
The date used in the test was “May 29, 2020” and because we rolled over into 2021 this condition returned false when it should have returned true. May 29, 2020 is in the past but May is greater than January. We should only check if the month is less …

Fix: isMonthInThePast returns false for past dates if the month is greater than this month

---

src/components/Link/Link.css.js

[Jira issue](https://helpscout.atlassian.net/browse/HSAPP-2163) 
The SPF and DKIM links on the Outgoing Mail tab do not come into focus when using the keyboard. This issue is seen on Firefox only. 
The SPF and DKIM links are `Link` components. In the `:focus` pseudo-class, an outline is specified only for webkit browsers. I specify an outline for non-webkit browsers using the `Highlight` system color.

HSAPP-2163 Make links focusable on non-webkit browsers

---

package-lock.json
package.json
src/components/Icon/Icon.css.js
src/components/Icon/Icon.jsx
src/components/RadioCard/RadioCard.css.js
src/components/RadioCard/RadioCard.jsx
src/components/RadioCard/RadioCard.stories.mdx

[JIRA issue](https://helpscout.atlassian.net/browse/HSDS-178)
Purpose of this PR is to update RadioCard component to the newest design. The use of it can be found here: https://www.figma.com/file/JwgxQmv2KyQTKwoiuyxHGq/Spec%2F-Messages-1.5
The demo implementation: https://codepen.io/team/helpscout/pen/5d458fb128e71e612ef1ad7202b178cd
The main changes are in "checked" state, the whole card gets larger. Additional there's some opacity added for "non-checked" cards.
The implementation isn't precisely as in codepen, as there are used images and fixed sizes to achieve the result. However it looks and behaves very similarly. The only thing not implemented as part of this story is change of the font color - that's because it collides with the existing usage of this component.
The solution is to …

HSDS-178: Update RadioCard component

---

src/components/Tooltip/Tooltip.jsx
src/components/Tooltip/Tooltip.stories.mdx
src/components/Tooltip/Tooltip.test.js

This prop will allow us to remove the wrapping span around the tooltip trigger. That span exists to ensure a valid trigger for Tippy. It needs a forwardable component to attach any events on the trigger. In some scenario, that span become an issue:
- Focusable button, we need the button to have the focus state, not the wrapping span
- Group of components were we style based on the children position (first child, last child, etc) 
To make that new prop work, the children needs to be a unique and valid child:
```javascript
<Tooltip title="Hello" withTriggerWrapper={false}>
<button>No wrapping span Trigger</button>
</Tooltip>
```
If we pass a non-valid react element, it will be wrap with the span even though the flag is turned off
```javascript
<Tooltip title="Hello" …
```

Add withTriggerWrapper prop on Tooltip

---

src/components/Nav/Nav.Item.jsx
src/components/Nav/Nav.test.js

This PR adds possibility to provide data-bypass attribute for a Nav.Item component and it would be set on actual link html element.
Context for the change is this story: https://helpscout.atlassian.net/browse/HSAPP-3810. In this case, we are blocking route change on React router, however there's Backbone router on top of this all that still changes the route. `data-bypass` is a special attribute to tell Backbone app to not use its router. 
Similar functionality is already present for a `Button` component

Allow to use data-bypass for Nav.Item

---

src/components/MessageCard/MessageCard.css.js
src/components/MessageCard/MessageCard.jsx
src/components/MessageCard/MessageCard.stories.mdx
src/components/MessageCard/MessageCard.test.js

Related JIRA ticket: https://helpscout.atlassian.net/browse/BEMBED-235
Related figma: https://www.figma.com/file/JwgxQmv2KyQTKwoiuyxHGq/Spec%2F-Messages-1.5?node-id=0%3A1
We need to be able to display Image on the Message Card, below the body. There could be only one image per message at the moment. Image would be resized to the original size that it was uploaded with, and centered when width of image is smaller than width of message card.

Add support for image below Message body

---

src/components/ConditionField/ConditionField.AddButton.jsx
src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.Select.jsx
src/components/DropList/DropList.css.js
src/components/DropList/DropList.jsx
src/components/DropList/DropList.stories.mdx
src/components/DropList/DropList.test.js
src/components/DropList/DropList.utils.js

Sometimes when portaling you might need to apply some custom css to the menu but find that adding styles using Styled Components doesn't work (this happens because the styled component can't target the menu as it's no longer in its scope). In these rare ocasions you can use the `menuCSS` prop to add your styles, it accepts the returned value from the [`css` helper from Styled Components](https://styled-components.com/docs/api#css)
```jsx
// import { css } from 'styled-components'
<DropList
items={regularItems}
toggler={<SimpleButton text="Click" />}
tippyOptions={{
appendTo: () => document.body,
}}
menuCSS={css`
width: 134px;
&:hover {
color: salmon;
}
`}
/>
```
> Note: `menuCSS` should only be used in conjuction with `tippyOptions.appendTo`, if not you will see errors in the console. Use …

DropList: Adds menuCSS prop to allow custom css on the menu when portaling

---

src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.ListItem.jsx
src/components/DropList/DropList.Select.jsx
src/components/DropList/DropList.css.js
src/components/DropList/DropList.downshift.common.js
src/components/DropList/DropList.jsx
src/components/DropList/DropList.stories.mdx
src/components/DropList/DropList.test.js
src/components/DropList/DropList.utils.js
src/utilities/specs/dropdown.specs.js

Purpose of this PR is to allow users to disable items in a menu. The item would not be clickable, or selectable in any other way. Additionally, flag `isDisabled` would be available for a custom item renderer, so that user can easily style the item in this case.

Allow to disable item in a DropList

---

src/components/MessageCard/MessageCard.css.js
src/components/MessageCard/MessageCard.jsx
src/components/MessageCard/MessageCard.stories.mdx
src/components/MessageCard/MessageCard.test.js

The size of the MessageCard image is now set to be the size of original image. This approach has an issue that when the original image is really big, it would cause the Message UI to jump after loading image to adjust to the actually displayed size..
Because of that, it's necessary to recalculate the dimensions of an image so that it fits the given boundaries. Boundaries has been defined as a 278x278 square (based on the available width within a MessageCard). The image would keep aspect ration, independent if it wider or taller, adjusting to the longer side. The image container would be visible before image renders, as a transparent space, preventing the card to resize afterwards.
How it looked before: https://c.hlp.sc/YEuRPR4B (there's a short, but visible moment when the whole card gets …

Prevent MessageCard image from resizing

---

src/components/MessageCard/MessageCard.css.js

In one of the previous PRs I've changed the paddings inside a MessageCard component, but it turned out that there is a visual bug in certain use cases. I am changing them (almost) back here + proper adjustment to the styles of an image inside a Card.
The image would be pushed closer to the bottom border of a Card when it's the last item inside.
This PR relates to this JIRA: https://helpscout.atlassian.net/browse/BEMBED-266 and this PR: https://github.com/helpscout/hsds-react/pull/916

Fix MessageCard paddings

---

src/components/Attachment/Attachment.css.js
src/components/Attachment/Attachment.jsx

Currently it's not possible to navigate to remove button of an Attachment preview with keyboard. This PR adds a functionality to show remove button not only on hover, but also on focus. Additionally there's a change on how hiding of a button is done. Previously it was by setting `display:none;`, but this breaks the accessibility. Instead, the button is now clipped to no size and the clip is removed on hover/focus. 
The best way to test this change is to check `Attachment -> Preview theme` story and try tabbing to the attachment and a remove button.
See this recording: https://c.hlp.sc/ApuYg8ez

Improve accessibility of Attachment remove button

---

src/components/Input/Input.BackdropV2.css.js
src/components/Input/Input.stories.mdx

This update improves the focus styles for any input with a danger, success or warning state. It adds a second lighter border around the input.

Update state-based input focus styling

---

src/components/Avatar/Avatar.Image.jsx
src/components/Avatar/Avatar.css.js
src/components/Avatar/Avatar.jsx
src/components/Avatar/Avatar.test.js

**Issue**
The wrapper contain the initial as the title attribute, which overwrite the parent element one.
**Fix**
Since the prop was named `title`, it was spread on the `AvatarImage` component with the initials value. To fix the issue, we renamed `title` to `initials`. It makes more sense syntaxically and it will also prevent the component title to be changed by this props.

HSDS-188 Rename the `title` prop to `initials` in AvatarImage component

---

package-lock.json
package.json
src/components/ConditionField/ConditionField.test.js
src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.Select.jsx
src/components/DropList/DropList.jsx
src/components/DropList/DropList.test.js
src/components/EditableField/EditableField.Input.jsx
src/components/EditableField/EditableField.css.js
src/components/EditableField/EditableField.jsx
src/components/EditableField/EditableFieldComposite.jsx
src/components/EditableField/__tests__/EditableField.test.js
src/components/EditableField/__tests__/EditableFieldComposite.test.js
src/components/Modal/Modal.jsx
src/components/Modal/Modal.stories.mdx
src/components/PortalWrapper/PortalWrapper.jsx

In this PR we refactor EditableField (the options variant) to use DropList instead of Dropdown.
This does not change external behaviours so there's no need to update wherever is used (this variant of EditableField is only used on one place in HSApp by the way).
[Story](https://deploy-preview-921--hsds-react.netlify.app/?path=/story/components-forms-editablefield--with-options)
I also fixed a couple of EditableFields minor issues that I noticed:
- Propagate the disabled option all the way
- On multiple value fields with options, adding a new one and opening the options dropdown with the input empty would remove the newly added field.
While doing the refactor I noticed DropList has `onMenuBlur` but not focus, so I added `onMenuFocus` which I ended up not needing for the refactor but kept it …

[Refactor] Replaces usage of Dropdown in EditableField with DropList

---

package-lock.json
package.json

Helix was updated to the latest version of all packages (https://github.com/helpscout/helix/pull/31). The package was also updated to use a plain babel transpile instead of having both commonjs and es module
This update bring the latest from helix to HSDS. All tests are still passing, and the avatar 404ing is also fixed.

HSDS-189 Update helix to 0.2.0

---

src/components/MessageCard/MessageCard.jsx

MessageCard image's width and height can be either number or string. The code is prepared for this, but PropTypes have not been allowing numbers. This PR changes PropTypes to allow both.

Fixed prop types on MessageCard image width and height to avoid console error

---

src/components/CheckMarkCard/CheckMarkCard.css.js
src/components/Tooltip/Tooltip.jsx
src/components/Tooltip/Tooltip.stories.mdx
src/components/Tooltip/Tooltip.storiesHelpers.js
src/components/Tooltip/Tooltip.test.js

This update adds the `visible` props to the tooltip in case we need to entirely control the tooltip from the outside (that's the case with the Editor).
When this prop exists (just declared on the props object is enough) it will make sure to remove the `showOnCreated` and `trigger` list of props that will be passed down to Tippy.
Also, at the same time, we fixed a small color issue with the CheckmarkCard component.  We increase the color contrast for the subtitle.

Controlled Tooltip

---

src/components/CheckMarkCard/CheckMarkCard.css.js
src/components/CheckMarkCard/CheckMarkCard.test.js
src/components/DropList/DropList.downshift.common.js
src/components/DropList/DropList.test.js
src/components/DropList/DropList.utils.js

When navigating with up/down keys:
- It skips disabled items correctly
- Internally it "highlights" group labels and dividers, an action that doesn't show up because those items are unselectable, so you had to press the key again to actually go to the next selectable item.
- When going one up from the first selectable item, downshift correctly goes to the last item in the list (effectively looping), but going down from the last one was not taking you to the top of the list.
Adjust the `getEnabledItemIndex` function to take into consideration items that are group or dividers and ignore them, and also use a little bit of recursion in when we are the bottom of the list and press DOWN.

[DropList] Improves up down navigation with all type of items present in the list

---

src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.Select.jsx
src/components/DropList/DropList.css.js
src/components/DropList/DropList.downshift.common.js
src/components/DropList/DropList.jsx
src/components/DropList/DropList.stories.mdx
src/components/DropList/DropList.togglers.css.js
src/components/DropList/DropList.togglers.jsx

Continuing the replacement of Dropdown, found a few more things to improve:
- Cleaned up togglers file (moved all styled components into a css file)
- Adds 'is-active' class to all preset togglers
- Adds some options to `IconBtn` toggler (`withCaret`, `iconSize`, `caretSize`)
- Adds `a11yLabel` to togglers that are just icons so we can pass text that will not be rendered but readable for screen readers
- Adds the ability to enable Tooltip on icon-only togglers with the flag `withTooltip` using the `a11yLabel` text
- Adds `closeOnBlur` flag to DropList, mainly because is useful when debugging (so that the menu DOM Node can be inspectable on devtools)
- Improves the padding/margin of menu when there is only one item in the DropList

Adds some enhancements to DropList

---

src/components/CheckMarkCard/CheckMarkCard.css.js
src/components/CheckMarkCard/CheckMarkCard.jsx
src/components/CheckMarkCard/CheckMarkCard.test.js

Some weird issue came up within hs-app with circular import crashing the webpack loader. After investigation, we found out that extending the Avatar component within `CheckMarkCard.css` was the culprit. For some reason, extending the consumer was creating import issues. Maybe it's a difference between styled-component version between hs-app and HSDS, it is still unknown. 
To fix the issue, we import the Avatar directly within the  `CheckMarkCard` component and wrap it with a simple div to apply the needed margin

Fix the weird avatar import issue

---

src/components/ActionSelect/ActionSelect.jsx
src/components/ActionSelect/ActionSelect.test.js
src/components/DropList/DropList.togglers.jsx

The selection from props and state in `ActionSelect` was out of sync and used in a mixed manner:
- The state value was not set on mount (so it was being ignored)
- The state was being in one place and the prop value in another (causing the sync issue)
- The corresponding test while existing it was incomplete and so giving false positive
Also in the SplitButton toggler from Droplist, moved the classname from props to be applied to the root instead of the actual toggler button as it is a little more intuitive (you can target the toggler button with its own classname 'SplitButton__Toggler`)

Fixes selection and beefs up test for ActionSelect

---

src/components/Tooltip/Tooltip.jsx
src/components/Tooltip/Tooltip.test.js

In Tooltip component, there's `onShow` function that calls `setTimeout` with setting state inside. In most situations it works fine, but in case of ConditionField component, there's a tooltip used on `Remove` button. If you click it fast enough (before animation duration passed), then the component would be unmounted, but it would still try to set state after timeout, which results in a console warning about setting state on unmounted component, like this:
The solution is to save flag saying that component is mounted and do not set the state when this flag is false.
No new story has been added, but it can be checked on `Condition` story. Click `Remove` button next to `Specific URL` condition. It has to be done fast, before the tooltip has a chance to be displayed - just hovering over the …

Avoid setting state on unmounted Tooltip component

---

src/components/MessageCard/MessageCard.css.js
src/components/MessageCard/MessageCard.stories.mdx

Scrollabar on MessageCard body is a bit too close to the right edge of the whole Card. This moves it by to 2px to the left side, so there's more space. The scrollbars might be different depending on the browser and/or operating system.
Related JIRA issue: https://helpscout.atlassian.net/browse/BEMBED-281
There is a Story added that present MessageCard with a scrollbar - `MessageCard` -> `with body scrollbar`
Before:
After:

Move scrollbar on Message Card body a bit off from the right edge

---

src/components/DropList/DropList.stories.mdx
src/components/DropList/DropList.togglers.css.js
src/components/EditableField/EditableField.Input.jsx
src/components/EditableField/EditableField.jsx

Reported: Not committing email addresses when clicking away from email field if there is already 2+ emails attached
The issue happened on multiple value EditableFields, when more than one value alreaady present, adding a new one and then blurring would break.
While looking into it I found a similar but cause by different reasons bug in the multiple value with options fields, again blurring was broken:
- Check if the EditableFields is a multiple option field, and put a guard if not.
- Persist the `Event` coming from blur

[Bug] Fixes EditableFields bugs when blurring the inputs

---

src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.Select.jsx
src/components/DropList/DropList.constants.js
src/components/DropList/DropList.downshift.common.js
src/components/DropList/DropList.jsx
src/components/DropList/DropList.test.js
src/components/DropList/DropList.togglers.jsx
src/components/DropList/DropList.utils.js
src/components/EditableField/EditableField.Input.jsx
src/components/EmojiPicker/EmojiPicker.Toggler.jsx
src/components/EmojiPicker/EmojiPicker.jsx
src/components/Modal/Modal.jsx
src/components/Modal/Modal.stories.mdx
src/utilities/specs/dropdown.specs.js

1. When a DropList lives inside a Modal, pressing ESC should only close the DropList  and not the Modal, this was already handled for the Select variant, here we add the Combobox variant to the list
2. Reported by @plbabin:
> So if I tab to the trigger press enter then tab again, the dropdown closed. That’s fine, but then I need to press enter twice to get it to open once again
so the sequence I did:
tab (trigger is focused ) + enter (opened)+ tab (closed, trigger is focused) + enter (nothing happened) + enter (opened) 
That was happening due to some complex event sequences, here we add a keyDown handler besides the onClick handler to deal with them separately.
3. DropList  togglers now will get the `DropListToggler` classname applied to them automatically and merge the user toggler …

[Fix] DropList tweaks

---

src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.jsx
src/components/DropList/DropList.stories.mdx
src/components/DropList/DropList.test.js
src/components/DropList/DropList.togglers.css.js
src/components/DropList/DropList.togglers.jsx
src/components/DropList/DropList.utils.js
src/components/Tooltip/Tooltip.css.js
src/components/Tooltip/Tooltip.jsx

- In Chrome, when using a combobox, tabbing out of the input would take the focus all the way to the window chrome for some reason, so we prevent the default event on tabbing and do the action manually.
- Moving up/down on combobox when all items were filtered out (no results state) would throw an error and break everything
- "KebabButton" has been turned into "MeatButton" to allow having a "kebab" or a "meatball" button which are essentially the same.
- IconBtn and MeatBtn with tooltip enabled has been improved (to avoid tabbing into the actual tooltip trigger)
- A new Tooltip prop has been added `getTippyInstance` returns the Tippy instance

More DropList tweaks

---

src/components/DropList/DropList.utils.js

When a character key is pressed, downshift tries to scroll to an item that starts with that letter. If an item of type "divider" is present, tries to process it and crashes.
We add a guard here to stop downshift from processing items that are groups or dividers to prevent the crash

[DropList] Fix crash when a divider item type is present and you type a character

---

src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.Select.jsx
src/components/DropList/DropList.downshift.common.js
src/components/DropList/DropList.jsx
src/components/DropList/DropList.stories.mdx
src/components/DropList/DropList.test.js

Sometimes is useful to clear the selected item right after selecting it, for example a menu of actions that are performed on select (think of something like "attach file"), they shouldn't be shown as "selected" and you should be able to perform them again if wanted (normally a click on a selected item gets ignored if clicked again)

[DropList] Adds clearOnSelect ability

---

src/components/ActionSelect/ActionSelect.jsx
src/components/ActionSelect/ActionSelect.test.js

This PR adds possibility to disable ActionSelect DropList component, by passing new `disabled` prop to the toggler.
Additionally, ID can be provided to the toggler as well. This would help with accessibility so that it's possible to associate label with the DropList component.
Those changes are necessary for the new Messages app and should not affect any other usage

Allow ActionSelect component to be disabled and to provide ID

---

src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.Select.jsx
src/components/DropList/DropList.jsx
src/components/DropList/DropList.stories.mdx
src/components/DropList/DropList.test.js

> Copied from the addition I made to the docs for this feature:
In downshift item selection other than click is not handled directly on the list item nodes, in Select the events are handled on the Menu and in Combobox they are handled from the input. Because of this there is no access to any list item "event" on selection.
Most of the time you don't care _how_ the item was selected, but if you need to, you can use this callback where you'll find the `event` and get the `event.type`.
For this we have added `onListItemSelectEvent` which fires on any selection event (click, keydown). This callback gives you access to the actual List Item DOM node that was selected, and the original event.
The original click event will give you the actual list item, so `listItemNode === e.target`
Notice that …

Adds onListItemSelectEvent prop to DropList

---

src/components/DropList/DropList.jsx

@Charca reported: 
Whenever I open a dropdown, it scrolls me back to the top of the page. Any ideas why this might be happening? My usage of this component is quite simple:
```
<DropList
items={messageOptions}
toggler={
<MessageOptionsButtonUI
onClick={handleButtonClick}
a11yLabel="Message options"
/>
}
/>
```
https://c.hlp.sc/yAur5nZG
The issue is fixed by using `showOnCreate` instead of `visible` on the `<Tippy />` component. Don't ask me why though 😅

Fixes Droplist scrolling the document

---

package-lock.json
package.json
src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.Select.jsx
src/components/DropList/DropList.config.js
src/components/DropList/DropList.constants.js
src/components/DropList/DropList.downshift.common.js
src/components/DropList/DropList.jsx
src/components/DropList/DropList.stories.mdx
src/components/DropList/DropList.test.js
src/components/DropList/DropList.utils.js
src/utilities/pkg.js

By removing the usage of `visible` here https://github.com/helpscout/hsds-react/pull/957, we have another problem that the tippy is not getting removed from the DOM in some instances (we are only making it invisible).
Since `visible` is the only way react-tippy provides to [control the open/close state of the tippy](https://github.com/atomiks/tippyjs-react#visible-boolean-controlled-mode) (and we do want to control it) but continues to be buggy by scrolling the document we resort to manipulating the tippy instance instead.
While at it, I added a new prop `getTippyInstance` to retrieve the tippy instance in case you want to do stuff with it. This prop exists in Tooltip too so might aswell have it here too.

DropList fix > manipulate tippy instance manually to show and hide

---

babel.config.js

While working on some performance improvements on the Beacon embed-side, we discovered that version v3.12.0 of hsds-react increased our overall bundle size by about 10% for no apparent reason. After some investigation, we found out that changing the `@babel/preset-env` `loose` setting to false, caused built assets to include a bit more code than before, adding some extra functions and variables during build time.
I don't think this `loose` setting has any impact on functionality, so this should be a pretty low-risk change. Also, I didn't change the setting in the Babel config used by Storybook because it didn't seem to have an effect, and leaving it as `true` gets rid of some warnings caused by Storybook plugins.

Updated babel's preset-env loose mode to reduce component bundle size

---

src/components/Avatar/Avatar.css.js
src/components/Avatar/Avatar.jsx
src/components/Avatar/Avatar.test.js
src/components/AvatarList/AvatarList.css.js
src/components/AvatarList/AvatarList.jsx
src/components/AvatarList/AvatarList.stories.mdx
src/components/AvatarList/AvatarList.test.js

The spec has these Avatars being 38px, but the closest we have is 35px for "smmd". This PR updates to 38px for consistency but we need design to OK this, if not either make them all 35px or add yet another size to the list:
```js
// all sizes
{
xl: {
size: 64,
fontSize: 13,
},
lg: {
size: 52,
fontSize: 13,
},
md: {
size: 46,
fontSize: 13,
},
smmd: {
size: 38, // <-- This was 35
fontSize: 15,
},
sm: {
size: 30,
fontSize: 10,
},
xs: {
size: 28,
fontSize: 10,
},
xxs: {
size: 26,
fontSize: 10,
},
},
```
AvatarList has an option to stack, using the `stack` prop, this prop used to be a boolean but I searched in our projects and is not being used at all, so I changed it to be either 'horizontal' or 'vertical'. Horizontal behaves just like it used to if `stack === true`.
When we limit the number …

[Feature] AvatarList: Adds vertical stack option + Tooltip

---

src/components/EditableField/EditableField.css.js
src/components/EditableTextarea/EditableTextarea.storiesHelpers.js

The validation icon is positioned too close to the border bottom.
Update the `position`, instead of `top` use `bottom`:
One line:
Multiple lines:

[Fix] EditableTextArea: updates validation icon position

---

package-lock.json
package.json

This really is unused and it makes VSCode behave in a very annoying manner when jumping to definition using cmd+click on your own authored styled components.
Context: https://github.com/microsoft/vscode/issues/68782

Removes @types/styled-components

---

src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.ListItem.jsx
src/components/DropList/DropList.Select.jsx
src/components/DropList/DropList.constants.js
src/components/DropList/DropList.css.js
src/components/DropList/DropList.downshift.common.js
src/components/DropList/DropList.jsx
src/components/DropList/DropList.stories.mdx
src/components/DropList/DropList.test.js
src/components/DropList/DropList.togglers.jsx
src/components/DropList/DropList.utils.js
src/components/Table/Table.ColumnChooser.jsx
src/components/Table/Table.css.js
src/components/Table/Table.test.js
src/components/Table/Table.utils.js

https://helpscout.atlassian.net/browse/HSDS-205
To enable this [workflow](https://helpscout.atlassian.net/browse/HSAPPUI-137):
When there are no items either on the initial mount of the DropList or when in combobox mode we filter down to 0 results.
➡️
We want to show "extra" items, that enables us to perform some action
For this, we add the new prop `customEmptyListItems` which accepts an array of items, any item that is accepted by DropList is valid here.
> `customEmptyList` still exists, this customizes the rendering of an empty list, use this if what you need is to display something static
```jsx
customEmptyListItems={[
{
label: 'No tags found',
type: 'inert',
},
{
type: 'divider',
},
{
label: 'Create tag',
type: 'action',
},
]}
```
On a combobox, you can customize the label of your …

[HSDS-205] DropList features

---

src/components/ActionSelect/ActionSelect.jsx
src/components/ActionSelect/ActionSelect.test.js

Goal of this change is to allow to provide error message to the Action Select component, so that DropList is marked with an error state. Additionally, I've parameterized aria-label attribute.
There is no functionality change.

Allow to provide Error message to ActionSelect component

---

src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.Select.jsx
src/components/DropList/DropList.css.js
src/components/DropList/DropList.jsx
src/components/DropList/DropList.test.js
src/components/DropList/DropList.utils.js
src/components/Popover/Popover.css.js
src/components/Popover/Popover.jsx
src/components/Popover/Popover.stories.mdx
src/components/Popover/Popover.test.js
src/components/Tooltip/Tooltip.jsx
src/components/Tooltip/Tooltip.storiesHelpers.js
src/components/Tooltip/Tooltip.test.js

https://helpscout.atlassian.net/browse/HSDS-211
Adds the `withArrow` (default `true`) prop to be able to render without it.
PopOver's styles get update to use depth.500
https://helpscout.atlassian.net/browse/HSDS-212
The initial desire of not deviating too much from the original design of the DropList menu made us make the choice of making it a bit difficult to customize some things, including the width of the menu.
I've noticed almost everywhere that is used, this is the first thing that gets overridden... 🙈
So might as well add the prop 🤷‍♀️
I introduce you `menuWidth`

Some tweaks on PopOver, Tooltip and DropList

---

package-lock.json
package.json
src/styles/configs/colorway.js

This update adds two new color to the palette: `green.650` and `yellow.950`. We introduce those two blended shades to improves our accessibility effort across all application. They will be used to increase readability on a green or yellow background.

Upgrade colorway to 0.9.7

---

src/components/AvatarRow/AvatarRow.jsx
src/components/AvatarRow/AvatarRow.stories.mdx
src/components/AvatarRow/AvatarRow.storiesHelpers.js
src/components/AvatarRow/AvatarRow.test.js
src/components/AvatarRow/AvatarRow.utils.js

Adding or removing avatars is not supported. The ResizeObserver callback gets binded on mount and needs to be re-done if the number of avatars change.
- Add the number of avatars to the useEffect hook so that the `onResize` gets updated if that number changes
- Make sure not to add multiple ResizeObservers by holding on to values with a `ref`
https://deploy-preview-986--hsds-react.netlify.app/?path=/story/components-structural-avatarrow--dynamic-number-of-avatars
- Remove ie compat mode, will re add if necessary
- Refactor the onResize fn to be able to test easily (jsdom does not support ResizeObserver)

AvatarRow: dynamic number of avatars

---

src/components/Pagination/Pagination.jsx

While testing hs-app with the  refactored pagination, we realized that it was not possible to overwrite some props from the parent component.
This update move the location of `getValidProps` after `data-testid`, `role` and `aria-label`. That way the parent component will be able to change the value of those props _if needed_

Allow component props to overwrite pagination attributes

---

src/components/Tag/Tag.css.js

An update on focusRing in another PR broke the border-radius on the tag remove icon, making it square. 
We added a border-radius value to the container element, that way the `focusRing` will be rounded with the same value as the parent.

Fix tag remove icon border-radius

---

src/components/Modal/Modal.stories.mdx
src/components/Modal/Modal.storiesHelpers.js
src/components/PortalWrapper/PortalWrapper.jsx
src/components/PortalWrapper/PortalWrapper.test.js

Relates to: https://helpscout.atlassian.net/browse/CTRIAGE-2697
There was a bug that trigger element of a Modal has be re-focused when `isOpen` state value is false and if any property has changed. This is causing some issues with a Beacon message form. Follow the steps to reproduce:
- Go to docs.helpscout.com and click the Contact Us button to open the Beacon
- Start typing a message into the main body text area
- Add an image attachment
- Try editing the message - as soon as you start typing, focus moves to the "1 file" button and you can't type any more
This happens because the button for files is a trigger and we don't have modal opened. The implementation was lacking a check if the portal has been opened before, so we re-trigger when it is closed. Adding the check solves the problem. …

Fix portal trigger to not re-focus when unrelated props changed [BEMBED-305]

---

src/components/Condition/Condition.jsx
src/components/Condition/Condition.test.js

This PR improves aria-label attribute for Condition -> DropList SelectTag toggler, to add currently selected item.
Additionally, `ariaDescribedBy` property has been added to allow to set additional description for this field.
Both changes are necessary to fix accessibility issues in Messages app.

Improve accessibility for Condition Select element

---

src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.jsx
src/components/DropList/DropList.test.js

For the DropList used for the Tags menu in the convo redesign, we want to alter the elements displayed based on whether the search input has a value ([Jira](https://helpscout.atlassian.net/browse/HSAPPUI-303)). This PR adds an `onInputChange` callback to allow for that as recommended by @tinkertrain [here](https://github.com/helpscout/hs-app-ui/pull/192#issuecomment-964051693)

HSAPPUI-310: Add onInputChange callback to DropList

---

package-lock.json
src/components/Icon/Icon.jsx
src/components/Table/Table.Cell.jsx
src/components/Table/Table.HeaderCell.jsx
src/components/Table/Table.Row.jsx
src/components/Table/Table.css.js
src/components/Table/Table.jsx
src/components/Table/Table.skins.js
src/components/Table/Table.test.js
src/components/Table/Table.testUtils.js
src/components/Table/Table.utils.js
src/components/Table/stories/Table.stories.mdx
src/components/Table/stories/TableWithSorting.js

Some updates to the styles have been requested, mostly regarding the Header Row:
Most of the changes will just happen but we did add a couple of convenience things:
1. `renderHeaderCell` has always been available to render icons (or whatever), since icons can be a common occurrence and to avoid each developer having to implement the right styles, you can now pass an object with a key `iconName`, and that's it:
```js
// example column
{
title: 'Company',
columnKey: 'companyName',
align: 'center',
width: '35%',
renderHeaderCell: { iconName: 'chat' },
sorter: this.sortAlphabetically,
},
```
2. Previously, if the table was sortable and `renderHeaderCell` was passed, the markup was incorrect, this is fixed now.
3. If the table is sortable, it gets the class name: `is-sortable` 
4. Removes the …

Table: Updates styles to latest (header row)

---

src/components/ScrollableContainer/ScrollableContainer.css.js
src/components/ScrollableContainer/ScrollableContainer.jsx
src/components/ScrollableContainer/ScrollableContainer.test.js
src/components/SidePanel/SidePanel.layouts.jsx
src/components/SidePanel/SidePanel.storiesHelpers.js
src/components/SimpleModal/SimpleModal.css.js
src/components/SimpleModal/SimpleModal.jsx
src/components/SimpleModal/SimpleModal.layouts.css.js
src/components/SimpleModal/SimpleModal.layouts.jsx
src/components/SimpleModal/SimpleModal.stories.mdx

In order to start using `SimpleModal` instead of `Modal` we create the first layout: "HeaderAndFooter". The pattern is the same as what we started with `SidePanel`, instead of adding several props to get a spedific modal type, we provide some ready-to-use components to drop inside the modal.
In this PR we add one of the most commonly used layouts, the one that has:
1. A fixed at the top header
2. A scrollable body
3. A fixed at the bottom footer
Like this one:
Usage is better explained with some code:
```jsx
import SimpleModal from '@helpscout/hsds-react/SimpleModal'
import Button from '../Button'
import { HeaderAndFooter } from '@helpscout/hsds-react/SimpleModal/SimpleModal.layouts'
<SimpleModal>
<HeaderAndFooter
withSimpleBar // all `ScrollableContainer` props are accepted in this …
```

SimpleModal layout: header and footer

---

package-lock.json
package.json
src/components/CheckMarkCard/CheckMarkCard.jsx
src/components/CheckMarkCard/CheckMarkCard.stories.mdx
src/components/CheckMarkCard/CheckMarkCard.test.js
src/components/ChoiceGroup/ChoiceGroup.jsx
src/components/ChoiceGroup/ChoiceGroup.test.js
src/components/SimpleModal/SimpleModal.stories.mdx
src/components/SimpleModal/SimpleModal.storiesHelpers.js
src/utilities/focus.js

In this PR two things has been change, all related to issues found in Messages app: https://github.com/helpscout/hs-app-ui/pull/209
There was an issue that if container was focused, for example SimpleModal, and user pressed Shift+Tab, the focus was moved to the previous element in the DOM, not witihn the container, even if `trapFocus` was set to true.
The fix here is to always move within container, even if it is the one focused.
To test this, I have create `SimpleModal` -> `with trigger` story that would open and focus modal once the button is clicked.
If ChoiceGroup was used with `multiSelect={false}` and children are `Checkboxes` (or variant of them) - then clicking the same item twice was de-selecting on the UI, but clicked third time was not selecting it again. The reason being that …

trapped focus and ChoiceGroup fixes

---

src/components/ChoiceGroup/ChoiceGroup.jsx
src/components/ChoiceGroup/ChoiceGroup.test.js

This PR lets user deselect `ChoiceGroup` item (Checkbox or a variant) via pressing Enter or Space when in single select mode.
To test this, use `CheckMarkCard` -> `inside group` story, change Knobs to deselect `multiSelect` option. Then use your keyboard to select and deselect (and select again) some item.

Allow deselecting ChoiceGroup item via Enter/Space keypress

---

src/components/Avatar/Avatar.Image.jsx
src/components/Avatar/Avatar.test.js

This PR improves Avatar to call `onLoad` callback in constructor for case that image is already in cache (so regular onLoad after fetching image would not be fired).
The use case for that is in Messages app where we need to perform some action when image is loaded and can be rendered. 

Call onLoad for Avatar in constructor, when image already in cache

---

src/components/Choice/Choice.Input.jsx
src/components/Choice/ChoiceInput.test.js

This PR fixes a bug introduced in one of the previous PRs (https://github.com/helpscout/hsds-react/pull/1007). The problem was that it was not possible to select Radio item inside a group using space or enter keys.
To test that it works, go to `Radio` -> `In a group` story and try using enter/space to select item.

Fix enter/space keypress for Radio input

---

src/components/MessageCard/MessageCard.css.js
src/components/MessageCard/MessageCard.jsx
src/components/MessageCard/MessageCard.stories.mdx
src/components/MessageCard/MessageCard.test.js
src/components/MessageCard/components/MessageCard.Body.jsx
src/components/MessageCard/utils/MessageCard.utils.js
src/components/MessageCard/utils/MessageCard.utils.test.js

[JIRA](https://helpscout.atlassian.net/browse/HSDS-229)
This PR adds support for highlighting variables in a MessageCard. Variables are provided via props, so this is not connected to any specific available variables, but whatever would be needed.
Design: https://www.figma.com/file/H2oEYNwn2RMpSVSR94B2vB/Spec%2F-Variable-Support-in-Messages?node-id=34%3A6520
I initially though about implementing just some utility function that is exported and can be used whenever needed. Main reason for this being re-usability, customization (can use different transformation if necessary) and the fact that it is not needed in Beacon Embed, so to not add additional size. 
However, I thought about it again and decided to, at least for now, just include implementation inside MessageCard component. Reason for …

HSDS-229: MessageCard body variable transformer

---

src/components/Accordion/Accordion.Body.jsx
src/components/Accordion/__tests__/Accordion.Body.test.js
src/components/Collapsible/Collapsible.jsx
src/components/Collapsible/Collapsible.test.js
src/components/SidePanel/SidePanel.layouts.jsx

For one case in Messages app we'd like to use Accordion component for it's functionality. However, we need the content of the Accordion Body to be rendered, because some background operations need to be performed, even if Accordion is closed. Currently the content is conditionally not rendered in `Collapsible` component (until opened)
This PR adds a new flags to `Accordion.Body` and `Collapsible` components so that the content would be rendered to the DOM. It is still hidden from user, but React lifecycle would fire for them.
I've not added any story for that, but there are tests confirming it works as expected.

Allow Collabsible/Accordion.Body content to be pre-rendered

---

src/components/MessageCard/utils/MessageCard.utils.js
src/components/MessageCard/utils/MessageCard.utils.test.js

This small PR fixes regex used for finding variables to highlight in MessageCard body so that it's possible to include % sign in fallback. There are tests added/adjusted to cover previously failing cases

Fix Message Card variable regex so that it's possible to include % sign in fallback

---

src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.Select.jsx
src/components/DropList/DropList.jsx
src/components/DropList/DropList.stories.mdx
src/components/DropList/DropList.test.js
src/components/DropList/DropList.utils.js
src/components/Table/Table.HeaderCell.jsx
src/components/Table/Table.css.js
src/components/Table/Table.test.js
src/components/Table/stories/Table.stories.mdx
src/components/Table/stories/TableWithSorting.js

In the example above I made the container focusable to demonstrate a couple of things happening:
- When tabbing out of the DropList, for a brief moment it focuses the container, and then focuses back on the toggler.
- Not only is jarring, but the behaviour of focusing back on the toggler is not standard, it should focus on the next focusable element.
Change the way we manage focus, a lot of the complexity was because of `onDropListLeave` which we want to fire when the DropList is left, whether is by clicking outside, blurring the toggler, etc.
- Use a combination of memoization and debouncing instead of a special utility with a timeout to avoid the `onDropListLeave` callback to fire multiple times 
- Focus the next focusable element when tabbing out of DropList instead of trying to keep …

DropList focus enhancements

---

src/components/Choice/Choice.Input.jsx
src/components/Choice/Choice.jsx
src/components/Choice/Choice.test.js

This small PR fixes a11y issue on Choice component (used inside Checkbox). When `helpText` attribute is provided, previously it was set as `aria-describedby` attribute. However, this attribute should receive ID of an element.
The change here is to assign ID (based on ID of Choice element) to `Help Text` div and use this id for `aria-describedby` attributes in `input`

Fix aria-describedby attribute on Choice component to use id, not raw text

---

src/components/Choice/Choice.jsx
src/components/Choice/Choice.test.js

This PR fixes previous fix (:facepalm:) - `aria-describedby` should not be set on Choice input if there's no helpText.

Do not set aria-describedby on Choice input when no helpText

---

src/components/Tag/Tag.css.js
src/components/Tag/Tag.jsx
src/components/Tag/Tag.test.js

To apply a tooltip correctly to the `Tag`, we had to refactor the component to use `forwardRef`.
We were able to remove the tagRef use internally. Seems that it was not needed anymore to validate the animation was on the correct element.
At the same time, we fixed an issue with the focus ring tag radius and also improve the `X` button placement (so that the focus ring doesn't overlap the tag content)

Tag forwarded ref

---

package.json
src/components/Frame/Frame.jsx
src/components/Popover/Popover.jsx
src/hooks/useMeasureNode.js

@nickolas described it [here](https://github.com/helpscout/hs-app-ui/pull/283#issuecomment-1043441561).
In a nutshell Safari does not support ResizeObserver fully yet, so AvatarRow and any other things that use it don't work as expected.
In this PR we add the polyfill [`@juggle/resize-observer`](https://github.com/juggle/resize-observer) to be used _only_ on Safari. We can remove it when Safari supports RO properly (allegedly v15.4 which is coming soon).
[🎥 Little demo in safari](https://i.hlp.sc/j7p6Qz)
--
We also include this https://github.com/helpscout/hsds-react/pull/1034 by @jakubjanczyk

Adds ResizeObserver polyfill to use on Safari

---

src/components/VerificationCode/VerificationCode.css.js
src/components/VerificationCode/VerificationCode.jsx

This PR fixes two a11y issues in the Verification Code component
1 [Scrollable region must have keyboard access](https://dequeuniversity.com/rules/axe/4.4/scrollable-region-focusable?application=AxeChrome) (Impact: Moderate) : set overflow attribute to hidden for ClipboardPlaceholderUI
2 [Form elements must have labels](https://dequeuniversity.com/rules/axe/4.4/label?application=AxeChrome) (Impact: Critical) : Add aria-labellby to input

Add label to Verification Code input and make unfocusable region not scrollable

---

src/components/Table/Table.jsx

It is currently not possible to dynamically change the columns of a table because the state does not update when the props change. This small change ensures that the columns state stays in sync with the columns prop.
This was needed to support changing Mailbox views. When we change views, we load new conversations that get loaded into the table as rows; however we also need to change the columns to show based on the view. See https://github.com/helpscout/hs-app-ui/pull/319 for more context.

Allow table columns to be changed

---

package-lock.json
package.json
src/components/DropList/DropList.Combobox.jsx
src/components/DropList/DropList.ListItem.jsx
src/components/DropList/DropList.jsx
src/components/DropList/DropList.stories.mdx
src/components/DropList/DropList.test.js
src/components/DropList/DropList.utils.js
src/utilities/pkg.js

Story: https://b87ad319.hsds-react.pages.dev/?path=/story/components-dropdowns-droplist--with-action-item
1. When filtering, do not remove the action item
- Divider: keep it if there are items left (besides the action), remove it if only the action left
2. Leave groups if not empty after filtering
New: 
1. Add a `template` key to your action item if you would like update the action item label with the input value, the special placeholder `__inputValue__` will be replaced with the input value.
```jsx
const actionItem = {
label: 'Add tag',
template: 'Add __inputValue__ tag',
type: 'action',
action: 'ADD_TAG',
}
// ....
<DropList
onSelect={(selection, clickedItem) => {
if (clickedItem.type === 'action') {
console.log('add tag clicked, do something!')
// `clickedItem` will include the updated …
```

DropList combobox new features HSDS-252

---

src/components/Tag/Tag.jsx
src/components/Tag/Tag.stories.mdx

In the beautiful CC/BCC implementation that @plbabin did for the mailbox rewrite, we're using the Tag component as a badge to represent the email address. [During accessibility review](https://github.com/helpscout/hs-app-ui/pull/351), we found it would be best to be able to customize the label, since it reads "Remove Tag" but in this context there isn't a tag. This adds a prop to be able to set the aria-label and test ID of the removal element to a different value:

Add custom remove label option to Tag component

---

package-lock.json
package.json
src/components/PortalWrapper/PortalWrapper.jsx
src/utilities/pkg.js

We've started using Preact in Beacon Embed for lighter bundle size and better performance. It's in most part compatible with React, so a lot of things work the same. However, there apparently is one difference we've noticed.
If there is a Portal created from within another Portal, the rendering to the DOM is very "transactional", meaning that some intermediate states are not being flushed to the DOM. In our case the issue is with Animate component, and the fact that intermediate `entering` state is not rendered, but it goes straight to rendering `entered` state. Because of that animations are not working - there is not change to the styles as seen from the DOM/browser perspective.
I am not 100% sure what is the exact issue, it might be some combination of Animate, PortalWrapper and Modal. …

Delay PortalWrapper content render

---

src/components/SidePanel/SidePanel.test.js
src/components/SimpleModal/SimpleModal.storiesHelpers.js
src/components/SimpleModal/SimpleModal.test.js
src/hooks/useClickOutside.js

There are cases when an element inside a modal is no longer there byt the time `useClickOutside` decides whether to execute the callback, making the check always true and so, executing the callback when it shouldn't.
Add an extra check: make sure the element clicked is visible to then execute the callback.
Added a test case in the story: https://1713afae.hsds-react.pages.dev/?path=/story/components-overlay-simplemodal--with-trigger-and-nested
1. Open the modal
2. Click the green button, it will get removed and the modal stays open (whereas previously it was closing it)
3. Clicking outside the modal, closes the modal

useClickOutside hook fix

---

package-lock.json
package.json
src/components/DropList/DropList.css.js
src/components/Modal/Modal.jsx
src/components/Modal/Modal.storiesHelpers.js
src/components/SidePanel/SidePanel.jsx
src/components/SimpleModal/SimpleModal.jsx
src/components/SimpleModal/SimpleModal.storiesHelpers.js
src/components/SimpleModal/SimpleModal.test.js
src/components/SimpleModal/SimpleModal.utils.js
src/components/Tooltip/Tooltip.css.js

[Jira ticket](https://helpscout.atlassian.net/browse/HSDS-263)
Keyboard events originating when the Simple Modal was displayed were leaking out onto the page, causing page keyboard shortcuts to be triggered. 
1. Stop propagation of key and click events from the modal
2. Add a `blocksGlobalHotkeys` prop to SimpleModal (and SidePanel) that will add a data attribute that external hooks or events can look for to perform or not a certain action when a modal is present
1. When having multiple modals on screen outside clicks were being firing 'onClose' for every modal, we added scenarios were we don't want this to happen, for example if having 2 modals open, and we click outside the modal on top, we only want to fire the onClose for that one, not the underneath one.
1. Tooltip: removed some …

Capture all keyboad originating in Simple Modal

---

src/components/HSDS/GlobalStyle.js

The CSS reset seems to be working great and didn't break anything.....jk 😅 😹 ! Here's what the Messages blank slate looked like for a little while (now fixed):
The CSS reset blew things up because the `height` and `width` got passed as props to the `Image` component, which means that they're set as attribute properties directly on the image. i.e. this
```
function renderExampleMessageImage() {
return (
<Fragment>
<ExampleMessageImageUI
height="412"
src={getImagePath('example-message.png')}
title="Example Message"
width="315"
/>
</Fragment>
)
}
```
Renders as this HTML:
```
```
Because `width` and `height` attributes in images and iframes have (thanks for the link @Charca) [the weakest specificity of all](https://css-tricks.com/whats-the-difference-between-width-height-in-css-and-width-heig …

Don't CSS reset img and svg width and height

---

src/components/CheckMarkCard/CheckMarkCard.css.js
src/components/CheckMarkCard/CheckMarkCard.jsx
src/components/CheckMarkCard/CheckMarkCard.stories.mdx
src/components/CheckMarkCard/CheckMarkCard.test.js

To support the work in an upcoming project, we had to implement some changes to the disabled state of the CheckmarkCard:
We removed all shadows and set a grey background (`grey.200`). Avatar is faded out and the heading/subtitle color are slightly lighter
By passing a cardTooltipText prop to the CheckmarkCard, a tooltip will appear on focus/mouseover. The tooltip will still work when the card is disabled
we migrate the component to use the `focusRing` mixin for both the card and mark component. It simplifies the code but nothing should have change visually

HSD- 261 Update CheckmarkCard disabled UI

---

package-lock.json
package.json
src/components/MessageCard/MessageCard.stories.mdx
src/components/MessageCard/MessageCard.test.js
src/components/MessageCard/components/survey/MessageCard.Survey.MultipleChoice.jsx
src/components/MessageCard/components/survey/MessageCard.Survey.css.js
src/components/MessageCard/components/survey/MessageCard.Survey.jsx
src/utilities/pkg.js

This PR fixes some issues found for Messages survey components:
- Color of submit button was always blue, it should be using the current theme instead
- Text for submit button was not truncated
- The animations/transitions when selecting thumb/face was a bit clunky - I had to delay (optionally) showing confirmation form after selecting an option, so that the animation for option finishes before. I also added some height animation to the form itself for nicer entry

Fix survey issues

---

src/components/MessageCard/MessageCard.css.js
src/components/MessageCard/components/survey/MessageCard.Survey.css.js

This PR makes some improvements to focus state of faces/thumbs option for Messages survey components. They are not behaving in the same way and all have blue focus ring when navigating through keyboard. This improves the accessibility of those components.

Improve focus states for Messages survey components

---

src/components/SimpleModal/SimpleModal.layouts.jsx

The button handlers were connected in reverse:
- The `onCancel` handler was connected to the "Confirm" button.
- The `onConfirm` handler was connected to the "Cancel" button.
This pull request is a small change to flip the usage of the button handlers:
- The `onCancel` handler is connected to the "Cancel" button.
- The `onConfirm` handler is connected to the "Confirm" button.
That's it!
Adds 2 props `cancelButtonProps` and `confirmButtonProps` to pass any valid Button prop to each button.

SimpleModal (confirmation layout): Swap which buttons handlers are applied to

---

src/components/MessageCard/MessageCard.css.js

This PR updates the padding-top of the MessageCard component from 17px to 20px so that it is consistent with other spacing. 

HSDS-267: Update MessageCard Padding

---

src/components/MessageCard/components/survey/MessageCard.Survey.css.js

This PR changes line-height of multiple choice radio option, in case if there are 2 rows of text. Before it was looking a bit weird, too stretched
Before:
After:

Change line height for Message Survey multiple choice option

---

src/components/MessageCard/components/survey/MessageCard.Survey.css.js

This PR fixes the margin on Messages microsurvey emojis (faces and thumbs). Previously there was unnecessary left padding.
Other thing is label text alignment to the center on microsurvey comment textarea.
See related PR comment: https://github.com/helpscout/hs-app-ui/pull/527#issuecomment-1167832054
To test it, open `MessageCard` in storybook and then `With Thumbs survey` and `With Faces survey` to see it looks ok now :)

Fix margin on microsurvey emojis and comment label alignment

---

src/components/Table/Table.Head.jsx
src/components/Table/Table.HeaderCell.jsx
src/components/Table/Table.css.js
src/components/Table/Table.jsx
src/components/Table/Table.test.js
src/components/Table/stories/TableWithSorting.js

We add a new table prop `tableRole` which changes the `role` attribute of the table element for special cases that require it.
When we change this attribute to something other than "table", we also make other attribute changes (in sortable tables)
- `th` no longer get the `aria-sort` attribute set
- Instead we add a `aria-label` attribute on the button inside the `th`, that reads "Sorted {columnName} name {order}" for example: "Sorted by name ascending"
We also adjust the row border focus from 2px to 3px
And we update all table tests to use testing-library

Table: adds the ability to change the table role

---

src/components/MessageCard/MessageCard.Survey.variants.js
src/components/MessageCard/MessageCard.stories.mdx
src/components/MessageCard/components/survey/MessageCard.Survey.Emoji.jsx
src/components/MessageCard/components/survey/MessageCard.Survey.Emoji.test.js
src/components/MessageCard/components/survey/MessageCard.Survey.css.js

**Note:** This PR is a copy of https://github.com/helpscout/hsds/pull/3 adapted for hsds-react.
This PR adds a new `EmojiSurvey` variant to the `MessageCard` component. This component will be used by the Messages Builder in hs-app-ui and Beacon.
- [Direct Link](https://hsds-257-emoji-survey.hsds-react.pages.dev/?path=/story/components-conversation-message-messagecard--with-emoji-survey)
- Open the Storybook Deploy Preview
- Navigate to the MessageCard component and select the "With Emoji survey" variant.

HSDS-257: Add MessageCard Emoji Survey variant

---

package-lock.json
package.json
src/components/MessageCard/MessageCard.stories.mdx
src/components/MessageCard/MessageCard.test.js
src/components/MessageCard/components/survey/MessageCard.Survey.css.js
src/components/MessageCard/components/survey/MessageCard.Survey.jsx
src/utilities/pkg.js

**Note:** This PR is a copy of https://github.com/helpscout/hsds/pull/6 adapted for hsds-react.
This PR adds support for Freeform Text surveys. Unlike other survey types, this is not a variant. The functionality for submitting text responses was already part of the `MessageCard.Survey` component, so I've simply added a new `isTextOnlySurvey` prop to enable it by default as well as adjusting some styles.
- [Direct Link](https://hsds-277-message-card-text-s.hsds-react.pages.dev/?path=/story/components-conversation-message-messagecard--with-text-survey)
- Open the Storybook Deploy Preview
- Navigate to the MessageCard component and select the "With Text survey" variant.

HSDS-277: Support for Freeform Text Survey 
