package-lock.json, src/components/Icon/icons.js, src/icons/arrow-left.svg, stories/Icon.js
* Add `arrow-left.svg` file
* Add `arrow-left` to `icons.js`
Resolves: https://github.com/helpscout/blue/issues/9
=> Add arrow-left (or "Back") arrow

scripts/test.js, src/index.js
This update adds the handful of useful util functions into the main `index.js`, allowing user/consumers of Blue to use them func! 🎉
=> Add utilities to main index.js

package-lock.json, src/components/Animate/index.js
Rename from `animate` -> `Animate`
https://github.com/helpscout/blue/issues/35
=> Fix Animate animation className

.storybook/addons.js, .storybook/config.js, package.json, stories/Button.js, stories/Modal.js, stories/Overlay.js, stories/Select.js, stories/addons/prettyDocs/components/Story.js, stories/addons/prettyDocs/index.js, yarn.lock
This PR updates the storybook deps to newer versions. I've also added `addon-options` to customized the header a bit.
Originally, I was going to try to transform our storybook into more of a styleguide. However, Storybook's addons (or lack of addons) is making this difficult.
Ideally, I want the styleguide to be:
a. as automated as possible
b. not terrible to use/read/understand
A potential solution is:
https://github.com/styleguidist/react-styleguidist
However, there are limitations and annoyances with that as well.
=> Storybook: Update Deps

src/components/Card/Block.js, src/components/Card/index.js, src/components/Card/tests/Card.Block.test.js, src/components/Card/tests/Card.test.js, src/styles/components/Card/Card.scss, src/styles/components/Card/CardBlock.scss
Resolves https://github.com/helpscout/blue/issues/66
=> Rename Card className from c-card to c-Card

src/components/InfiniteScroller/index.js, src/components/InfiniteScroller/tests/InfiniteScroller.test.js, src/components/LoadingDots/README.md, src/components/LoadingDots/index.js, src/components/LoadingDots/tests/LoadingDots.test.js, src/styles/components/LoadingDots.scss, stories/LoadingDots.js
This update adds an `align` prop to the LoadingDots component, allowing it to align to the `left`, `center`, and `right`.
InfiniteScroller has also been adjusted so that the LoadingDots align `center` by default.
=> LoadingDots: Add alignment styles

src/components/AnimateGroup/README.md, src/components/AnimateGroup/index.js, src/components/AnimateGroup/tests/AnimateGroup.test.js, src/components/InfiniteScroller/index.js, src/components/index.js, src/styles/components/Modal.scss, src/tests/index.test.js, stories/InfiniteScroller.js
This update enhances the InfiniteScroller component to "normalize" the scrollNode when the onLoaded callback fires.
The InfiniteScroller Story has also been updated to better showcase the InfiniteScroller component being used inside/outside of a Modal.
**Other updates**
* AnimateGroup component has been added (a convenient alias for TransitionGroup from react-transition-group)
=> InfiniteScroller: Improve scroll position onLoaded

src/components/Modal/index.js, src/components/Modal/tests/Modal.test.js, src/styles/components/Modal/Modal.scss, src/styles/components/Modal/ModalBody.scss
This update resolves some of the integration issues we saw from
integrating it into Beacon. Tests were added to catch those
edge-cases.
Follow-up to https://github.com/helpscout/blue/pull/155
=> Modal: Body - Fix logic and styles

src/components/Icon/propTypes.js, src/components/Icon/tests/Icon.test.js, src/styles/components/Icon.scss
This update adds size '13' to Icon.
=> Icon: Add size 13

src/components/Animate/index.js, src/components/Collapsible/tests/Collapsible.test.js, src/components/Overflow/index.js, src/components/Overflow/tests/Overflow.test.js, src/components/Scrollable/index.js, src/components/Scrollable/tests/Scrollable.test.js, src/styles/blue.scss, src/styles/components/Button.scss, src/styles/components/ChatList/ChatListItem.scss, src/styles/components/Input/Input.scss, src/styles/components/Input/InputField.scss, src/styles/components/Modal/Modal.scss, src/styles/components/Modal/ModalBody.scss, src/styles/components/Modal/ModalContent.scss, src/styles/components/Overflow.scss, src/styles/components/Scrollable.scss, src/styles/components/Select/Select.scss, src/styles/configs/_font.scss, src/styles/configs/_globalVariables.scss, src/styles/resets/_font.scss, src/styles/themes/hs-app/__index.scss, src/styles/themes/hs-app/configs/_globalVariables.scss, stories/Scrollable.js, test/acceptance/components/TagList.spec.js
This update makes some minor adjustments to the UI (mostly CSS) as well as
provides some performance enhancements.
**UI Adjustments**
Inputs were adjusted to better account for the autocomplete background
override, which affects only Chrome. This update was also applied to
Select.
Modals received a `min-height: 0` reset, which resolves some flexbox issues
in Firefox's height calculations.
The font family has been set to system default via CSS variables. The
default font size has also been reduced from 14px -> 13px (also using
CSS variables). The reason for CSS variables is to make theming easier,
which has been applied to the HS App stylesheet, since they require
a different font + font-size.
**Performance Enhancements**
Scrollable's fade calculations are now done without state updates, …
=> UI + Performance enhancements

src/components/Modal/tests/Modal.test.js, src/components/Select/index.js, src/components/Select/tests/Select.test.js, src/styles/components/Select/SelectIcon.scss, stories/Select.js
This update adjusts the Select component to keep the placeholder value
after selecting an option.
=> Select: Keep placeholder

package-lock.json, src/utilities/color.js, src/utilities/docs/color.md, src/utilities/docs/color/darken.md, src/utilities/docs/color/hexToRgb.md, src/utilities/docs/color/lighten.md, src/utilities/docs/color/optimalTextColor.md, src/utilities/docs/color/rgbToHex.md, src/utilities/index.js, src/utilities/tests/color/darken.test.js, src/utilities/tests/color/hexToRgb.test.js, src/utilities/tests/color/lighten.test.js, src/utilities/tests/color/optimalTextColor.test.js, src/utilities/tests/color/rgbToHex.test.js, stories/Colors/index.js, stories/index.js
This update adds a collection of utility functions that manipulate or help
make hex color values easier to work with.
These functions include:
* hexToRgb
* rgbToHex
* optimalTextColor
* lighten
Storybook examples, tests, and docs have been added :).
=> Utilities: Add color functions

src/components/Icon/index.js, src/components/Icon/tests/Icon.test.js, src/components/Modal/index.js, src/styles/components/CloseButton.scss
This update adjusts the interactive styles for the CloseButton, and also
nudges it slightly when used within a Modal.
The Icon component has been enhanced to include a CSS className for the
`name` specified by the icon (to allow for CSS targeting).
=> CloseButton and Icon adjustments

src/components/Portal/index.js
This update adjusts the renderTo checks for Portal to better ensure
that the DOM node exists just before injecting the Portal'ed element
to it.
=> Portal: Better guards to renderTo

src/components/Button/index.js, src/styles/components/Button.scss, stories/Button.js
This update adds a new "pill" theme for the Button component.
=> Button: Add "pill" theme

src/components/Message/Message.js, src/components/Message/tests/Message.test.js, src/styles/components/Message/Message.scss, src/utilities/color.js, stories/EmbedChat/index.js
This update adds a "from" name to the Message component, if the theme is
set to `embed`.
This update also removes the `min-width` for `embed` themed Messages.
=> Message: Add "from" name

src/components/Message/Chat.js, src/components/Message/docs/Chat.md, src/components/Notification/README.md, src/components/Notification/index.js, src/components/Notification/tests/Notification.test.js, src/styles/components/Message/Bubble.scss, src/styles/components/Message/ChatBlock.scss, src/styles/components/Notification.scss, src/styles/components/Notification/Notification.scss, stories/Notification/index.js
This update enhances the `Notification` component by providing it with the
ability to align content to the left or to the right.
The CSS styles that rendered the Notification UI has been abstracted from
`Message/Bubble.scss` to `Notification.scss`.
Lastly, truncation has been added for Notification body text. This is
to provide giant bubbles from appearing if there is too much content.
For added flexibility, the truncation limit can be customized via the
new `truncateLimit` prop.
=> Notification: Enhancements

src/components/Message/Message.js, src/components/Message/tests/Message.test.js, src/styles/components/Message/Media.scss
This update fixes the CSS issue for `Message.Media`, to ensure
that extra top margin is not added if it is the first child.
This update also improves `Message` sub-component type checking.
Tests have been added to check against edge-cases.
=> Message: Minor adjustments

src/styles/components/Message/Media.scss
This update fixes the issue where the `Message.Media` component's `display`
CSS property changes on a hover interaction, causing UI to jump around.
=> Message.Media: Ensure display is consistent

src/components/Avatar/index.js, src/components/Avatar/propTypes.js, src/components/Avatar/tests/Avatar.test.js, src/components/Message/Action.js, src/components/Message/Message.js, src/components/Message/tests/Action.test.js, src/styles/components/Avatar.scss, src/styles/components/Message/Bubble.scss, src/styles/components/Message/Message.scss, src/styles/components/Notification/Notification.scss, src/styles/components/StatusDot.scss, src/styles/configs/_seed-control.scss, stories/Avatar/index.js, stories/EmbedChat/index.js
This update adjusts the UI for the Notifications component.
=> Notification UI Tweaks

src/styles/components/Message/Bubble.scss, src/styles/components/Message/ChatBlock.scss, src/styles/components/Message/Message.scss, stories/Message/default.js
This update adjusts some CSS properties for various components that make up
the Messaging UI for Chat interfaces.
The Message storybook has been updated to include actions for both
from/to recipients.
=> Message: Adjust UI

src/components/Input/README.md, src/components/Input/Resizer.js, src/components/Input/helpers.js, src/components/Input/index.js, src/components/Input/tests/Input.test.js, src/components/Input/tests/Resizer.test.js, src/components/Input/tests/helpers.test.js, src/styles/components/Input/InputGhost.scss, src/utilities/strings.js, src/utilities/tests/strings.test.js, stories/Input.js
This update enhances the `<Input>` component to have better scroll handling
when the user presses Enter. It ensures that the desired content is correctly
in focus at all times.
The input has also been enhanced to support a (bottom/right) offset, to allow
for better integrations with UI that combines textarea + actions.
=> Input: Resizer enhancements + better scroll handling

.flowconfig, package.json, src/components/Attachment/styles/Attachment.css.js, src/components/AttachmentList/__tests__/AttachmentList.test.js, src/components/AttachmentList/index.js, src/components/Overflow/__tests__/Overflow.test.js, src/components/Overflow/index.js, stories/AttachmentList/index.js
This update improves the AttachmentList UX when new attachments are added.
The UI now scrolls to reveal the latest attachment. The left/right
scrolling MATH has also been updated to scroll to the correct amount.
=> AttachmentList: Improve UX on new items

src/components/Input/README.md, src/components/Input/__tests__/Input.test.js, src/components/Input/index.js, stories/Input.js
This PR adds some callbacks to inputs for when the user starts or stops typing in an input.
=> Is typing events for inputs

src/components/Image/README.md, src/components/Image/index.js, src/components/Image/tests/Image.test.js, src/components/Input/index.js, src/components/Message/Media.js, src/components/Message/__tests__/Media.test.js, src/components/Message/docs/Media.md, src/components/Message/styles/Media.css.js, src/styles/mixins/breakpoints.css.js, src/utilities/__tests__/is.test.js, src/utilities/images.js, src/utilities/is.js, stories/Message/media.js
This update enhances the `Image` component to automatically calculate
aspect ratio sizing if `maxHeight` and `maxWidth` are defined.
This allows for the `img` to have a defined dimension before it renders into
the DOM. This interaction benefits UI like `Message.Media`, as content will
no longer jump around while the image attempts to render.
=> Message.Media/Image: Responsive aspect ratio support

src/components/Message/Media.js, src/components/Message/__tests__/Media.test.js, src/components/Message/docs/Media.md, src/components/Message/styles/Media.css.js, src/components/Modal/index.js, stories/Message/media.js
This update enhances the `Message.Media` component with the ability to
render a thumbnail in the preview, if specified.
This update also improves the image responsiveness (CSS) for images
opened within the modal.
Lastly, this also resolves some positioning issues with the Close button.
=> Message.Media: Add thumbanil support + fix close button

src/components/Input/README.md, src/components/Input/__tests__/Input.test.js, src/components/Input/index.js, stories/Input.js
Needed a bind or the execution context gets passed in from the parent.
=> Adding refApplySubmit to input

package.json, src/components/Collapsible/__tests__/Collapsible.test.js, src/components/Message/styles/Media.css.js, src/components/Timestamp/__tests__/Timestamp.test.js, src/styles/components/Card/Card.scss, src/styles/mixins/cardStyles.css.js, src/styles/mixins/cardStyles.scss, stories/Message/media.js
This update adjusts the styles for `Message.Media`, specifically with margins,
border-radius, and box-shadows.
Visually, the `Message.Media` bubbles are spaced/cornered just like any
other message (with directional + sequence awareness).
The box-shadows have also been consolidated with other card-based UI.
=> Message.Media: Adjust styles

.vscode/settings.json, src/components/Message/Content.js, src/components/Message/Media.js, src/components/Message/Message.js, src/components/Message/__tests__/Message.test.js, src/components/Message/styles/Content.css.js, src/components/PreviewCard/styles/PreviewCard.css.js, stories/Message/index.js
This update improves the rendering reliability of isNote for `Message`.
A minor CSS update was added for `PreviewCard` to resolve border style
conflicts.
Lastly, minor refactors were done for ESLint.
=> Message: Improve isNote prop/rendering

src/styles/mixins/breakpoints.css.js, src/styles/resets/baseStyles.css.js, src/styles/resets/font.css.js, src/styles/utilities/variableFontSize.js
Specifically adding `var()` css fallbacks for the CSS variables.
=> Styles: Minor cleanup + improvements

src/components/Attachment/index.js, src/components/Modal/Body.js, src/components/Modal/index.js, src/components/Modal/styles/Body.css.js, src/components/Modal/tests/Body.test.js, src/components/Modal/tests/Modal.test.js, src/styles/components/Modal/ModalBody.scss
This update resolves the `Modal` close repositioning that was introduced in
v0.5.13.
Also, `Modal.Body` has been refactored with Fancy.
=> Modal: Close fix

src/components/Input/README.md
This PR makes small changes to `inputs` README.md.
=> Fix documentation for input

src/components/InfiniteScroller/index.js, src/components/Input/Input.js, src/components/Message/Attachment.js, src/components/Message/Bubble.js, src/components/Message/styles/Bubble.css.js, src/utilities/smoothScroll.js
This update adjusts the (Flex-based) styles of an inner component
of `Message.Bubble` to improve responsive rendering for IE 11.
The level of nested Flexbox-based components led to unpredictable
width calculations.
Other updates include adding a guard for any node element using
`scrollTo`. IE11's console produced an error for this.
---
CC'ing @Charca , @tjbo , @knicklabs
=> IE: Improve rendering stability

package-lock.json, package.json, src/components/EventListener/index.js, src/components/KeypressListener/index.js, src/components/Label/Label.js
https://codesandbox.io/s/ww2kyjp5vw
Originally brought on my radar by @knicklabs and @ShayCichocki (❤️)
I got it working with Codesandbox. Stackblitz is.. another thing. Not sure how to resolve it on there. The issue is that Stackblitz is trying to compile/parse SCSS->CSS things. I don't know how to make it NOT do that.
=> Fix Codesandbox Integration

package-lock.json, package.json, src/components/Avatar/Avatar.js, src/components/Avatar/__tests__/Avatar.test.js, src/components/Avatar/styles/Avatar.css.js, src/components/Message/Action.js, src/components/Message/Bubble.js, src/components/Message/__tests__/Action.test.js, src/components/Message/__tests__/Message.test.js, src/components/Message/index.js, src/components/Message/styles/Bubble.css.js, src/components/Message/styles/ChatBlock.css.js, src/components/StatusAvatar/StatusAvatar.js, src/components/StatusAvatar/__tests__/StatusAvatar.test.js, src/components/StatusAvatar/index.js, src/components/StatusAvatar/utils.js, src/components/StatusDot/StatusDot.js, src/components/StatusDot/styles/StatusDot.css.js, src/components/Text/README.md, src/components/Text/Text.js, src/components/Text/__tests__/Text.test.js, src/components/Text/styles/Text.css.js, stories/Avatar/index.js
This update provides visual adjustments to a handful of Chat relate
Components, such as `Avatar`, `StatusAvatar`, `StatusDot`, `Message.Action`,
`Message.Bubble`, and `Text.
`@helpscout/react-utils` has also been bumped to the latest `1.0.1`, which
improves it's `getValidProps` check
Minor refactors were done. Most notably, `Message`'s sub-components have been setup with `propConnect`
=> Component tweaks and enhancements for Chat

package-lock.json, package.json, src/components/Choice/styles/Choice.css.js, src/components/ChoiceGroup/ChoiceGroup.js, src/components/ChoiceGroup/README.md, src/components/CopyCode/CopyCode.js, src/components/CopyCode/__tests__/CopyCode.test.js, src/components/CopyCode/styles/CopyCode.css.js, src/components/FormGroup/Choice.js, src/components/FormGroup/docs/Choice.md, src/components/Page/Header.js, src/components/Page/__tests__/Header.test.js, src/components/Page/docs/Header.md, src/components/Page/styles/Card.css.js, src/components/Page/styles/Header.css.js, src/components/RadioCard/styles/RadioCard.css.js, stories/Page/Card.js, stories/RadioCard/index.js
This update adjusts the UI for:
* `ChoiceGroup`
* `CopyCode`
* `RadioCard`
* `ChoiceGroup`
These are all very subtle changes. Most of them are for CSS stability when rendering within an application with existing CSS rules.
The `ChoiceGroup` component receives an enhancement, which connects it to `FormLabel.Context`.
=> Choice + Other component adjustments

package-lock.json, package.json, scripts/update-icons.js, src/components/Icon/icons.js, src/icons/plus-large.svg, src/icons/plus-small.svg
This update adds 2 new `plus` icons, as well as a handy `npm run update:icons` script.
=> Icon: Add plus icon

package-lock.json, package.json, stories/AvatarStack/AvatarStackV2.js
This update adds [Artboard](https://github.com/helpscout/artboard) to Blue for UI development.
As a test, the `AvatarStackV2` component story was setup with an `<Artboard />` and `<Guide />` components.
https://media.giphy.com/media/dZ5k7sNDl5UnPQOsCy/giphy.gif
=> Add Artboard!

src/components/Message/styles/Chat.css.js, stories/Message/chat.js
This update fixes the "From" Message.Chat bubble radius, specifically the
one that appears in the top right corner.
Before: (Broken)
=> Message.Chat: Fix bubble radius

.eslintrc, package-lock.json, package.json, src/components/ArticleCard/ArticleCard.tsx, src/components/ArticleCard/__tests__/ArticleCard.test.js, src/components/ArticleCard/index.ts, src/components/ArticleCard/styles/ArticleCard.css.js, src/components/AvatarStack/styles/AvatarStack.css.js, src/styles/mixins/cardStyles.css.js, stories/ArticleCard.stories.js
This update refactors and adjusts the UI and interactions for `ArticleCard`, to bring it up to the latest/greatest from HSDS (Embeddables).
The ArticleCard story has been updated with Artboard + Knobs to showcase all the various states and interactions :)
Netlify preview:
https://5c01aa55e5cd161e4c6c9ae1--hsds-react.netlify.com/?selectedKind=ArticleCard&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
=> ArticleCard: UI Updates

package-lock.json, package.json, src/components/Modal/index.js, src/components/Pop/Popper.js, src/components/Pop/__tests__/Pop.test.js, src/components/Pop/__tests__/Popper.test.js, src/components/Pop/index.js, src/components/Popper/Popper.js, src/components/Portal/index.js, src/components/Portal/tests/Portal.test.js, src/components/Tooltip/Tooltip.js, src/components/Tooltip/styles/Tooltip.css.js, stories/Tooltip.stories.js
This update fixes some `Tooltip` and `Modal` behaviour and interaction. The common fix for both would be adjustment made to `Portal`, which controls the mounting mechanism for these components.
Other adjustments were made to `Tooltip` to ensure the `arrow` color renders correctly, as well as removing duplication (which only affected React 16 environments).
The `Tooltip` story was much improved with Artboard and Knobs to provide a better QA environment.
=> Tooltip + Modal Fixes

package-lock.json, package.json, src/components/Modal/Body.js, src/components/Modal/Modal.js, src/components/Modal/__tests__/Modal.test.js, src/components/Portal/index.js, stories/Modal.stories.js
This update improves the stability of Portal/Modal components. The closeButton repositioning mechanism for `Modal` (and it's sub-components) have also been improved.
=> Portal/Modal Fixes

src/components/Message/Media.js, src/components/Message/__tests__/Media.test.js, src/components/Message/docs/Media.md, src/components/Message/styles/Media.css.js, src/components/Modal/styles/Modal.css.js, stories/Message/Message.Media.old.stories.js, stories/Message/Message.Media.stories.js
This update adjusts the UI for `Modal` to be consistent with the latest
HSDS Design requirements (specifically the `box-shadow` styles).
The `Modal` that renders within `Message.Media` has been adjusted with
better animation defaults to match the experience we have in Beacon Embed.
For added flexibility, these props have been exposed to the component for
refined adjustments.
Lastly, the Story for the `Message.Media` component has been re-written
to include Knobs for a better design/QA experience.
---
Tagged @digitaldesigner for design QA
URL:
https://deploy-preview-472--hsds-react.netlify.com/?selectedKind=Message&selectedStory=Media&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
Click on the image to see the modal
Tagged @tjbo for code review
=> Modal + Message.Media Modal updates

src/components/ProgressBar/README.md
In this PR we update the ProgressBar docs to match the available values that were in the story.
=> Fix progress bar docs

.gitignore, .storybook/webpack.config.js, .travis.yml
This update attempts to speed up storybook be adding some
properties to the TS compiler (awesome-typescript-loader).
=> Speed up Storybook

.gitignore, package-lock.json, package.json, src/components/Button/ButtonV2.js, src/components/Button/__tests__/ButtonV2.test.js, src/components/RouteWrapper/__tests__/RouteWrapper.test.js, src/components/RouteWrapper/index.js, stories/ButtonV2.stories.js
This update adds a special `data-bypass` property to the `Button` and `Link`
components to handle the route navigation within a Marionette + React routing
hybrid environment.
=> Button/Links: Enhance with marionette + React routing support

.storybook/config.js, .storybook/storybook.css, src/components/Page/styles/Actions.css.ts, src/components/Page/styles/Card.css.ts, src/components/Page/styles/Header.css.ts, src/components/Page/styles/Page.config.css.ts, src/components/Page/styles/Page.css.ts, src/components/Page/styles/Section.css.ts, stories/Page/Page.Example.stories.js, stories/Page/decorators.js
This update changes the breakpoints for the max-width and the changes the padding applied at different breakpoints. 
The width is constrained until 1050px (previously 1000px).
Beyond the default padding (y: 50px, x: 50px), we introduced:
Wide Screen: 1050 - 1350 (y: 50px, x: 100px)
Super Wide Screen: 1350 - 1450 (y: 65px, x: 50px)
Full Screen: 1450+ (y: 65px, x: 100px)
I'll update this with a link to the Story after Storybook rebuilds.
See: https://github.com/helpscout/hsds-product-ui/wiki/Responsive
=> Page Component: Update Responsive Styles

package-lock.json, package.json
This update fixes the Fancy build by bumping Fancy to v2.2.6.
=> Fancy: Fix Emotion build

src/components/HsApp/HsApp.css.js
This update fixes the import paths for the utilities used in HsApp.css.js
=> HS App: Fix import for HsApp.css.js

.remake/component/remake-name/remake-name.css.ts, .remake/component/remake-name/remake-name.tsx, .remake/component/remake-name/remake-name.types.ts, .remake/component/remake-name/styles/remake-name.css.ts, package-lock.json, package.json
This update adjusts the `.remake` templates with the latest TS conventions
=> Remake: Template updates

src/components/ActionSelect/ActionSelect.ContentResizer.tsx, src/components/ActionSelect/ActionSelect.tsx, src/components/ActionSelect/ActionSelect.types.ts, src/components/ActionSelect/README.md, src/utilities/smoothScroll.ts, stories/ActionSelect.QA.stories.js, stories/ActionSelect.stories.js
(GIF: Dramatized version. 3000s animations speeds to show the scroll/height animations)
This update improves the UX for the ActionSelect component by scrolling the
content into view when something is selected. The scrolling animation timing
is also synchronized with the height animations, providing the user with a
super smooth experience.
We decided to pursue this enhancement after implementing this component into
the app. When it's positioned with form elements, we found that it was
difficult to (visually) focus on the ActionSelect fields. It felt
cumbersome to have to manually scroll into position.
The auto scroll into view mechanism resolves this issue!
=> ActionSelect: Improve UX by coordinating focus + scrolling

src/components/Dropdown/V2/Dropdown.ItemSelectedCheck.tsx, src/components/Dropdown/V2/Dropdown.css.js, stories/DropdownV2.stories.js
This update make sure the checkmark icons is always align no matter the size of the label. It also makes sure that the icon size will always be the same
=> Multi select dropdown alignment

src/components/EmojiPicker/EmojiPicker.tsx, src/components/EmojiPicker/__tests__/EmojiPicker.test.tsx, src/components/EmojiPicker/emojiSet.ts, src/components/EmojiPicker/styles/EmojiPicker.css.ts, stories/EmojiPicker.stories.js
This update includes a few small Emoji Picker refinements:
- rename heart emoji
- changed the displayed Heart emoji symbol
- refactor trigger colors
- add handler for `onOpen` and `onClose` Dropdown events
- Clean up Storybook stories
- Fix bug where `size` was not being passed to Emoji `Item` component
=> Emoji Picker refinements

src/components/EmojiPicker/EmojiPicker.tsx, src/components/EmojiPicker/styles/EmojiPicker.css.ts, stories/EmojiPicker.stories.js
Refactor Emoji Picker styles to handle hover and active states.
=> Emoji picker styling updates

src/components/Input/Input.tsx
This adds the count prop so that text will render in a thinner style.
=> Fix count prop so that text renders properly

src/components/Badge/Badge.tsx, src/components/Badge/README.md, src/components/Badge/styles/Badge.css.ts, stories/Badge.stories.js
This updates the Badge component to:
1 - be able to make inverted badges
2 - be able to pass a custom color
=> COMMS-177 Update badge styles with inverted and custom colors

src/components/Input/Input.tsx, stories/Input.stories.js
This PR modifies to char text validator of the Input so that it only shows the char validator and it's associated styles when the limit is rounded down to the nearest 10th.
So if you have a char limit of 106, instead of showing the validator at 53 chars left, it will show it at 50.
=> Round char validator down to the nearest 10th

package-lock.json, package.json, src/styles/configs/_colorway.scss, src/styles/configs/colorway.ts
This PR upgrade colorway to v0.4.0 so we can add two missings color from our new palette:
=> Upgrade colorway to add missing indigo and whaletail color

package-lock.json, package.json, src/components/EditableField/EditableField.tsx, src/components/EditableField/EditableField.types.ts, src/components/EditableField/EditableField.utils.ts, src/components/EditableField/__tests__/EditableField.test.tsx, src/components/EditableField/styles/EditableField.Input.css.ts, src/components/EditableTextarea/EditableTextarea.tsx, src/components/EditableTextarea/EditableTextarea.types.ts, src/components/EditableTextarea/__tests__/EditableTextarea.test.tsx, src/components/EditableTextarea/styles/EditableTextarea.css.ts, src/utilities/pkg.ts, stories/EditableField.stories.js, stories/EditableTextarea.stories.js
Adds a new prop for both EditableField and EditableTextarea to allow floating labels like the ones we have on Composite Fields.
=> Adds floating labels to editable field and textarea

src/components/AvatarSelector/AvatarSelector.tsx, src/components/AvatarSelector/README.md
Adds the prop `initials` to AvatarSelector
=> Add initials to AvatarSelector

src/components/Icon/icons.embed.js
[Jira Ticket](https://helpscout.atlassian.net/browse/BEMBED-56)
This is needed to support adding the `EmojiPicker` to Beacon Embed
=> Add Emoji svg to Embed icon bundle

src/components/AvatarSelector/AvatarSelector.tsx
Bump the tab index on AvatarSelector to 0
=> Fix tabindex on AvatarSelector

src/components/AvatarSelector/styles/AvatarSelector.css.js
Fixs the color and adjusts the border gap of the AvatarSelector
=> Fix avatar selector border

src/components/Page/styles/Page.Card.css.ts
Change bottom margin on page card to 20px. This is a global change.
=> Tweak page card bottom margin

src/components/CopyButton/CopyButton.tsx, src/components/CopyButton/styles/CopyButton.css.js, src/components/CopyInput/CopyInput.tsx, stories/CopyButton.stories.js
This updates the copy button styles for HSAPP-995
=> Tweak copy button styles

package-lock.json, src/components/Avatar/Avatar.types.ts, src/components/Portal/Portal.tsx, src/components/VerificationCode/README.md, src/components/VerificationCode/VerificationCode.css.js, src/components/VerificationCode/VerificationCode.js, src/components/VerificationCode/VerificationCode.stories.js, src/components/VerificationCode/VerificationCode.test.js, src/components/VerificationCode/VerificationCode.utils.js, src/components/VerificationCode/index.js
New component!
https://www.figma.com/file/LM9TDdqD85RBXvz6EipJL6/Forms-Verification-Code?node-id=0%3A1
The verification code component is designed to be used for 2FA. The _feel_ of it is as if you are using a normal `<input />`, but the look is quite different.
For this component, some decisions of note I went with:
- Avoid usage of React State
- Make use of native browser functionality as much as possible (like using `<input />`) and some less known css features
Here's a video with more details that goes into how I went about it and why some things exist:
🎥 https://www.loom.com/share/a2a9e6aa44664445a3c922aa169daff2
=> Verification Code

package.json, src/components/TypingDots/README.md, src/components/TypingDots/TypingDots.tsx, src/components/TypingDots/TypingDots.types.ts, src/components/TypingDots/TypingDots.utils.ts, src/components/TypingDots/__tests__/TypingDots.test.tsx, src/components/TypingDots/index.ts, src/components/TypingDots/styles/TypingDots.css.ts, stories/TypingDots.stories.js
This creates a new component to be used as the new typing indicator in Message.Chat.
=> Create TypingDots Component

src/components/RateAction/README.md, src/components/RateAction/RateAction.css.js, src/components/RateAction/RateAction.js, src/components/RateAction/RateAction.stories.js
In this PR we add a withBorder variation of the RateAction component.
http://c.hlp.sc/576a1dc0f46f
=> Add withBorder for rate action

src/components/CopyInput/CopyInput.tsx, src/components/Modal/Modal.tsx, src/components/VerificationCode/VerificationCode.js, src/components/VerificationCode/VerificationCode.stories.js, src/components/VerificationCode/VerificationCode.test.js, src/components/VerificationCode/VerificationCode.utils.js, stories/CopyInput.stories.js
This PR is bringing changes from the Focus improvements (#807) pull request into v2 as an hot fix
=> Merge changes from Focus improvements (#807)

jest.config.js, src/components/Modal/Modal.ActionFooter.tsx, src/components/Modal/Modal.types.ts, src/utilities/__tests__/focus/findCurrentFocusedNodeIndex.test.js, src/utilities/__tests__/focus/findFirstFocusableNode.test.js, src/utilities/__tests__/focus/findFocusableNodes.test.js, src/utilities/__tests__/focus/findLastFocusableNode.test.js, src/utilities/__tests__/focus/findNextFocusableNode.test.js, src/utilities/__tests__/focus/findPreviousFocusableNode.test.js, src/utilities/__tests__/focus/focusNextFocusableNode.test.js, src/utilities/__tests__/focus/focusPreviousFocusableNode.test.js, src/utilities/focus.ts, stories/Modal.stories.js
This PR is bringing changes from the Add disabled props + Fix modal focus trapping (#809) pull request into v2 as an hot fix
It also update the test coverage threshold value to match v3
=> Merge changes from Add disabled props + Fix modal focus trapping (#809)

src/components/Modal/Modal.HeaderV2.tsx, src/components/Modal/Modal.tsx, src/components/Modal/Modal.types.ts, src/components/VerificationCode/VerificationCode.js, src/components/VerificationCode/VerificationCode.stories.js, src/components/VerificationCode/VerificationCode.test.js
This PR is bringing changes from the Tab focus cycling in Modal  (#811) pull request into v2 as an hot fix
=> Merge changes from Tab focus cycling in Modal (#811)

src/components/Message/styles/Action.css.js, src/components/Message/styles/Message.css.js
[Jira Ticket](https://helpscout.atlassian.net/browse/HSAPP-1956)
Add more spacing to each Chat message group.
=> Add spacing to Chat message groups

src/components/ArticleCard/ArticleCard.css.js, src/components/Attachment/Attachment.css.js, src/components/CheckMarkCard/CheckMarkCard.css.js, src/components/Datepicker/Datepicker.test.js, src/components/Depth/Depth.storiesHelpers.js, src/components/FluffyCard/FluffyCard.css.js, src/components/FluffyCard/FluffyCard.jsx, src/components/MessageCard/MessageCard.css.js, src/components/Modal/Modal.css.js, src/components/Modal/Modal.jsx, src/components/Notification/Notification.css.js, src/components/Page/Page.config.js, src/components/Page/Page.css.js, src/components/Page/Page.jsx, src/components/RadioCard/RadioCard.css.js, src/guides/Depth.stories.mdx, src/styles/mixins/cardStyles.css.js, src/styles/mixins/depth.css.js
Use the new Depth mixins in HSDS components:
d200 - FluffyCard
d300 - Page
d300 - RadioCard
d400 - CheckmarkCard
d400 - ArticleCard
d400 - Attachment with preview
d600 - Notification
d600 - MessageCard
d700 - Modal
=> Add Depth to components

docs/contributing/storybook.md
The link to [writing stories](https://hsds.helpscout.com/?path=/story/welcome-4-writing-stories--page) was broken (screenshot below). This PR fixes the link.
=> Fix writing stories link

src/components/CheckMarkCard/CheckMarkCard.css.js, src/components/CheckMarkCard/CheckMarkCard.jsx
Fix animation issues
https://helpscout.atlassian.net/browse/COMMS-1140
=> CheckmarkCard: fix animation jankiness

docs/contributing/creating.md
The link to the contributing styling guide was broken on the creating page, this fixes that 😄 
=> Updates broken link in contributing docs

src/components/Emoticon/Emoticon.css.js
Updates emoji face color to increase contrast w/fill color
=> HSDS-187 Update emoticon face to increase contrast

src/components/MessageCard/MessageCard.css.js, src/components/MessageCard/MessageCard.jsx, src/components/MessageCard/MessageCard.stories.mdx, src/components/MessageCard/MessageCard.test.js, src/components/MessageCard/MessageCard.utils.js, src/components/MessageCard/components/MessageCard.Action.jsx, src/components/MessageCard/components/MessageCard.Body.jsx, src/components/MessageCard/components/MessageCard.Content.jsx, src/components/MessageCard/components/MessageCard.Image.jsx, src/components/MessageCard/components/MessageCard.Subtitle.jsx, src/components/MessageCard/components/MessageCard.Title.jsx
**[Jira Issue](https://helpscout.atlassian.net/browse/BEMBED-268)**
In order to provide a better user experience when showing Messages with images in them, we're updating the logic so that the Message only becomes visible after the image has finished loading.
With this update we now have three scenarios to test:
1. A Message without an image should become visible right away.
2. A Message with an image should become visible after the image has finished loading.
3. A Message with an image that fails to load (with a 404 error for example) should become visible without rendering the image.
=> BEMBED-268: Updates to MessageCard component

package-lock.json, src/components/CheckMarkCard/CheckMarkCard.css.js, src/components/CheckMarkCard/CheckMarkCard.jsx, src/components/CheckMarkCard/CheckMarkCard.stories.mdx, src/components/CheckMarkCard/CheckMarkCard.test.js
Reverts helpscout/hsds-react#932
=> Revert "HSDS-186 new CheckmarkCard UI"

package-lock.json, src/components/CheckMarkCard/CheckMarkCard.css.js, src/components/CheckMarkCard/CheckMarkCard.jsx, src/components/CheckMarkCard/CheckMarkCard.stories.mdx, src/components/CheckMarkCard/CheckMarkCard.test.js
Reverts helpscout/hsds-react#935 to bring back helpscout/hsds-react#932
=> Bring back HSDS-186 new CheckmarkCard UI

src/components/DropList/DropList.ListItem.jsx, src/components/DropList/DropList.css.js, src/components/DropList/DropList.jsx, src/components/DropList/DropList.stories.mdx, src/components/DropList/DropList.test.js, src/utilities/specs/dropdown.specs.js
While using DropList in the _real world_ we found a couple of enhancements:
- Don't always show the scrollbar (should depend on the number of items)
- Long text items should be truncated in one line with ellipsis
- Laser Targeting: if you need to target a specific List Item for styling (or else), you can add the property `className` to each item in the array, the value will be added to the existing css class names on the `DropListItem`:
```js
const items = [
{ label: 'a', className: 'paintItBlue' },
{ label: 'ab' },
{ type: 'divider' },
{ label: 'b', className: 'paintItGreen' },
]
```
will result in something like:
```html
<ul>
<li class="DropListItem paintItBlue">a</li>
<li class="DropListItem">ab</li>
<li class="DropListItem DropListItem--divider"></li>
<li class="DropListItem …
```
=> DropList UI tweaks

src/components/Table/Table.HeaderCell.jsx, src/components/Table/Table.jsx, src/components/Table/stories/TableWithPagination.js
- Updates header cells classname
- Spreads `rest` props on table
=> Table quick tweaks

src/components/SidePanel/SidePanel.jsx, src/components/SidePanel/SidePanel.storiesHelpers.js, src/components/SidePanel/SidePanel.test.js
Adds the ability to close the Panel when clicking outside, same as SimpleModal
=> Adds closeOnClickOutside to SidePanel

src/components/CopyButton/CopyButton.jsx, src/components/CopyButton/CopyButton.utils.js, src/components/CopyValue/CopyValue.css.js, src/components/CopyValue/CopyValue.js, src/components/CopyValue/CopyValue.stories.mdx, src/components/CopyValue/CopyValue.test.js, src/components/CopyValue/index.js, src/components/HSDS/GlobalStyle.js, src/components/Tag/Tag.css.js, src/components/TagList/TagList.css.js, src/components/VerificationCode/VerificationCode.css.js
This update brings the copy conversation id (from hs-app-ui) into a new HSDS component. This behavior will be reused throughout the application so we thought it was a good idea to create a component flexible enough to be customize when needed but also strict enough to keep the behavior the same across the app. 
The component will receive a `value` prop. When the button is clicked, the value will be added to the clipboard. It it still possible for dev to extend the `onClick` action. 
```javascript
// when the user click on the icon, "123456789" will be added to the clipboard
<CopyValue value="123456789" />
```
| prop name     |  |
|----------|---------|
| prefix    | will add  a muted prefix before the value  |
| renderValue |  custom render for the value    |
| onReset | Callback when the …
=> New CopyValue Component

src/components/EditableField/EditableField.Actions.jsx, src/components/EditableField/EditableField.jsx, src/components/EditableField/EditableField.stories.mdx, src/utilities/node.js
Found an issue that when clicking around values in the same field, the active state was all wonky:
Check if the next element receiving focus is part of the same EF and act accordingly:
Pass a `buttonAttrs` object to attach attributes directly on the html button (such as aria labels): `{ buttonAttrs: { 'aria-label': 'My important button' } }`
=> EditableField issues

src/components/IconButton/IconButton.css.js, src/components/IconButton/IconButton.jsx, src/components/IconButton/IconButton.stories.mdx, src/components/IconButton/IconButton.test.js
This update add a status indicator on the `IconButton` component. Some new UI work requires this button to have a red dot on demand. It was easier to implement within the core component vs doing it as a new component in our hs-app-ui stack. The status indicator was build mainly for the outlined button, but it is supported for all variants.
**Outlined**
**Hover**
**Seamless**
**Filled**
**Size small**
We also took the time in this update to cleanup the IconButton tests. Doesn't mean the tests list is a complete one (we still need to address that).
=> IconButton status indicator

src/components/Attachment/Attachment.jsx, src/components/Attachment/Attachment.stories.mdx, src/components/Attachment/Attachment.test.js, src/components/Icon/icons.all.js, src/components/MessageCard/MessageCard.jsx, src/components/MessageCard/MessageCard.stories.mdx, src/components/MessageCard/MessageCard.test.js, src/components/MessageCard/components/MessageCard.Image.jsx, src/components/MessageCard/components/MessageCard.Video.jsx, src/icons/play-video-large.svg
Added possibility to embed Video in a Message, by setting provided iframe HTML code on the MessageCard.
There is a handler to not show a Message until the video iframe is fully loaded.
This can be tested by opening newly added stories: `MessageCard` -> `With video` and `With iframely video url`.
The second story is added for the purpose of showing difference between embedding video directly from service URL vs. using Iframely hosted ones. In the second case, waiting for video to load before showing a Message, and you can observe a moment where empty element is visible on the Message (which should not happen on the first story).
This is something that has be dealt with outside of HSDS, but I'm leaving those two here so we have easy comparison.
Additionally, new icon `play-video-large` has …
=> HSDS-259: Embedding video in Message and Attachment custom content

src/components/Table/Table.Cell.jsx, src/components/Table/Table.Row.jsx, src/components/Table/Table.css.js, src/components/Table/Table.test.js, src/components/Table/Table.utils.js, src/components/Table/stories/ConvoList/ConvoList.css.js, src/components/Table/stories/ConvoList/ConvoList.customCells.js, src/components/Table/stories/ConvoList/ConvoList.js, src/components/Table/stories/Table.stories.mdx, src/components/Table/stories/TableWithPagination.js
Sometimes we need a link or button inside a cell and have `onRowClick`, but we don't want to fire 2 events, we just want to fire the event of the clicked (or enter press) element.
> If you have focusable elements inside the cells, such as an <a> or <button> AND have `focusableRows` set to `true`, you might want to set `tabindex=-1` on any element you don't want to focus, see the story and code below where we do this to the link, but leave the button focusable
Also, often we need to clear the padding on the cell and apply our own on cells from a certain column, DOing so via styled components is currently possible, but overcomplicated. So we add a custom field on the columns data: `clearCellPadding`, when passing this, we set the padding for all the cells in a specific column to 0.
> For …
=> Table: enhances the ability to have clickable elements inside a cell

src/components/Badge/Badge.jsx, src/components/FilteredList/FilteredList.css.js, src/components/FilteredList/FilteredList.jsx, src/components/FilteredList/FilteredList.test.js
For a new project, the badge UI in a filtered list was updated. We modify the component to match those new figma styles:
At the same time we:
-fixed the focused style when there is a tooltip
-rewrite the component as a functional one
-rewrite the test to only use RTL
=> HSDS-262 New Filtered badge UI

src/components/DropList/DropList.downshift.common.js
https://helpscout.atlassian.net/browse/HSDS-276
=> [DropList] fixes multiselection using keyboard
